### ISSUE TITLE
Show linked hashes on the game's page

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAWeb#1]
It would be useful to show the linked hashes for regular users. They could check if they are using an acceptable ROM.

**Comment by ahstro** [comment]
This seems like a fairly easy feature to implement, but I am not familiar with the code base at all, so I might be wrong. Is it simply a matter of priority that's keeping this from happening or is it actually hard to do?

I'd look into it myself, but don't want to bother setting up the dev enviroment until #44 is closed

**Comment by meleu** [comment]
It's not hard to implement. But as we are refactoring the code (moving to laravel framework #42), I prefer to wait for the new code.

**Comment by meleu** [comment]
Implemented in #136 .
