### ISSUE TITLE
Game page titles with apostrophes (') are transformed into two apostrophes ('')

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAWeb#100]
**The change needed:**
Correct the bug which is changing ' into ".

I have no idea the cause. This issue came into play roughly 6 months ago. It is notable that some developers have a work around which is inserting an apostrophe via unicode which reads as ``&#39;`` in html. If you search for ``&#39;``. You will find every instance where this is in use.

**Comment by luchaos** [comment]
i guess this is related to sanitising input before inserting into the database. 
i'll write in-depth tests to see which input get masked and encoded which way and how they end up in the database.

it might require a separate database migration step to clean these completely.
related to that: looking at the database schema it seems everything is in CHARSET=latin1 COLLATE=latin1_general_ci when it should be CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci - the site itself is output in utf8 as well.

**Comment by Jamiras** [comment]
I assumed that was a result of the migration to the new server, like the Cyrillic corruption: http://retroachievements.org/viewtopic.php?t=2202&c=26033

Are you saying it still happens?

**Comment by Jamiras** [comment]
Must be a DB thing: http://retroachievements.org/Game/669 looks okay.

**Comment by kdecks** [comment]
It does still happen. Any time you put ``'`` in a title it becomes ``''``. As in **two apostrophes, not a quotation mark.

In example of ``Link's Awakening`` a dev put the html apostrophe as a work around. If you search for link's awaking on Site you will see it displays it as ``Link&#39;s Awakening, The (Game Boy)``.

You can see the change that happens for yourself if you rename any title with a ``'``.

@luchaos as for cleaning them, I think there are few enough entries with this problem that after the problem is fixed they can all be corrected manually without much effort.

**Comment by meleu** [comment]
While browsing the code I noticed that this behavior is explicitly intentional, as we can see in [this line of code executed when uploading an achievement](https://github.com/RetroAchievements/RAWeb/blob/1c828300046c11de0ded7d808dd9632dd2f4d5f3/lib/database/achievement.php#L775).

Maybe @ScottFromDerby could explain the reason.

**Comment by kdecks** [comment]
I think this was possibly an attempt to turn single quotations into double quotations, forgetting about apostrophes. I'd suggest removing lines 1025 and 1026.

**Comment by kdecks** [comment]
It just occurred to me that this is probably the source of many code notes being overwritten with ''. If so this could have been the cause of more problems than initially though.

**Comment by kdecks** [comment]
@luchaos explained in devs chat that this is a security measure. It will not be an issue in v2 and will not be fixed in v1.
