### ISSUE TITLE
Game compare counts hardcore unlocks twice

### ISSUE THREAD

**Issue by luchaos** [RetroAchievements/RAWeb#1016]
Says 24 / 35 ...
![Screenshot 2022-06-03 at 20 54 36](https://user-images.githubusercontent.com/1280590/171930130-c4ec8e08-f61d-4311-acc2-947dc3fb7c13.png)
... when it's 12 / 35 hardcore:
![Screenshot 2022-06-03 at 20 54 57](https://user-images.githubusercontent.com/1280590/171930144-8c54b939-6909-43c4-956f-2364bf1cb26c.png)

**Comment by Tsearo** [comment]
I've got a fix for this included in my WIP Softcore point update once that is finished 👍
