### ISSUE TITLE
[Feature Request] Support for accountless, offline achievements

### ISSUE THREAD

**Issue by dio-gh** [RetroAchievements/RAWeb#1044]
Hi all,

I've been wondering if it was possible to facilitate support for accountless, offline achievements, and if you guys would be okay with that in the first place. The core idea is that some people (including me) may not be interested in tracking/sharing their achievements online, at least not right away, and thus might find having to create a RetroAchievements account an unnecessary drag, or might not even discover the feature in the first place¹.

For this to work, emulators that implement RetroAchievements support would need to be able to either scrape² all the achievements, or collect a designated archive automatically prepared for this purpose. This could be some agreed upon archive containing a cheat database with all the assets (icons, names, descriptions) in some agreed upon format, or something of the sort.

What do you guys reckon?

¹ People may or may not know about RetroAchievements, and the settings panels of emulators is not usually the most accessible thing. If they never get an achievement, they might not know it's possible to get any, especially not that it needs to be set up.

² While it is technically already possible to scrape the achievements through the website, what I'd be thinking of is more in the way of a new API endpoint designated for this purpose (supplying arbitrary achievement data). Hence why I'm opening the ticket here.

P.S.: Apologies if I'm posting this to the wrong repo, I'm not familiar with this project beyond superficial levels.

**Comment by meleu** [comment]
I suggest to close this issue and open a new one specifically requesting something like "provide an API endpoint to get achievement data via unauthenticated requests".

Yeah, I'd love to have offline achievements in a small gadget like the Miyoo Mini.

I tried a movement towards this goal in the [OnionOS repo](https://github.com/jimgraygit/Onion/discussions/394) but it didn't take much attention there...

**Comment by luchaos** [comment]
See https://github.com/RetroAchievements/RAWeb/discussions/1043#discussion-4184554
