### ISSUE TITLE
login_app should return case-corrected user name

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RAWeb#109]
The user login appears to be case insensitive. I can log in with either `Jamiras` (capital J) or `jamiras` (lowercase J), but if I use the latter, my avatar is not correctly downloaded for use in the emulator.

http://retroachievements.org/UserPic/Jamiras.png returns the image correctly
http://retroachievements.org/UserPic/jamiras.png returns 404 not found

I believe this can be fixed by modifying `login_app.php` to return the properly cased user name in the response.

The response returned by `login_app.php` currently returns the user as passed to it:
```{"Success":true,"User":"jamiras",...}```

It should return the properly cased user:
```{"Success":true,"User":"Jamiras",...}```

**Comment by SyrianBallaS** [comment]
I actually remember running into this a long time ago but forgot about it.

**Comment by luchaos** [comment]
this will be resolved in api v2 and should be doable for v1 retroactively
