### ISSUE TITLE
create a form page to request manual award

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAWeb#110]
**Note:** this is not a feature to be implemented soon. Maybe we need the notifications system to tag admins before implementing this.

Our #help-me channel at discord is turning into a #gimme-the-cheevo channel, and we constantly have to explain that users must provide more info.

Then I thought in a form with the following fields:

- the ticket for the buggy cheevo (not necessary if it was a network problem)
- the achievement ID
- a proof (could be a link to an image/video)
- comments

**Comment by kdecks** [comment]
Great idea
