### ISSUE TITLE
Ticket submitted widget displays wrong color.

### ISSUE THREAD

**Issue by Ben-Ghazi** [RetroAchievements/RAWeb#1104]
It shows up as red instead of green, which makes people think something went wrong at first when creating the ticket.

![image](https://user-images.githubusercontent.com/39404689/186208547-117dac1e-886d-4b9c-b37e-3da7bea4a5b2.png)

Also the wording could be a bit better, "Your ticket has been successfully submitted." or "Your issue has been successfully submitted." Either one works but when combined it sounds off.

**Comment by Jamiras** [comment]
This appears to have been fixed with the 2.0.0 rollout. The message now appears in green and simply says "Submitted."
![image](https://user-images.githubusercontent.com/32680403/190868196-e279d58d-3d15-40ec-8a1d-d4c722f20961.png)
