### ISSUE TITLE
Achievement description/title overlap with other fields

### ISSUE THREAD

**Issue by Jazerus** [RetroAchievements/RAWeb#1106]
Under some circumstances, achievement descriptions and titles don't break their lines early enough and overlap with the "won by" section of the achievement display. You can find an example screenshot for descriptions taken from the Link's Awakening DX (game ID 5371) page here: https://i.imgur.com/mmGSK9B.png

I wasn't able to easily find an example of title overlap, but I know I have seen it before as well. I'd imagine this might be a bigger problem on mobile resolutions but it does show up occasionally for desktop resolutions as well.

**Comment by Jazerus** [comment]
RAWeb 2.0.0 seems to have resolved the underlying issue here at least on desktop resolutions. I'll leave this open until a developer closes it in case any new problems along these lines are present, but I am not seeing anymore problems.

**Comment by Jamiras** [comment]
Continuing with the example provided above, both the title and description appear to be wrapping.
![image](https://user-images.githubusercontent.com/32680403/190872767-e894a11d-6843-4c68-b645-df5c45b7d17a.png)

> I'll leave this open until a developer closes it in case any new problems along these lines are present, but I am not seeing any more problems.

If new problems are found, new issues can be opened.
