### ISSUE TITLE
a little trick to add an "edit this page" link on the docs

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAWeb#111]
The mkdocs (tool used to generate the RADocs pages) provide a way to put an "edit this page" link on the pages, but it has a limitation: the name of the page will be always the trailing part of the URL.

The github wiki URL to edit a wiki page is `https://github.com/blablabla/wiki/page/_edit`. As you can see, `_edit` is the trailing part of the URL.

A friend from RetroPie project made a trick to circumvent this limitation and shared the code with me. But I'm not sure where I should put this code in order to make it accessible via `http://retroachievements.org/wikiedit.php`.

@luchaos , could you help me with this? 

```php
<?php

$page = $_GET['page'];
// remove .md
$page = substr($page, 0, -3);
if ($page == '/index') {
    $page = '/Home';
}
header("location: https://github.com/RetroAchievements/docs/wiki$page/_edit");
```

**Comment by luchaos** [comment]
this should work fine, deals with missing/superfluous slashes and empty requests
```
<?php
if(empty($_GET['page'])) {
    return;
}
$page = pathinfo($_GET['page'])['filename'];
if(empty($page)) {
    return;
}
switch ($page) {
    case 'index':
        $page = 'Home';
        break;
}
header("location: https://github.com/RetroAchievements/docs/wiki/$page/_edit");
```

**Comment by meleu** [comment]
done in e63351a8318468803238269ef8b9f898149aeb65
