### ISSUE TITLE
Unable to reset achievement progress in RAWeb 2.0.0

### ISSUE THREAD

**Issue by suspect15** [RetroAchievements/RAWeb#1116]
![image](https://user-images.githubusercontent.com/106546659/190854799-04b00d05-9c0e-4ab7-b634-d6474d9f75d5.png)

I get this error when trying to reset all progress in a set or individual achievement progress.

**Comment by starblades** [comment]
This appears to happen on the Game page, the settings option for resetting a game still appears to work
