### ISSUE TITLE
link to leaderboard in feed is broken

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RAWeb#115]
![image](https://user-images.githubusercontent.com/32680403/39097580-71bb4d76-461b-11e8-8e56-0763bb5e66a3.png)
The "Mario Circuit 4" link is: http://retroachievements.org/147'/leaderboardinfo.php?i=%27
The link on the page is: http://retroachievements.org/leaderboardinfo.php?i=147

The same link is generated when improving the score. The time/score also uses the same link. The game/user links work correctly.

**Comment by GameDragon2k** [comment]
Which page is this? The frontpage feed? The leaderboard links seem to be working properly on `/feed.php`.

**Comment by Jamiras** [comment]
yes, global feed (also friends only)
