### ISSUE TITLE
Red error bar on page load/change

### ISSUE THREAD

**Issue by snowpin** [RetroAchievements/RAWeb#1194]
**Describe the bug**
Red error box showing when sometimes loading a page and it stays and sometimes it wont be there but when I click on a link to somewhere else I see it flicker on and back off. (To be clear, nothing special I do to get this besides load the page. I haven't edited or submitted changes.)

**To Reproduce**
Just load pages randomly

**Screenshots**
![image](https://user-images.githubusercontent.com/6635720/194927157-69704b7e-bd75-413c-a19d-dea66d5c0ab1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Browser: Chrome - Haven't had it happen when I use Firefox
 - Version: 106

**Comment by televandalist** [comment]
I noticed this happening as well, but now that I'm trying to reproduce it, it's not happening 😆

**Comment by snowpin** [comment]
![image](https://user-images.githubusercontent.com/6635720/202875366-064150b3-58b4-4935-aadb-7be23475139d.png)
Had this happen again while just simplying scrolling through the ticket manager.

**Comment by Jamiras** [comment]
It's easy to reproduce on the ticket manager. just whip your mouse around making sure to hit all the user links. The server starts responding with 429 Too Many Request errors fetching the tooltips, and the result is the red bar. I assume it's supposed to show the "Too Many Requests" error.

**Comment by Jamiras** [comment]
Based on that logic, I was also able to reproduce on the game page. Just whip the mouse over the recent players and user comments, making sure to hit all the user links.

**Comment by televandalist** [comment]
![2manyrequest4u](https://user-images.githubusercontent.com/45054151/205271077-f2d7cf89-ea77-4c5a-a0c9-8635704a9b0d.png)

Happened when scrolling down on this page. https://retroachievements.org/game/5948

Cursor was over the usernames in the mastery list when it popped up so....

**Comment by Jamiras** [comment]
The 429 error itself hasn't been fixed. That's the server trying to prevent a DDOS attack. The empty bar is what was fixed. See #1227 for tracking the 429 error.
