### ISSUE TITLE
Some Users cannot update their avatar

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAWeb#12]
Example:
FitzG, mike8581, ViLXDRYAD, Pedro Henrique, Alena, Theztret00, others.

**Comment by RetroAchievements** [comment]
This is a config issue, needs to be sorted on the backend I think. Thanks for posting names, that's ideal for testing

**Comment by luchaos** [comment]
i'm not able to update my avatar either - this should be fixed with https://github.com/RetroAchievements/RAWeb/commit/c106752a95a7f57aa6671a2fbf0b4f9a5d26a3ed going to prod.

**Comment by meleu** [comment]
I believe this issue is solved, am I wrong?

**Comment by meleu** [comment]
Checked the users mentioned on the OP and looks like this issue is solved.

Closing it, but feel free to reopen if I'm wrong.
