### ISSUE TITLE
submitlbentry results contain a wrong rank

### ISSUE THREAD

**Issue by CookiePLMonster** [RetroAchievements/RAWeb#1201]
**Describe the bug**
On submitting new leaderboard entries, RAWeb response code includes a field `Rank` that is supposed to contain the rank of the current leaderboard result for the player, whether it is a newly submitted one or a previously existing, better one. However, as seen on the below screenshots, it would seem that the reported rank is from an entry that comes directly after the submitted best time.

We've verified that this is not a display bug in DuckStation, the value returned from `rc_api_process_submit_lboard_entry_response` is used directly: https://github.com/stenzek/duckstation/blob/42768c31015c6e9e39e25741069ee9af3c1a68ed/src/frontend-common/achievements.cpp#L1771-L1773
Same with PCSX2: https://github.com/PCSX2/pcsx2/blob/8947c0d2e746f49d7015fd1c4e00eebf2ec480e1/pcsx2/Frontend/Achievements.cpp#L1792-L1793
This is not a rcheevos bug either, since the value from a returned JSON is placed in `rc_api_submit_lboard_entry_response_t.new_rank` directly: https://github.com/RetroAchievements/rcheevos/blob/ca8b4f4ac52c6e23fa1e0e5999a1d9da9939bb8e/src/rapi/rc_api_runtime.c#L492-L493

**To Reproduce**
1. Launch any game and submit any time to the leaderboard. For this the emulator used must be showing ranks on submitting times - DuckStation or PCSX2 will suffice.
2. Observe that the reported rank does not match the user's actual rank, instead it reports one rank "below" the user.

**Expected behavior**
Reported rank matches the actual one.

**Screenshots**
1. DuckStation: Actual rank is 35, the returned rank is 43:
https://cdn.discordapp.com/attachments/935144777152856086/1032203899966324767/unknown.png
https://cdn.discordapp.com/attachments/935144777152856086/1032203900348018729/unknown.png

2. DuckStation: Actual rank is 1, the returned rank is 2:
https://media.discordapp.net/attachments/661694346336272394/1032124870902943786/duckstation-qt-x64-ReleaseLTCG_FHq4rxWJDn.png
https://media.discordapp.net/attachments/661694346336272394/1032124871259471962/duckstation-qt-x64-ReleaseLTCG_UcFTsZDfbz.png

3. PCSX2: Actual rank is 13, the returned rank is 15:
https://cdn.discordapp.com/attachments/757516477887676426/1032210520763281438/pcsx2-qtx64-avx2_c32hFfr5gp.png
https://cdn.discordapp.com/attachments/757516477887676426/1032210521249824808/pcsx2-qtx64-avx2_Ssodmws3xn.png

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by Jamiras** [comment]
Thank you for the detailed analysis. The problem is that the rank calculation for lower-is-better leaderboards was not accounting for shared ranks.
