### ISSUE TITLE
Too Many Requests error when switching pages

### ISSUE THREAD

**Issue by miccmike** [RetroAchievements/RAWeb#1227]
**Describe the bug**
When switching pages quickly, such as jumping around different hubs, shows a Too Many Requests error red bar at the top.
![Screenshot_19](https://user-images.githubusercontent.com/112952233/201517313-b49d5cde-c0e9-44bd-862e-e22a7b65fdce.png)

**To Reproduce**

just switch pages quickly in RA.

**Comment by Soulsderfuchs** [comment]
This is getting way more common and sometimes even failing to diplay this red bar and straight up bring an error page 
![chrome_sxZx6zNGPJ](https://user-images.githubusercontent.com/59575350/202909153-91a50b84-9502-4c6f-a2e0-c96cf6d87a81.png)

**Comment by miccmike** [comment]
ive also noticed the red bar will just pop up randomly for no reason on a page. other then being a mild visual annoyance, it doesn nothing

**Comment by miccmike** [comment]
missclick

**Comment by luchaos** [comment]
Increased rate limiting for site and connect api
