### ISSUE TITLE
Games with 5 or less achievements reward a badge

### ISSUE THREAD

**Issue by Blazekickn** [RetroAchievements/RAWeb#1249]
There is no longer a requirement for a game to have 6 or more achievements in order to reward a badge. I mastered Bugs Bunny Birthday Bash Prototype which only has one achievement and obtained the site award. Is this intended behavior?

![image](https://user-images.githubusercontent.com/38176599/205214371-092d2615-2ba2-4495-afc5-b221f3867684.png)
![image](https://user-images.githubusercontent.com/38176599/205214377-20eb3e34-2f5c-4aa2-8e44-c4b83c5eda08.png)

**Comment by Jamiras** [comment]
Nope. Bug introduced by #1196.
