### ISSUE TITLE
All user profiles show current user's friends

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RAWeb#127]
As a user, when I view someone's profile, I expect to see their friends, not mine.

The "Friends Leaderboard" always shows the current user's friends. It should either show the friends of the user being viewed, or not be present when viewing a profile other than the current user's.

**Comment by Ben-Ghazi** [comment]
Same, what reason is there for needing to see other people's friend list?

**Comment by Jamiras** [comment]
I'm just indicating that it's misleading as-is. It should either be corrected or removed.
