### ISSUE TITLE
Profile Page "Total Masteries" does not include "hidden games"

### ISSUE THREAD

**Issue by Xeinok-Pals** [RetroAchievements/RAWeb#1288]
**Describe the bug**
On any Profile Page the "Total Masteries" does not include "hidden games" that players hide the badges of via a -1 on https://retroachievements.org/reorderSiteAwards.php

**To Reproduce**
1. Hide any 100% badge via https://retroachievements.org/reorderSiteAwards.php
2. Check your profile page to see that your true count of 100%s is lower than it should be.

**Expected behavior**
"Total Masteries" count should include all hidden games (it makes sense that it should not count relocked games, but hidden games should count).

**Comment by Tsearo** [comment]
#1271 by @EmoonX should fix this, it has been merged but not deployed yet I believe

**Comment by Xeinok-Pals** [comment]
Nice, thanks - my bad for not seeing that. This can be closed then, looks totally covered by the other 👍🏼

**Comment by EmoonX** [comment]
Good to know I caught up with doing it earlier 😁
