### ISSUE TITLE
Treat banned accounts as non-existing

### ISSUE THREAD

**Issue by luchaos** [RetroAchievements/RAWeb#1289]

**Comment by Alexdatadestroyer** [comment]
Hmm, may I ask: Is this was already been solved?

When you access a banned account on RAWeb, you face a page with "Not Found" underlined message followed by a random reaction of RA Mascot. Something like a HTTP 404 Error...

**Comment by luchaos** [comment]
@Alexdatadestroyer you're right, thanks! seems to be fully resolved now, I missed closing this.
