### ISSUE TITLE
Game Page Sorting does not work

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAWeb#13]
These: 
![image](https://user-images.githubusercontent.com/32706333/36181225-34532932-10e1-11e8-85de-ba975c2ad0b8.png)

None of them do anything

**Comment by SyrianBallaS** [comment]
I can confirm it doesn't work, I'll take a look at it.

**Comment by SyrianBallaS** [comment]
I don't think we work on this until issue 84 is resolved. If any of you have an alternative I'm all ears.
