### ISSUE TITLE
Inconsistent tooltip tag rendering

### ISSUE THREAD

**Issue by EmoonX** [RetroAchievements/RAWeb#1317]
Tags can, at times, appear unrendered in tooltips.

**To Reproduce**
1. Open homepage at [https://retroachievements.org](https://retroachievements.org)
2. Press `Ctrl+F5` (or `Cmd+F5`) to hard-reload page
3. Hover over game title with tag in "New Sets/Revisions"
4. Title is displayed unrendered in tooltip
5. Reload page normally
6. Tag should be displayed correctly on next hover

**Screenshots**

![broken](https://user-images.githubusercontent.com/22218549/212479569-0a30cc7b-85a1-45bb-b6c6-355b3607d616.png)
![correct](https://user-images.githubusercontent.com/22218549/212479566-57361c4b-1168-4eea-8381-b0a7aef1538b.png)

**Desktop:**
 - OS: Manjaro Linux
 - Browser: Chrome 104, Firefox 108

**Comment by oddgoo** [comment]
Could not replicate on Chrome 110 or Firefox 111 (Windows 11)
Maybe it was a caching issue/leftover?

**Comment by EmoonX** [comment]
Okay, reopening issue as I just stumbled upon it again. :man_facepalming:

**Comment by wescopeland** [comment]
I am having a lot of trouble reproducing this - I am wondering if this related to server-side caching and it was just a matter of time until the cache was nudged for all these tooltips.

**Comment by EmoonX** [comment]
Closing this as an update had removed tooltips for the `New Sets/Revisions` section, which makes the issue irrelevant now.
