### ISSUE TITLE
The "Games" count used on the home page is inaccurate

### ISSUE THREAD

**Issue by wescopeland** [RetroAchievements/RAWeb#1356]
**Describe the bug**
The stats drawn from `StaticData` on the home page are not accurate.

> @televandalist It's worth noting that the numbers are actually kinda misleading because it includes stuff in unofficial and events. It says 6410 games at this moment, but we're still about 55-60 sets away from reaching 6000.

> @luchaos None of those numbers are accurate iirc. Emphasizing them might be misleading in general.

**To Reproduce**
1. Go to the home page.
2. Look at the statistics section on the right.

**Expected behavior**
The statistics numbers for games, achievements, etc should be precise and accurate.

**Screenshot**
![218236412-817d66ab-8f11-4cf5-8e07-31e586da2f49](https://user-images.githubusercontent.com/3984985/218277460-f6f6ebfc-b221-479b-aa6f-e0971632aa36.png)

**Additional context**
This emerged from this PR https://github.com/RetroAchievements/RAWeb/pull/1354. I have been using the site for years and did not realize these numbers were not 100% precise. I assume it is not widely known.

**Comment by EmoonX** [comment]
Not directly related to accuracy, but: the game number takes subsets into account, right? Is this worth of being disclosed in the statistics grid? Or maybe changing the way data is fetched so it counts only base games?

**Comment by wescopeland** [comment]
> Not directly related to accuracy, but: game counter takes subsets into account, right? Is this worth of being disclosed in the statistics grid? Or maybe changing the way data is fetched so it counts only base games?

Disclaimer: I have not studied the `StaticData` stuff too closely yet.

My opinion is the "Games" stat should not include subsets or bonus sets. Based on the delta between games & sets, it may be worth having a "Sets" stat in the section.

**Comment by wescopeland** [comment]
@Jamiras wrote [here](https://github.com/RetroAchievements/RAWeb/issues/1400#issuecomment-1451135938):

>... it's just counting games with achievements. The 6535 is all games with achievements. The 6145 is games with published achievements. That means there are 390 games with achievements only in Unofficial.

**Comment by MSGoodman** [comment]
I see a `// TODO replace StaticData table`. What were we thinking of replacing this with? 

It seems this is basically memoized data, right? I don't know the origin of this thing so this is coming from a place of ignorance, but is a query for these numbers that expensive? I don't know the whole database structure yet but it mostly looks like a bunch of `count`s and a `max` in a few places? 

I'm just thinking about how often this table is updated: whenever a game is added or mastered or beaten, whenever an achievement is created or unlocked, and whenever a new user signs up. So around 52 million times thus far? I don't know how many times users have hit the front page in comparison, or how that would scale, so I can't make an informed decision here.

I'd love to grab this one, just unsure which direction we should move in!

**Comment by wescopeland** [comment]
> What were we thinking of replacing this with?

@luchaos may have a better answer. My gut feeling says anything too expensive here could probably just live in Redis.

**Comment by wescopeland** [comment]
It may make sense to handle this as part of multiset.
