### ISSUE TITLE
[Bug Report] Developer site awards stopped updating

### ISSUE THREAD

**Issue by Ben-Ghazi** [RetroAchievements/RAWeb#1360]
When my achievements were re-authored to my new account my two developer badges stopped updating. For awhile I didn't think much of it but after seeing an account with comparable points awarded being a bit further along it made me realize that I had passed the point threshold when my achievements were re-authored and my badges weren't updating to reflect it.

Here's the badge my account has:
![1](https://user-images.githubusercontent.com/39404689/218299555-cc9a5661-bc73-4380-887c-5e75be5af78c.png)

My account is sitting at 132,000, here's the badge of someone sitting at 120,000:
![2](https://user-images.githubusercontent.com/39404689/218299681-d6cb5041-4456-4378-8def-8ca15ac8e079.png)

**Comment by Jamiras** [comment]
When you cross the next threshold (250,000), it'll award that badge and you'll be up to date again.

Since that's so far away, I've run the command to manually regenerate your badges.
