### ISSUE TITLE
Earned points don't always seem to match total calculated by site

### ISSUE THREAD

**Issue by relm** [RetroAchievements/RAWeb#1364]
**Describe the bug**
I'm noticing that the points total on profile pages doesn't actually match up with the sum of all earned points from the user's played games.

**To Reproduce**
Take this profile as an example - https://retroachievements.org/user/dagger?g=15

It's showing 2881 points in the profile summary the top. Yet, if you if add the points total of each game individually it comes out 2,876

This doesn't always happen. Sometimes the points match up exactly as expected.

I run Exophase and I've been trying to reduce the amount of API requests we're sending to RA. This is problematic as if the points don't match up, we do a full profile scan to make sure nothing was missed. So since the points don't match it's been scanning the top users a lot more frequently than it would otherwise.

**Comment by Jamiras** [comment]
This behavior is partially described in #296.

Basically, an achievement can be demoted or have it's points changed, and that doesn't affect the cumulative score managed for each user who has earned the achievement. These are concessions made to keep the API responsive.

Whenever a player manually resets an achievement, or approximately once every two months when the cron job reaches the user, their score is recalculated to re-sync it.

**Comment by kmpers** [comment]
[This](https://retroachievements.org/achievement/17457) achievement was moved to the bonus set along with all the unlocks, so dagger has 5 points from the set despite never playing it. Completion Progress section of the profile includes this set.

**Comment by luchaos** [comment]
Resolved with v5?

**Comment by wescopeland** [comment]
Should indeed be resolved as of V5. @relm Please feel free to re-open this issue if it re-emerges.
