### ISSUE TITLE
Inbox/Outbox messages list bug

### ISSUE THREAD

**Issue by Alexdatadestroyer** [RetroAchievements/RAWeb#1373]
I have been noticing this bug months ago, but only tried to report just now when found a solution after looking Inbox.php code...

This kind of bug only happens if you have all your messages listed whereas Total Messages is divisible by 10 (Example: 20, 50, 100, 150, etc.). If you have 24 messages, then, next page will list the last 4 ones correctly.

**Try for yourself:**
1. Send a lot of messages to yourself at the way that you fill any page with 10 messages
2. Click "Next 10 >" link
3. You will see a blank list there.

**Screenshots:**

Last page with last message shown (Page 2):
![](https://i.imgur.com/5x5oFPN.png)

Next page leading to nowhere... (Page 3):
![](https://i.imgur.com/3FFjsKs.png)

**Computer Information:**
 - OS: Windows 10 Pro 20H2
 - Browser: Microsoft Edge

**Solution:**
After looking on [Inbox.php](https://github.com/RetroAchievements/RAWeb/blob/master/public/inbox.php) file here on RAWeb repository, it seems that Line 186 is the culprit as it makes to show that link "Next 10 >" everytime when exactly 10 messages are loaded. This also applies to Outbox case:

`if ($totalMsgs == $maxCount)`

Since $maxCount is always 10 as expressed on Line 5, $totalMsgs will only be 10 if all 10 messages are loaded. However, it doesn't block the case if all messages ($totalMessageCount) have already been loaded. Looking on next lines, you can see that $offset variable is being incremented by 10 as new offset to next page on Line 187 inside Echo command. So, why not checking if this sum is less than $totalMessageCount before replicating that "Next 10 >" link?

What I mean is something like this:

`if (($totalMsgs == $maxCount) && (($offset + $maxCount) < $totalMessageCount))`

For example above, I am on second page, so $offset value is 10 since it will list from IDs 10 to 19 on this page. On next page is expected to list from IDs 20 to 29 with $offset being 20. However ($offset + $maxCount) is 20 on second page which is equal to $totalMessageCount. So, clicking "Next 10 >" will lead to nowhere...

On another hand, if you have 52 messages to display in total ($totalMessageCount == 52), then, you will have 6 pages to display whereas Page 5 will display 10 messages with $offset == 40 and ($offset + $maxCount == 50). Next page will exhibit the last 2 messages: one message with ID 50 and other with ID 51. Since ($offset + $maxCount) will be 60, only "< Previous 10" will be displayed.

Hope that it helps!

**Disclaimer:**
This is my first report here on Github. Sorry if I posted this on wrong place.

**Comment by EmoonX** [comment]
Thanks for the comprehensive report and insights. Should be solved by #1374.
