### ISSUE TITLE
Re-promotion of a set adds extra unlocks to user totals

### ISSUE THREAD

**Issue by redwizard42** [RetroAchievements/RAWeb#1398]
A Jr Dev had me demote his entire set to fix a set-wide bug. This is his only set. When I re-promoted the set, his total unlocks (achievements won by others) *doubled*, suggesting that promoting the set added the unlock totals erroneously whereas demoting it did not subtract any.

**Comment by wescopeland** [comment]
Possibly related to https://github.com/RetroAchievements/RAWeb/issues/1383

**Comment by luchaos** [comment]
Resolved with v5?

**Comment by Jamiras** [comment]
Should be handled by #1947 (v5.1), which includes [tests](https://github.com/Jamiras/RAWeb/blob/07e84560782f545455c0537663dd0b11dc5c0d72/tests/Feature/Connect/UploadAchievementTest.php#L179-L270) for contribution counts changing when promoting/demoting achievements.
