### ISSUE TITLE
Leaderboard Display Order is does not change order on game page

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAWeb#14]
While the leaderboard does display on the Leaderboard List / Leaderboard Management, for a game, the order does not change on the game page.

It appears that the order displayed on game page is by leaderboard ID number.

**Comment by meleu** [comment]
not for myself:
it seems to be pretty trivial to solve by adding `DisplayOrder` [in this line of code of `lib/database/lbs.php`](https://github.com/RetroAchievements/RAWeb/blob/f8c250c652438918b80670c8e7e8af3ff02c6d13/lib/database/lbs.php#L353). Will test it when I have a chance
