### ISSUE TITLE
Negative Softcore Points

### ISSUE THREAD

**Issue by Tsearo** [RetroAchievements/RAWeb#1413]
Users seem to be able to have negative softcore points after resetting progress in softcore earns. In this example the user earned an achievement in softcore, reset it and then earned it in hardcore. Attempting to recalculate score manually did not correct the issue.
![image](https://user-images.githubusercontent.com/4047771/222934423-68de2bb6-fdf3-4f16-aece-c4c542fd65b7.png)
![image](https://user-images.githubusercontent.com/4047771/222934418-5971766c-0dfa-42c0-9ff7-c2f24cbc2c79.png)

**Comment by wescopeland** [comment]
Possibly resolved by https://github.com/RetroAchievements/RAWeb/pull/1688.

**Comment by wescopeland** [comment]
Closing as I do believe this is now resolved.
