### ISSUE TITLE
[Bug] My Settings Page

### ISSUE THREAD

**Issue by StingX2** [RetroAchievements/RAWeb#1421]
https://retroachievements.org/controlpanel.php
Anytime I go to the My Settings page the entire page freezes until I get a non responsive update. My thought is because of the amount of games I have played it wants to load all that as the reset options are there. Unfortunately even if I load it and wait it still crashes my browser tab.

The only solution is to play this cat and mouse game with it closing the tab and reopening and after about 10 tries it will briefly let me hit a button (whether thats change my motto or recalc my score). Even after a succesful push of the button it is a guess if it works or not as the tab then freezes forever.

**Desktop (please complete the following information):**
 - Windows 11
 - Chrome

**Comment by Blazekickn** [comment]
If you wait long enough it does load, but its not ideal

**Comment by Jamiras** [comment]
It's definitely the game list. It took about 1 second to retrieve the data, but the web page was unresponsive for over a minute (There are about 1200 games in your list).

I suspect it's something in the way the list is being populated from the response. Maybe something similar to the changes made in #1391 could help.

**Comment by StingX2** [comment]
> It's definitely the game list. It took about 1 second to retrieve the data, but the web page was unresponsive for over a minute (There are about 1200 games in your list).
> 
> I suspect it's something in the way the list is being populated from the response. Maybe something similar to the changes made in #1391 could help.

The rescore project had me load many many games sadly.

**Comment by wescopeland** [comment]
@StingX2 Good news! I have found a nearly 100x performance optimization for this and will be opening a PR to remediate the issue later this evening.

**Comment by StingX2** [comment]
> @StingX2 Good news! I have found a nearly 100x performance optimization for this and will be opening a PR to remediate the issue later this evening.

my hero :D
