### ISSUE TITLE
Claims on Developer Profile wrap wrong on long Game Titles

### ISSUE THREAD

**Issue by SporyTike** [RetroAchievements/RAWeb#1430]
**Describe the bug**
It seems that if the title of a game entry is very long the wrapping on the User Profile behaves a bit weird. As seen in the screenshot the site make a full new line just for the `*` which is weird considering that it normally should just be behind the console name.

**To Reproduce**
1. Claim a game with a very long name
2. Visit the user profile
3. See error

**Expected behavior**
The `*` should be directly behind the console name as seen on the last claim for the Game Boy Color game.

**Screenshots**
![image](https://user-images.githubusercontent.com/45672834/224579177-c986cc8e-84d0-4108-a2f7-6ceea9eac5be.png)

**Desktop (please complete the following information):**
 - Browser: Opera GX (95.0.4635.74)

**Comment by wescopeland** [comment]
I believe this issue shares its root cause with white points wrapping on a game page's achievements list.
