### ISSUE TITLE
Deprecate app API request files

### ISSUE THREAD

**Issue by luchaos** [RetroAchievements/RAWeb#144]
As suggested by @GameDragon2k - these files should be deprecated to ensure remaining outdated clients are updated.

```
requestallgametitles.php
requestgameid.php
requestlogin.php
requestpatch.php
requestsubmitcodenote.php
requestunlocks.php
requestuploadachievement.php
requestuploadbadge.php
requestvote.php
```

They will respond with:
`FAILED: Deprecated. Use x.php instead. POST {a: 'a descriptive example string for this post parameter', b: 'another descriptive string', c: 'you get the idea'}`

It will be made sure that those files are not used by the site itself anymore.

**Comment by meleu** [comment]
I'm currently working on #160 and noticed that `public/ticketmanager.php` is the only client for `public/requestupdateticket.php`.

IMHO that stuff happening on `requestupdateticket.php` can be handled in the `ticketmanager.php` and/or `lib/database/tickets.php`. I'll submit a PR soon with this approach in mind.

That being said, I think that `requestupdateticket.php` can be in that list of deprecated files too.

**Comment by luchaos** [comment]
as for the `request*.php` the rule of thumb is: 
if it uses `RA_ReadCookieCredentials` for authentication it can be ignored as it will be completely replaced by controller actions in v2 and no legacy support.
if the file authenticates through `login_appWithToken` it will be refactored into a v1 api implementation to provide backwards compatibility.
i wouldn't mind the superfluous files too much atm as they've all been already removed from v2.
