### ISSUE TITLE
[Bug] Can't see the lowest part of the list of consoles in the Games tab

### ISSUE THREAD

**Issue by Maximdraco** [RetroAchievements/RAWeb#1470]
Is exactly what the title says, either is for the size of the list, or my monitor screen, I can't see the lowest part of the Console list, so for example I can't see Watara Supervision or the Wonder Swan unless I zoom out to 80%

**Comment by wescopeland** [comment]
What screen resolution are you using?

**Comment by Maximdraco** [comment]
1366 x 768

**Comment by wescopeland** [comment]
This is a video of me using the menu when the res is 1366 x 700, so slightly more constrained than your computer's screen resolution.

Notice the menu is indeed initially clipped, but I can scroll down just a bit to see the rest. Does this workaround also work for you?

I do think we should perhaps give this menu some more thought soon. Especially for mobile, it is a bit overwhelming.

https://user-images.githubusercontent.com/3984985/232227499-977a20ff-afb1-4da9-8a5c-75df7850d921.mp4

**Comment by Maximdraco** [comment]
It kinda seems ti be more the viewport (1325 × 627) more than the screen itselfs, having the web browser in window mode (no full screen) it works fine in small viewports.

It seem to be in the range beetween 879 × 608 and 1325 × 627 when I have the problems, if the web browser isn't in full screen, I can only see until Vectrex, I'm not sure if is a problem in the website, a problem of my web browser (Opera GX) or my PC (I use Windows 10)

**Comment by luchaos** [comment]
Works fine on 1325 × 627 now after making the dropdown four columns wide.
