### ISSUE TITLE
"Hide badge" functionality not working when trying to hide more than 1000 badges

### ISSUE THREAD

**Issue by guineu1** [RetroAchievements/RAWeb#1472]
Tried to hide some recently earned badges, first time using the new Badge reorder functionality. The badges didn't hide and instead got reordered randomly. For the time being I decided to hide all badges and rebuild the order later on when I had more time. Then I noticed that no matter how many times I tried to hide them, there were always 91 badges showing. The site says I have 1081 hardcore + 11 softcore badges, so I'm gonna guess the problem appears when trying to hide more than 1000 badges.

**Comment by wescopeland** [comment]
I will investigate this soon. @Jamiras my initial thoughts are this could be related to the variable size issues we were seeing with a POST, though I will confirm this when I investigate.

**Comment by wescopeland** [comment]
I am having a lot of trouble reproducing this on my local machine's RAWeb setup. I signed into your account (granted, it's missing several of your latest badges, but still well over 1000). I then hid the last row, saved, and everything appears to be fine. Repro video attached.

@guineu1 Do these reproduction steps look correct to you? Also, when saving do you happen to see any errors? We may need to use process of elimination to determine what the cause of this issue is.

I am wondering if this could possibly be related to server config somehow. If these are indeed the correct repro steps, something must be different between our local machines and the production server.

https://user-images.githubusercontent.com/3984985/232226899-ecd928f1-d5e6-4a34-8ef9-7d86ef964b5c.mp4

**Comment by guineu1** [comment]
The problem for me started when I tried to have more than 1000 badges hidden (I don't think that's the case in your video) but that was just my guess maybe the problem is caused by something different.

Here I recorded a video, sorry seems like the mouse wasn't captured.
-Showing the last badge (Baby Wolfenstein)
-Ticking the "hidden" slot for that badge.
-Saving without errors shown.
-F5 and the badge is still there.

https://user-images.githubusercontent.com/58072326/232231149-c3ab2c14-8076-40d4-a5ba-a93cdd3da79d.mp4


Not shown in the video, if I go again to the bottom, the badge is still ticked as "hidden" while also having the buttons to move it around:

![Screenshot 2023-04-15 at 16-46-44 Reorder Site Awards](https://user-images.githubusercontent.com/58072326/232231753-ee5c9187-66bc-466e-928a-abe3d7943a58.png)

**Comment by guineu1** [comment]
Tried to do the same using a different browser, in case the problem was on my side, and had the same results (Chrome and Firefox).

**Comment by wescopeland** [comment]
Thank you for providing this additional repro footage and context.

With this context, it is safe to rule out that this is a browser issue. Something must be happening server-side or in the payload that is being sent to the server when the Save button is clicked.

In my attempt to repro again, I wrote some code in the browser devtools to verify that over 1000 checkboxes were checked. Unfortunately I am still not seeing the same thing you are seeing 🤔

https://user-images.githubusercontent.com/3984985/232235556-4abc97b5-4a70-4243-805f-9302683bc6e8.mp4

<br><br>

Just to further narrow down what a potential culprit might be, I would be interested the know the exact count of Hidden checkboxes you have checked on the page. It is possible the bug kicks in when _well over_ 1,000 checkboxes are checked. I would like to try to repro with as much precision to what you're seeing as I can. To run the code I used in the video above, open the browser Developer Tools in Google Chrome:

<img width="752" alt="Screenshot 2023-04-15 at 11 57 55 AM" src="https://user-images.githubusercontent.com/3984985/232235609-e61d69ea-4041-495c-987b-2033ff344c1c.png">

Then click on the "Console" tab:
<img width="314" alt="Screenshot 2023-04-15 at 11 58 42 AM" src="https://user-images.githubusercontent.com/3984985/232235706-6c2c5061-7c3d-4da4-9347-878ebe4eb62e.png">

Then paste in the following and press enter:

```js
var checkboxes = document.querySelectorAll('input[type="checkbox"]');
var checkedCount = 0;

for (var i = 0; i < checkboxes.length; i++) {
  if (checkboxes[i].checked) {
    checkedCount++;
  }
}

console.log("Number of checked checkboxes: " + checkedCount);
```

If this seems too overwhelming, no worries. We will keep digging.

**Comment by guineu1** [comment]
Here's the video:

- First I run that code, shows 996.
- The Wolfenstein badge is visible in the sidebar.
- At the bottom of the list I check the Wolfenstein badge to hide it.
- Save
- Badge is still visible in the sidebar.
- Badge not at bottom of the list... but reappears at bottom upon refreshing.
- Finally I run the code again, shows the same (996).

https://user-images.githubusercontent.com/58072326/232237791-f9ab5621-5501-453a-9502-71c2e8c1f988.mp4

**Comment by wescopeland** [comment]
@guineu1 We are still trying to reproduce this in our local environments, to limited success. You have done such a great job organizing your site awards. I apologize that you've been hit with this inconvenience. Rest assured this will not fall on the back burner and we will figure something out.

**Comment by guineu1** [comment]
Don't worry about it, specially if no one else has experienced anything similar.

Actually I'm more worried the problem could be something on my side and I'm wasting your time. But I just tried hiding badges from my phone and still experienced the same behavior as from the PC: saves without error notifications, but badges don't hide. Let me know if you want me to test anything else.

**Comment by wescopeland** [comment]
I would still like to get this figured out ... even if it's only impacting you today, it will impact more people in the future.

Leaving this here for future context/notes. I have been working with another developer attempting to reproduce this. With my latest attempt, I tried from a completely pristine database with the latest snapshot (still ~4 weeks old). There was a suspicion maybe I'd be able to reproduce this on the first try, but on no subsequent tries. However, I am still not able to repro this even under those circumstances.

I am leaning more heavily into this being some kind of configuration/settings issue on the production server.

@guineu1 I have another idea for a way to get clues to help resolve this. You may be able to go to https://stage.retroachievements.org and sign in to your account. This is our testing environment before we push out new site releases. See if you can also reproduce the bug there. Whatever the results are will help give us more context on what could be happening.

https://user-images.githubusercontent.com/3984985/232332873-734e186a-dda6-42bd-b980-59ab3743dc21.mp4

**Comment by guineu1** [comment]
Tried there and had the same results. Some of the badges weren't showing the thumbnail, as seen in the image below, but I guess that's normal.

Here's what I did exactly; logged in, took a screenshot (left side), went to "Reorder Site Awards", ticked the checkbox for the last badge shown ("Road Trip" for Arduboy), and saved the changes. Then refreshed the profile and the Road Trip badge was still shown at the end, same last position. Took another screenshot (right side) to show how the badges got reordered on their own. Notice how basically an entire block of badges got moved to the top without really changing the order of that block, maybe that could help.

![Screenshot 2023-04-16 at 21-10-55 guineu](https://user-images.githubusercontent.com/58072326/232336907-f6723ef3-f93a-46e3-bbbf-b7e2a9cc22a0.png)

**Comment by wescopeland** [comment]
Thank you for reproducing this on stage. This is very helpful.

This all but confirms there is some kind of server issue causing the problem, as my DB snapshot is only a few days older than the stage DB snapshot. That rules out a code issue and supports that this is configuration related on the server itself.

**Comment by wescopeland** [comment]
I am optimistic that https://github.com/RetroAchievements/RAWeb/pull/1483 will resolve this issue.
