### ISSUE TITLE
Double Space in Game-Tag referencing Subsets

### ISSUE THREAD

**Issue by SporyTike** [RetroAchievements/RAWeb#1509]
As the title mentions the [game=] tag for forums has a double space when referencing to a subset. It's between the game title and the console name, pretty sure it's there since normally the subset tag is between them which gets put at the end since recently.

To reproduce you can just create a forum post using that tag or check out an existing post like here where the tag references a subset. A post like this can be found [here](https://retroachievements.org/viewtopic.php?t=18082&c=132017#132017).

**Screenshot showing that there are two spaces in the tag between the game name and console name**
![image](https://user-images.githubusercontent.com/45672834/233862402-fc4d2631-fc9d-48b0-b717-f6e08c9021fb.png)

There should be some logic for such cases that forces a single space instead of multiple spaces in a row.

**Comment by amine4567** [comment]
The problem seems to come from putting a [game=] tag inside a [code=] tag, if you try a [game=] tag alone, you won't get the double space as you can see from my reply to the linked post (sorry for polluting your post, I will remove my comment later on).

This still needs to be fixed.

**Comment by wescopeland** [comment]
This will be resolved by https://github.com/RetroAchievements/RAWeb/pull/1544.
