### ISSUE TITLE
Profile shows 0 last played games despite having recent activity

### ISSUE THREAD

**Issue by relm** [RetroAchievements/RAWeb#1515]
Profile in question: https://retroachievements.org/user/lotrdaniel

I noticed this profile is showing 0 last played games despite having recent activity. Also verified through the API, the endpoint `API_GetUserRecentlyPlayedGames` returns a empty response. Does anyone know what could be going on here?

**Comment by Jamiras** [comment]
It looks like whatever emulator he is using is not issuing "start session" API calls. I don't know if there's any easy way to determine which emulator he is using.

**Comment by RALordAndrew** [comment]
It's an emulator called TNavigator Ultimate.
https://retroachievements.org/viewtopic.php?t=21347&c=165181#165181

**Comment by Jamiras** [comment]
I found this discussion around TNavigator in an admin channel from 2021:

> tnavigator is a paid, not-open-source, clone of an open-source project with additional features like achievements. I believe we came to the conclusion that it's not sending any user agent.
> but yes, neither appears to be making the startsession call

It's the startsession call that updates the recently played games list.

Not sending a user agent could potentially result in us not allowing hardcore unlocks if we ever start restricting hardcore unlocks to known, trusted, and reasonably up-to-date emulators.

**Comment by wescopeland** [comment]
Closing as this is related to an emulator not making a startsession call or sending a user agent, and not something that can be fixed from RAWeb.
