### ISSUE TITLE
Global Ranking Achievement Count includes Unofficial and Event Achievements

### ISSUE THREAD

**Issue by Tsearo** [RetroAchievements/RAWeb#1522]
Easy example showcasing both issues where the user has 152 achievements but because of doing the stimulus package event worth 1000 achievements even though it was demoted to unofficial and is an event they count towards the total in the ranking
![image](https://user-images.githubusercontent.com/4047771/234739449-365d2d7b-902d-40d7-aeec-56dfc20dbfd9.png)
![image](https://user-images.githubusercontent.com/4047771/234739541-b3b5d7cd-4909-4527-a3ff-8823eb4e59df.png)

A fix to this would be to add checks for only core achievements and exclude the event ID like so but doing so tripled the time to run the query so either a more optimized query is needed or we will need to wait for denormalization to correct this issue

Current query for achievement count
```
(SELECT COALESCE(SUM(CASE WHEN HardcoreMode = " . UnlockMode::Hardcore . " THEN 1 ELSE 0 END), 0) 
                        FROM Awarded AS aw 
                        WHERE aw.User = ua.User) AS AchievementCount,
```

Accurate query (~3x slower)
```
(SELECT COALESCE(SUM(CASE WHEN HardcoreMode = " . UnlockMode::Hardcore . " THEN 1 ELSE 0 END), 0) 
                        FROM Awarded AS aw 
                        LEFT JOIN Achievements ach ON ach.ID = aw.AchievementID 
                        LEFT JOIN GameData AS gd ON gd.ID = ach.GameID
                        WHERE aw.User = ua.User
                        AND ach.Flags = 3
                        AND gd.ConsoleID <> 101) AS AchievementCount,
```

**Comment by wescopeland** [comment]
Resolved by https://github.com/RetroAchievements/RAWeb/pull/1617.
