### ISSUE TITLE
Technical Trigger Information Standard for Achievements

### ISSUE THREAD

**Issue by magusLOGS** [RetroAchievements/RAWeb#155]
How about adding a Technical Trigger Infomation Standard for Achievements (TTIS) as this important information could help improving, fixing and earning Achievements drastically. It would work additional to the Description but more from a technical perspective and would include rules of how to get the Achievement.

I post this in RAWeb and not RAIntegration because its more a WebSite thing than a RAIntegration function. However, i wrote this around the RAIntegration for a better unterstanding.

**1. Dynamic (On-The-Fly) via Toolkit**
By marking selected IDs (Conditions) and add information in form of Tags to them.
- Displaying current information live in the Emulators, for example if a ID has a Hit or not

![Toolkit-TTIS](https://i.imgur.com/f9m6OH3.png)
In this Achievement you have to finish Stage 2 right after you finished Stage 1, no Game Over or Cheats are allowed.
> **Note:** ID4 is not active as its the value for Demo Mode which should be blocked/reseted by default in every Game/Achievement.

![RetroArch-TTIS](https://i.imgur.com/trHfQ5q.png)
Example of rules for the Achivement displayed in the Emulators as additional information:
```diff
+ Stage 1*, Stage 2, Stage End
- Game Over, Cheats, Cheats
```
> **Note:** The * in Stage 1 could be automatically updated by reading the Hit if its active (1+) or not (0) so the player sees the status live in the Emulator, adding such active Tags via Web wouldn't be possible unless the Achievement Viewer on the Site gets a overhaul (being able to change Achievement Code via Web).

**2. Manually via Web**
By manually adding this information as Tags to each Achievement.
- No live status in Emulators
- Add and remove TTIS Tags to Achievements via Web

The TTIS information could also be displayed on each Achievement Page incl. expanded Description as requested by Salsa. https://github.com/RetroAchievements/RAWeb/issues/107

This would benefit:

- **Gamers** (Hardcore)
Better rules understanding of what to do to get the Achievement as a simple Description is sometimes not clear enough and would prevent Description being spammed with all the rules when it can be done separately.
Some Gamers don't know what to do to get the Achiement being triggered and the Ticket Reports with lack or improper information are proving it because those who know what to do and don't get the Achievement are results of a broken. Having such information would decrease the False Reports as Gamers will have more information in hand what to do beside the Achievement Description.
This would increase the accuracy of Achievement triggers for every Game and cause less Ticket Reports.

- **Gamers** (Softcore)
Gamers who play in Softcore would benefit from it a lot as they will know when to create a Savestate for the retry. Having such information would make Softcore more accurate and appealing for Gamers. At the moment there is no such information available unless you open the Achievement Editor and watch the Hits. Achievements without Hits are not affected by creating Savestate at wrong time.

- **Developers**
This information would help understanding much faster how the Achivement works from a technical perspective without browsing through all the Adresses in Memory Viewer and reading the Notes used in the specific Achievement.

**Comment by kdecks** [comment]
Basically a way to add notes to requirements and on overlay feedback on the status of certain reqs.

**Comment by Jamiras** [comment]
I realize this is just a mock-up, but I think the Yes/No TTIS column seems redundant. Either the Tags will be blank or it won't.

Putting it in the emulators would probably confuse more people than it would help. You had to describe your in-game example for our benefit. Imagine an "Average Joe" seeing that for the first time: _Why do I care about "Stage 1" if i'm supposed to beat stage 2, and what's the little star thingy?_

Showing the extended information in the achievement details page makes sense. I would recommend labels over colors for two reasons: 1) clarity, 2) colorblindness.
```
Requirements: Stage 1, Stage 2, Stage End
Without: Game Over, Cheats, Cheats
```
You might even take it a step further:
```
From: Stage 1
To: Stage 2, Stage End
Without: Game Over, Cheats, Cheats
```

Regarding your last bullet point: It has been suggested that we have tooltips that show code notes in the achievement editor. I've formally created an issue for RAIntegration to address this: https://github.com/RetroAchievements/RAIntegration/issues/53

Providing feedback on when an achievement is active is a good idea. I tried to implement something that did that, but it's nearly impossible to do correctly without manually defining the behavior. See https://github.com/RetroAchievements/RAIntegration/issues/52

**Comment by meleu** [comment]
@magusLOGS do you agree to close this in favor of #400 ?

**Comment by magusLOGS** [comment]
Can be closed as it already exist in form of measuring.
