### ISSUE TITLE
<br> displayed when editing Code Notes on Site

### ISSUE THREAD

**Issue by SporyTike** [RetroAchievements/RAWeb#1563]
While editing code notes on site I found another bug by accident while doing a few misclicks on a code note that forces a next line. If you follow a specific process you make the code note editor show `<br>` instead of going into the next line and if someone edits that note and then saves it, it overwrites all the line breaks with `<br>`.

Code note opened on the site normally:
![image](https://user-images.githubusercontent.com/45672834/236672483-a54f7518-66e3-4440-a6d1-c8ce9e423126.png)

Code note opened after causing the bug:
![image](https://user-images.githubusercontent.com/45672834/236672515-c7dae68c-4acf-415a-b7e6-ee14d8f67107.png)

**To Reproduce**
1. Create a code note in the emulator that uses a line break
2. Go to the code notes of the same game on the site
3. Edit the code note and save
4. Click the Edit button again and then Cancel
5. Click the Edit button once again and the line breaks are messed (image 2)

It seems that any code note that suffered from the `<br>` will remain like even when reopening it in the code note editor. The only way to fix it is to reload the page.

**Comment by wescopeland** [comment]
Will be fixed by https://github.com/RetroAchievements/RAWeb/pull/1564
