### ISSUE TITLE
Game List game tooltip sometimes won't display console name

### ISSUE THREAD

**Issue by laytonloztew** [RetroAchievements/RAWeb#1583]
Go to a game list [https://retroachievements.org/gameList.php](https://retroachievements.org/gameList.php) and hover over a game's name or icon. Sometimes the console name won't be printed underneath the game name. If it does display, hovering over other games won't display their console name. Refreshing the page resets this, so the first game hovered may display the console name but others will not.

![ra_tooltipbug1](https://github.com/RetroAchievements/RAWeb/assets/12983268/a556ced4-5761-4e04-b073-33f42b58b036)
![ra_tooltipbug2](https://github.com/RetroAchievements/RAWeb/assets/12983268/3e0765fe-1e61-43ea-8c25-4e6236376781)

I first observed this on my dev game list [https://retroachievements.org/gameList.php?d=Layton](https://retroachievements.org/gameList.php?d=Layton) Seems to be any page using gameList.php, other pages don't exhibit this behavior. 

Windows 11
Chrome 113.0.5672.93 (Official Build) (64-bit)

**Comment by wescopeland** [comment]
This seems to have been introduced by https://github.com/RetroAchievements/RAWeb/pull/1156. I am investigating if it's possible to keep the console name stripped but still pass it to the tooltip on the page.
