### ISSUE TITLE
Achievement condition metadata

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RAWeb#159]
As a developer, I want to annotate my achievements in a way that doesn't break RetroArch or cause the definition to become unnecessarily long.

A simple use case would be https://github.com/RetroAchievements/RAIntegration/issues/4. If the "Progress" flag were embedded in the achievement string, it would break RetroArch compatibility until RetroArch supports the flag. As the flag has no impact to the behavior of the achievement, it should be stored separately. This logic could also be applied to https://github.com/RetroAchievements/RAIntegration/issues/52.

A more complex use case is described here: https://github.com/RetroAchievements/RAWeb/issues/155. 

I believe this would best be implemented by adding a second string field to the achievements table/APIs. The existing "mem" data would be untouched, allowing for the addition of the metadata without breaking compatibility with RetroArch or causing the "mem" field data to exceed its current 1024 byte limit..

The format of the string should be debated. For compactness, I'd recommend some sort of delimited list that runs parallel to the conditions. For example, given the TTIS mockup in #155 expanded for trigger support (https://github.com/RetroAchievements/RAIntegration/issues/52):
```
TN:Stage 2_TN:Stage End_N:Stage 1__N:Game Over_N:Cheats_N:Cheats
```
* The `T` indicator would be used to mark trigger conditions (per https://github.com/RetroAchievements/RAIntegration/issues/52)
* The `N:` prefix indicates the start of a note (TTIS) (#155). The note would continue until the next separator.
* The `_` is a separator between conditions.
* Note that the 4th condition has no metadata (two underscores together)

Underscores are currently used to separate conditions in the mem string. For something slightly more readable, the underscores could be changes to commas.

To support multiple string metadata items per condition, a metadata separator could also be introduced:
```
T|N:Stage 2|C:This seems stable_T|N:Stage End_...
```

**Comment by meleu** [comment]
@Jamiras 
I think this issue was opened before RetroArch started using rcheevos, right?

Can we close this in favor of #400 ?

**Comment by Jamiras** [comment]
Yes. It's much easier for RetroArch to uptake features now. There's still a bit of discrepancy between versions, but I don't see any reason to further pursue this solution.

The progress flag has already been implemented, and I expect the trigger flag to be implemented before this would be.
