### ISSUE TITLE
Web API case sensitive for username in user related queries

### ISSUE THREAD

**Issue by gorocz** [RetroAchievements/RAWeb#1610]
**Describe the bug**
When I try to retrieve user related data from the Web API (e.g. from API_GetGameInfoAndUserProgress.php), using different capitalization of my username retrieves data several days old (e.g. my username "gorocz" returns current data but "Gorocz" retrieves data from 4 days ago).
Authorization doesn't have a problem with capitalization of username though.

**To Reproduce**
1. Send a Web API request to API_GetGameInfoAndUserProgress.php for game 3528, user "Gorocz"
2. Do the same with user "gorocz"
3. Retrieved data is different
(This reproduction is obviously not consistent forever, since it relies on having recent progress in a specific game, but the screenshots below should be self-explainatory)

**Expected behavior**
Either the username parameter for the query should be case insensitive, or an error should be returned for incorrect username.

**Screenshots**
![picture](https://github.com/RetroAchievements/RAWeb/assets/33903218/55a163d6-e5d2-4376-89c3-de5da515703c)
![picture](https://github.com/RetroAchievements/RAWeb/assets/33903218/968fee71-5532-4fde-87b5-207e13eb628d)

**Additional context**
I know this is a trivial issue to solve from the side of the API's user, but since data was returned, just old, it was not easy to figure out where the issue was, so a fix would help any people in the future who could have this same problem.

**Comment by Jamiras** [comment]
This is most likely the result of the caching added in #1486. Per-game user unlocks are cached for 7 days at a time. Unlocking a new achievement will expire the cached record, but only for the correctly cased username. The secondary cache entry generated by querying the incorrectly cased username will still contain the old data until it expires after 7 days.

The fix should be fairly trivial - just case-correct the username before doing the cache lookup/store, but that will add another query to the call. Another option would be to normalize the case for the cache key.
