### ISSUE TITLE
RecentAchievements of API_GetUserSummary.php returns all achievements and number of recent achievements not working

### ISSUE THREAD

**Issue by DFelten** [RetroAchievements/RAWeb#1615]
**Describe the bug**

The `RecentAchievements` field of the endpoint `API_GetUserSummary.php` returns a list of recently played games including all achievements. Both unlocked and not unlocked achievements appear. Here also appear the games where I have no Achievements yet.

In addition, the parameter `a` seems to be ignored. At least I get significantly more Achievements back.

Is this the way it is supposed to be? 

**To Reproduce**
1. API call: `API_GetUserSummary.php?y={{key}}&u={{user}}`

**Expected behavior**

In the list of recent achievements, only those should appear that I actually received recently. Also, only as many as I specify via the parameter.

**Comment by Jamiras** [comment]
The `a` parameter is only filtering unlocked achievements.

For example, if you played three games:
* Game 1: Unlocked 2/15 achievements
* Game 2: Unlocked 0/10 achievements
* Game 3: Unlocked 7/12 achievements

When you call the API and ask for 3 achievements, you would get 3 of the 7 unlocked achievements from game 3, but all 5 of the locked ones. You'd also get all 10 of the locked achievements for game 2, and all 13 of the locked achievements for game 1.

If you're just looking for recent unlocks, you should use the [API_GetUserRecentAchievements](https://github.com/RetroAchievements/RAWeb/blob/master/public/API/API_GetUserRecentAchievements.php) interface. It's a much lighter API
