### ISSUE TITLE
Text Handling exceptions #2: User Motto not being exhibited correctly on certain situations on User Page and on User Card

### ISSUE THREAD

**Issue by Alexdatadestroyer** [RetroAchievements/RAWeb#1624]
Taking opportunity of my previous issue (#1619) which already has a solution provided (#1620). It's time to provide another information regarding Text Handling Exception once again. However, this only affects User Motto and its exhibition feature now: User Card and User Page.

Since this may also affect how Latin Characters (and Emojis) are handled on RA Website, I will report this before the next version release on RA Web comes to reality to avoid rework.

**Try it for yourself! It's fun!**

Switch (String.length)

- Case 1: Create a UM sentence with only 1 character (Non-LC or EMJs) and check your UP and UC.
- Case 2: Create a UM sentence with 2 characters (Non-LC or EMJs). Check your UP displaying correctly the sentence, but UC being bugged.
- Default: Create a UM sentence with 3 characters (Non-LC or EMJs). Check your UP working well as well for UC. This behavior is also maintained for more than 3 characters put on UM.

**1. Screenshots: Case 1:**

a.1) Creating a User Motto sentence with only 1 character

![](https://i.imgur.com/PqFsppp.png)

b.1) User Page with NO User Motto exhibition...

![](https://i.imgur.com/cpFO4OS.png)

c.1) User Motto is also absent on User Card

![](https://i.imgur.com/EyU1ooJ.png)

**2. Screenshots: Case 2:**

a.2) Creating a User Motto sentence with 2 characters

![](https://i.imgur.com/vBsBB78.png)

b.2) User Motto exhibited correctly on User Page...

![](https://i.imgur.com/sN2TEF5.png)

c.2) However, User Card is messed again! (Don't be fooled, this isn't the same picture used on Case 1 even with it taken on another angle!)

![](https://i.imgur.com/mLREDas.png)

**3. Screenshots: Case 3 (default) - Accepted IF Characters >= 3:**

a.3) Creating a User Motto sentence with 3 characters

![](https://i.imgur.com/DbDuAXm.png)

b.3) User Motto exhibited correctly once again...

![](https://i.imgur.com/QXl1XTD.png)

c.3) User Card now shows correctly User Motto sentence. Viva!

![](https://i.imgur.com/3hqKw4o.png)

**4. Other cases tested: Latin Characters & Emojis**

For sake of reading, I won't post more images showing how UP and UC behaviored when UM was changed: Just a quick result of those cases:

a.4) Latin Characters:

1 char: UP (Yes) | UC (No)
2 chars: UP (Yes) | UC (No)
3 chars: UP (Yes) | UC (Yes)
4 chars: UP (Yes) | UC (Yes)

b.4) Emojis:

1 char: UP (No) | UC (No)
2 chars: UP (Yes) | UC (No)
3 chars: UP (Yes) | UC (Yes)
5 chars: UP (Yes) | UC (Yes)

Emojis behaviored the same way as Normal Character, but for Latin Characters, results differ. Both behaviored the same way for 2 characters or more.

**5. Further Investigation:**

- User Page: Taking a look on RA Web repository, main issue was [found on userInfo.php file at Line 208](https://github.com/RetroAchievements/RAWeb/blob/d48689706f2276bfeb9b76f67789f588b99537c1/public/userInfo.php#L208) on mb_strlen command. According to [PHP Manual](https://www.php.net/manual/en/function.mb-strlen.php), Multi-byte is counted as 1. **So, this means that, if UP showed a LC alone, then, it's reinforces the theory/fact that LC are being counted as 2 instead of 1** - which is a bug and what was said explained by @wescopeland on #1620. UC remained unchanged though.

Extra screenshot: LC alone being shown on User Page as valid User Motto sentence:

![](https://i.imgur.com/7NAVeaP.png)

- User Card: UC seems to be programmed in Javascript. I tried to find something more directly on Main Javascript file and failed, but those Lines [98](https://github.com/RetroAchievements/RAWeb/blob/d48689706f2276bfeb9b76f67789f588b99537c1/public/js/all.js#L98) and [114](https://github.com/RetroAchievements/RAWeb/blob/d48689706f2276bfeb9b76f67789f588b99537c1/public/js/all.js#L114) seems to be linked to User Card effect. I even tried to find a direct information on [WZ Tooltip file](https://github.com/RetroAchievements/RAWeb/blob/master/public/vendor/wz_tooltip.js), but some functions are a real nightmare to understand and I found it a lot more puzzling than actually helping me, so I gave up.

This report was long to write: It was hard to match things and write everything down, but I think that the issue is mapped correctly!

**Exception Level: High** -- Easy to Reproduce, Hard to notice. However, it's [already affected](https://i.imgur.com/VTCJJ2o.png) [other users](https://retroachievements.org/user/ilikepie345) for such a long time...

**Comment by wescopeland** [comment]
It is intentional for user mottos to not render in tooltips if they are only a single character.

https://github.com/RetroAchievements/RAWeb/blob/a200152e541e65b2d187722a8c7ca989ddb44e9b/app/Helpers/render/user.php#L109

**Comment by Alexdatadestroyer** [comment]
> It is intentional for user mottos to not render in tooltips if they are only a single character.
> 
> https://github.com/RetroAchievements/RAWeb/blob/a200152e541e65b2d187722a8c7ca989ddb44e9b/app/Helpers/render/user.php#L109

Sure, I noticed that before. However, this is still buggy as it is giving unexpected behavior on such situations like explained above...

**Comment by MSGoodman** [comment]
Taking a look at this, I can see the situation is thus:

**User Profile Page**
As seen in the code below (from `userInfo.php`), we never show a user motto unless it's more than 1 character:
```
if (isset($userMotto) && mb_strlen($userMotto) > 1) {
    echo "<div class='mottocontainer'>";
    echo "<span class='usermotto'>$userMotto</span>";
    echo "</div>";
}
```

**User Card**
As seen in the code below (from `user-card.blade.php`), we never show a user motto unless it's more than _2_ characters:
```
@if($motto !== null && mb_strlen($motto) > 2)
    <div class="mb-1 rounded bg-bg text-text italic p-1 text-2xs hyphens-auto">
        <p style="word-break: break-word;">{{ $motto }}</p>
    </div>
@endif
```
---

I am unsure what exactly we're referring to with "latin characters", but I'm going to guess it has something to do with encoding which is often a pain in the butt. 

Anyhow, I have a few suggestions, any of which I'm happy to do:

1. Make the display limitation here consistent between the two 
2. Remove the display limitation entirely and just show mottos regardless of length (doesn't seem like it'd hurt anything?)
3. Consider it not a big deal and close the ticket

I'm more inclined towards 2 personally, but am happy to take someone else's lead here.

**Comment by wescopeland** [comment]
I also agree that choice 2 (remove conditionals on rendering if meeting a certain length) seems particularly desirable.

If someone wants their motto to be "A", more power to them. Concealing it from view seems like a dishonest design since we allow them to input the value in the first place.
