### ISSUE TITLE
[Bug] [Problem] Text Handling exceptions #3: Profile Name + Account Status character explosion on User Card

### ISSUE THREAD

**Issue by Alexdatadestroyer** [RetroAchievements/RAWeb#1625]
Motivated by User Motto & Textarea bug report (#1619) which was resolved already (#1620) and a related issue reported later (#1624). Now, it's time to finish this Text Handling exception Trilogy: another old problem was noticed. However, this became reality when V2 was implemented in September 2022 compared to other 2 aforementioned cases.

Since when V2 was implemented, I noticed a character explosion between Profile Name and Account Status. This also happens when User Motto is really big: On majority of cases that I ever seen, UM sentence is get wrapped inside UC - which doesn't seem to be a problem. However, in cases where a User puts a big URL, it gets clipped and bugs the UC. Sometimes, these issues are fused together.

**How to Reproduce this?**

Sorry, there is NO such a way to reproduce this issue...

Unless if you create an Account with a Name than surpasses 12 or more... This also dependents of the Account Status of the person (Registered, Unregistered, Banned, Spam, Junior Developer, Developer, Site Moderator, Invalid Permission...). So the exact Profile Name size is impossible to guess. Maybe this is possible [to be reproduced here?](https://stage.retroachievements.org/)

**Screenshots taken from various Users (Some aren't bugged):**

- [ThatAmericanSlacker](https://retroachievements.org/user/ThatAmericanSlacker) UC:

![](https://i.imgur.com/xThnoFk.png)

- [BigWeedSmokerMan](https://retroachievements.org/user/BigWeedSmokerMan) UC (UM sentence wrapped):

![](https://i.imgur.com/UPym5Cd.png)

- [AngeloLeonhart](https://retroachievements.org/user/AngeloLeonhart) UC (UM sentence wrapped):

![](https://i.imgur.com/pLFmk5o.png)

- [AllMyHomiesHateJord](https://retroachievements.org/user/AllMyHomiesHateJord) UC:

![](https://i.imgur.com/kPU2eCI.png)

- [hardcoregamertop](https://retroachievements.org/user/hardcoregamertop) UC:

![](https://i.imgur.com/VnvsmhE.png)

- [Alexdatadestroyer](https://retroachievements.org/user/Alexdatadestroyer) UC Examples:

Normal:
![](https://i.imgur.com/FlW4m9d.png)

UM clipped due to URL as UM sentence:
![](https://i.imgur.com/uvgbWmz.png)

- [IantasGames1995](https://retroachievements.org/user/IantasGames1995) UC (UM sentence wrapped):

![](https://i.imgur.com/MH6ejts.png)

- [Hotscrock](https://retroachievements.org/user/Hotscrock) UC (UM is clipped due to URL as UM sentence):

![](https://i.imgur.com/Wqeit3x.png)

- [OmegaVideoGameGod](https://retroachievements.org/user/OmegaVideoGameGod) UC (UM is clipped due to URL as UM sentence + long Profile Name). Account Status can't even be seen on this case:

![](https://i.imgur.com/Mj8Tkij.png)

Some cases are creepier than others. Some errors are more errors than others!

**Exception Level: High** -- You can see it anywhere! There is a feature on User Card bug!

**Comment by wescopeland** [comment]
Thanks for the report - I plan on resolving this as soon as https://github.com/RetroAchievements/RAWeb/pull/1429 is merged.

**Comment by Alexdatadestroyer** [comment]
No problem! I think this finishes this series of Text Handling Exceptions for now... I should had report that months ago when it was noticed :v
