### ISSUE TITLE
[Minor] [Duplicate] Which of these do you think you can get? (This link should point to a Random Set originally)

### ISSUE THREAD

**Issue by Alexdatadestroyer** [RetroAchievements/RAWeb#1626]
This idea came to my mind back in 2021-2022, but I could make it materialize just now (19-20 Jun 2023): The link on Welcome Area at Main Page only points to [Sonic the Hedgehog 1 MD set](https://retroachievements.org/game/1). I don't think this was intended since the own sentence and entire paragraph that Scott wrote years ago gives a hint of a user clicking on this link and accessing a Random Set. This is a long time pendent feature!

This feature already exists, but it can be found on dropdown "Games" menu only. However, I suppose that it should be also available on Welcome Area to preserve original intention and for being available for non-logged users. When user is logged in, Welcome Area is not visible. So, the alternative of it being available on "Games" dropdown menu comes in handy.

**Screenshot of a non-logged user: This shows that the link still points to Sonic 1 MD set since 2013:**

![](https://i.imgur.com/DVpo9Ui.png)

**Exception Level: N/A** -- Just asking for a cloning an existing feature to such a different place on RA Website.

**Comment by Alexdatadestroyer** [comment]
At this point with this already implemented, it useless to post the following message on main post... However, I would like to share what I imagined in past for a feature like this: The idea was to find a Random Set which follow these criteria:

- Non-Mature sets. Out of [[Theme - Mature] hub](https://retroachievements.org/game/8323);
- NO [Hubs (Console ID: 100)](https://retroachievements.org/gameList.php?c=100) and [Event (Console ID: 101)](https://retroachievements.org/gameList.php?c=101) sets;
- Console ID must be valid: Console must have been already released on RA Web;
- The Random Set selected must have valid Achievements online (Core; NOT Unofficial ones);
- The Random Set selected must not be any Subset. Subsets are custom challenges which would, probably, require the user to have their experience on Main Set first before dealing with them (and preparation on how to play them - RAPatches, Floating IPS, etc...)
- The Random Set selected must provide a Mastery Badge (Achievements >= 6) to avoid discouraging users from enlisting on RetroAchievements. A newcomer user wouldn't understand at first why a Mastery Badge wasn't provided after completed a Set with less than 6 Achievements - which can be disheartening.

**Comment by wescopeland** [comment]
For the welcome/splash message, I do think it makes sense for the URL to point to one of the most popular sets on the site. Perhaps it could pick one randomly from the top 20? But I do think it should point to a game users will generally recognize.

**Comment by Alexdatadestroyer** [comment]
Sonic the Hedgehog 1 is just posted there because it's the first set released on Retro Achievements. If the idea is choosing a game that users will recognize easily, then, we are talking about overrated games. Some of those overrated games aren't been accessed like it was expected to. Then, they can be put manually into an Array to be chosen randomly, giving a better audience as they should deserve.
