### ISSUE TITLE
Mastery Badge Timestamps doesn't update correctly if a Set is Mastered 2 or more times on same day in a short period of time! (GMT)

### ISSUE THREAD

**Issue by Alexdatadestroyer** [RetroAchievements/RAWeb#1627]
The exception is interesting to talk about since it came at most surprising time ever: After a First Place Race for [Sonic 1 Easy Mode hack set](https://retroachievements.org/game/8514) which happened in 16 October 2022. Since this was a peculiar thing and a bit difficult to happen again, I will try to tell this incident as more accurately as possible which may help someone to fix this issue.

**Background Story:**

At that day (16 Oct 2022 - GMT), a user - which was a Junior Developer at the time - called [FlashbackGuyYT](https://retroachievements.org/user/FlashbackGuyYT) got their set released by a Developer (or by their Code Reviewer) as well. Since the set was recently released and it's a Sonic hack (It's an adaptation of Easy Mode of Sonic 1 game from Sonic Jam anyway), I decided to race for First Place on Set Ranking there - like I did other times. Then, the set suffered a lockdown (impossible to fully master for a limit time) and the situation was like this:

2 achievements bugged. {Tickets at the time: [52658](https://retroachievements.org/ticketmanager.php?i=52658) and [52659](https://retroachievements.org/ticketmanager.php?i=52659)} So, as per Junior Developer role, those achievements needed to be demoted to get fixed (Unofficial) and promoted again to Core. Those 2 achievements, neither me and neither another experienced player called VGLongplays got those before. So, we were waiting those to come again to Core.

Since the set had more than 6 achievements, a Mastery Badge would be provided if all presented achievements on Core get obtained regardless those 2 other ones remained in Unofficial waiting to be fixed.

**Screenshot: Timestamp showing exact time when those 2 bugged achievements got Demoted at the time:**

![](https://i.imgur.com/IZyzV3b.png)

- My first mastery occurrence was at 04:39 GMT on same day. I thought that was in First Place on Set Ranking, but found that VGLongplays got last achievement at 04:09 GMT. Both 2 bugged achievements got demoted at 04:07 GMT, making the first mastery occurrence possible! I mastered the set 30 minutes behind...

- Later, when those 2 achievements were fixed, [one achievement was released before another](https://retroachievements.org/achievement/255548). So, me and VGLPs came to get it. We both "Mastered" again. So, the second occurrence was 15:48 GMT for me and 16:01 GMT for VGLongplays that time. I was taking the lead.

- Then, [the last achievement came to live](https://retroachievements.org/achievement/255552) and we both "Mastered" definitely this time. Third occurrence was 16:04 GMT for me and 16:09 for VGLongplays. I was definitely victorious. That was a hard race though! xD

After some time, I noticed something weird on Mastery Badge which called my attention: The Timestamp information didn't update as expected. I was guessing that this was caused by:

a) The same set being mastered twice in a short period of time;
b) The same set being mastered in less of 24-hour period.

Since the first and second mastery occurrence everything went normal just being the third occurrence a problem, **I would judge the first option.** Mastery Badge Timestamp only recorded the second occurrence for me and VGLongplays. The Third occurrence is only memorized on Set Ranking - which is what is truly valid since it marks when last achievement got obtained - though. A hypothetical Achievement Reset would solve this issue after some time, however, it would make me and VGLongplays lose the race. **First Place Race on Set Ranking only occurs once:** So, it's, definitely, not a valid option!

**Is there any way to reproduce this, seriously? I think there is! Try this:**

1. Try to create a dummy set with more than 6 achievements.
2. Demote 1 or 2 achievements on purpose, for example, but let at least 6 of them alive on Core.
3. Call your friends to master your dummy set for first time...
4. Then, wait some short period of time and promote that (or those) "bugged" achievements to Core again
5. Call your friends again to (Re)master your dummy set for a second time
6. Look at Timestamp of their last achievement of the set obtained and compare to Timestamps shown on their Mastery Badge. (Set Ranking will provide correct information though since it's based on last achievement obtained data!)

**1. Screenshots Provided ([Alexdatadestroyer Profile](https://retroachievements.org/user/Alexdatadestroyer)):**

a.1) First occurrence of set mastery (Left) and second occurrence of set mastery (Right):

![](https://i.imgur.com/lNfV5Tz.png)

b.1) Last Achievement Won in Sonic 1 Easy Mode (MD) set (Third set mastery occurrence) + Mastery Badge information

![](https://i.imgur.com/dlB532B.png)

**2. Screenshots Provided ([VGLongplays Profile](https://retroachievements.org/user/VGLongplays)):**

a.2) First occurrence of set mastery (Left) and second occurrence of set mastery (Right):

![](https://i.imgur.com/KX1ojAQ.png)

b.2) Last Achievement Won in Sonic 1 Easy Mode (MD) set (Third set mastery occurrence) + Mastery Badge information

![](https://i.imgur.com/bzl2Dl3.png)

**Exception Level: Low** -- It's difficult to occur again, seriously. It was just curious how it happened and I think it's deserved to be mentioned since it can happen again. This is like "one case in one million!" xD

**Comment by luchaos** [comment]
Resolved with v5?

**Comment by Alexdatadestroyer** [comment]
> Resolved with v5?
> **-- luchaos**

I can't tell for real... :/ However, since you are a Moderator, you can reproduce this issue without any problems there. Following these steps:

a) Take at least 2 dead sets (which they are already retired on [Meta|QA - gRAveyard](https://retroachievements.org/game/163) Hub). It will be 2 Test Cases. It's preferrable to take those with fewer dead achievements;
b) Promote 6 or more and do a Manual Unlock to them. NOT at same time. Wait at least for 10 seconds to do so;
c) Then, a Mastery Badge will come to your Profile;

At this time, mark the exact timestamp for both Mastery Badges. For the First Case, wait for at least 2 hours. For the Second Case, wait a little time of 10-20 minutes. Then, proceed doing...

d) Promote at least 1 or 2 more achievements to those specific Dead Sets and do a Manual Unlock to them;
e) Check your Mastery Badge now.

If I am not mistaken, **Test Case 1 will work normal while Test Case 2 won't.** I suspect that the Mastery Badge will NOT update their timestamp if the same Set gets mastered at same day for short period of time. Maybe they have at least 1 hour of threshold before timestamp update routine. This will explain why Test Case 2 will have an older timestamp mark (Only based on first time mastery instead of last time) in comparison to Test Case 1.
