### ISSUE TITLE
[Duplicate] [Enhancement] Legal: Cookie Notification Message at Main Page when RetroAchievements get visited by any User for First Time

### ISSUE THREAD

**Issue by Alexdatadestroyer** [RetroAchievements/RAWeb#1628]
Just asking for duplicate a feature that already exists: **Cookie Notification Message.** It's kinda "hidden" inside [Legal and Terms of Use](https://retroachievements.org/terms) page on RetroAchievements Website and I think it's worth to mention openly to a user regarding cookie usage due to Legal reasons.

Cookie Notification Message became important (kinda of mandatory thing) since implementation of Privacy Laws like GDPR (General Data Protection Regulation) in European Union countries, CCPA (California Consumer Privacy Act) in United States and LGPD (Lei Geral de Proteção dos Dados) in Brazil which all of them rose back in 2018. Since this is already onipresent on Internet nowadays, I think that we at RetroAchievements should have an alert regarding Cookie Usage here at Main Page as well. It's not like "jumping on bandwagon" because you can see it everywhere, but "we should do this because it's the Law, it's a Legal thing" instead.

I don't know much about Cookies, but, as far as I know, logging in session uses them since the user will be kept logged even when Browser is closed. During RAWeb V1 lifetime, Session Cookie used to expire after 7 days. Now, on V2, it's forever. When you got logged on another device, the older cookie was destroyed to allow the newer one to live - This was probably made to avoid users using double session on their account which is great!

**Screenshot: Legal & Terms page**

![](https://i.imgur.com/45ky8Iz.png)

- Extracted from "Information about cookies" section:

> You can prevent storage of cookies by appropriately setting your browser software; in this case, however, please note that you might not be able to fully use all functions offered by this website.

For Legal & Terms page, **this section is short and should be upgraded on future.** It should provide more information regarding Cookie Policy overall: How to manage Cookies preferences, a detailed explanation about CP, what the heck is this and how this affects RA Website navigation. [An example can be seem here](https://www.termsfeed.com/public/uploads/2022/03/spotify-cookies-policy-how-manage-preferences-clause.jpg).

However, the way that message is written on Legal & Terms page is perfect for just a quick Cookie Notification Message at Main Page! However, if I am not asking much is it possible to be more user-friendly? Giving an example:

> This website uses cookies to make sure you have the best experience while dealing with some impressive challenges on some sets published here! We recommend you to accept cookies in order to don't have any problems during this process or website navigation as some features might not work properly!
> 
> (Insert a "OK, Got It!" button at bottom of message)

I found a [website that talks more about this subject](https://www.termsfeed.com/blog/cookies-notification-messages/), give more Cookie Notification Messages examples - which can be used as a template - and even teaches how to create one.

I know that Legal is such a boring thing and subject to talk about, but I suppose that it's needed to be made to avoid future problems...

**Exception Level: N/A** -- Cookie Notification Message is a Legal matter. Not an exception thing.

**Comment by wescopeland** [comment]
GDPR has an exception for certain types of cookies that are considered 'strictly necessary' for the delivery of a service over the internet. This includes cookies used for the sole purpose of carrying out the transmission of a communication, and cookies that are strictly necessary in order for the provider of an information society service explicitly requested by the subscriber or user to provide the service.

Session cookies and authentication cookies that are used to manage a user's session and keep them logged in to a secure area of a website generally fall into this 'strictly necessary' category. This means they can be exempted from the requirement of informed consent under GDPR and ePrivacy Directive, assuming they do not track or profile users beyond what is necessary to maintain the session and are not used for any other purposes.

To my knowledge, RA uses no cookies beyond what is considered 'strictly necessary', thus we do not need a GDPR cookie notice.

**Comment by Alexdatadestroyer** [comment]
Found something related to this on Retro Achievements Patreon just now (04 Jul 2023) written at time when GDPR became a reality: https://www.patreon.com/posts/gdpr-and-site-19025540

I should had read that days ago...
