### ISSUE TITLE
Feed reports all leaderboard submissions

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RAWeb#163]
Noticed this in the global feed:
![image](https://user-images.githubusercontent.com/32680403/41046904-8bc1f498-6968-11e8-932f-f39158933f0e.png)
Clearly the second and third submissions were not improvements, despite the text suggesting they were. Only actual improved leaderboard values should be reported.

**Comment by meleu** [comment]
[This line of code](https://github.com/RetroAchievements/RAWeb/blob/057cf6347fd50d3c629b5b8f92e4d9ef71de24e4/lib/database/lbs.php#L85) has an `if` that on a quick glance makes me believe that would solve this. But it's commented and must have a reason for this...

Will make some tests later.

**Comment by meleu** [comment]
I noticed that actually I inserted this bug. Fixing it real quick.
