### ISSUE TITLE
[Bug] Achievement search results don't render achievement icons

### ISSUE THREAD

**Issue by monkey-bug** [RetroAchievements/RAWeb#1648]
**Describe the bug**
When searching for just achievements, the icons next to the result as well as the icons in the on-hover popup fail to render.

**To Reproduce**
1. Go to [search](https://retroachievements.org/searchresults.php)
2. Enter any text and filter for only achievements
3. See bug

**Expected behavior**
Achievement icons should be rendering in both places.

**Screenshots**
![Firefox](https://i.imgur.com/m5tmUO8.png)
![Chromium](https://i.imgur.com/OXdAFyn.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox, Chromium
 - Version: 114

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: Android
 - Browser: Firefox
 - Version: 114

**Comment by Jamiras** [comment]
Thank you for reporting.

This was already reported via discord: https://discord.com/channels/310192285306454017/1126764225130397698/1126764225130397698

And fixed by #1647. It just hasn't been deployed yet.

**Comment by monkey-bug** [comment]
Sounds good, closing.
