### ISSUE TITLE
[Minor Visual] Link background occlusion oval... thing, not centered.

### ISSUE THREAD

**Issue by Magicrafter13** [RetroAchievements/RAWeb#1669]
**Describe the bug**
When hovering mouse over entries on [this page](https://retroachievements.org/game/5596) (and presumably others), an effect is added behind the window that pops up, and it is not centered on the box vertically. I *assume* this is a bug, but also acknowledge this could be intended behavior.

**To Reproduce**
As mentioned, go to the page I linked above, and hover over one of the links in the list.

**Expected behavior**
I would expect this effect to be vertically centered on the box, especially since it looks like it would fit it (even if I don't understand the purpose of the effect).

**Screenshots**
![image](https://github.com/RetroAchievements/RAWeb/assets/29127566/64272469-a860-4b87-8f99-a459e4311dc9)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux (Kernel 6.4.2-3)
 - Browser Librewolf (Firefox fork, but this happens in vanilla Firefox too)
 - Version 115.0.1

**Comment by wescopeland** [comment]
This is intended behavior, though likely will go away when https://github.com/RetroAchievements/RAWeb/pull/1429 lands in production.
