### ISSUE TITLE
[Bug] [UI] [Forum] Text Handling Exceptions #4: Posts that have characters from foreign alphabet might not be correctly exhibited on Forum Area

### ISSUE THREAD

**Issue by Alexdatadestroyer** [RetroAchievements/RAWeb#1677]
This was noticed recently (19 Jul 2023) when I made a quick visit on Forum Recent Posts page to see what is going on the RA World...

This issue seems to happen when someone comments on a Forum Topic with characters that belongs to some foreign alphabets like Cyrillic Script, Romanji and Kanji, for example. This was noticed only for Cyrillic Script which is used as Russian Alphabet. However, it might happen for others since they are different from our alphabet - in terms of programming, I mean "Ordinary Alphanumeric Characters".

I believe that screenshots below will tell more than words might tell after all...

**Screenshots:**

- Original commentary from [Xnaivx](https://retroachievements.org/user/xnaivx) on [this forum topic](https://retroachievements.org/viewtopic.php?t=2202&c=176514#176514):

![](https://i.imgur.com/IAwp2MZ.png)

- Blank commentary when viewed from Forum Recent Posts page:

![](https://i.imgur.com/t8mzmUC.png)

- However, the commentary is "almost" viewed correctly from Forum Post History page: It shows a glitched character at the end of sentence (something characteristic of charsets handling issue):

![](https://i.imgur.com/vSP0Z6y.png)

**Exception Level: High** -- This issue might affect other users which use foreign alphabet symbols. However, their commentary it's not affected when a forum topic is fully viewed.

**Comment by wescopeland** [comment]
I'm having trouble reproducing this locally when the post string is:

```
Да, вот сюда надо отправить сообщение чтобы тебя одобрили с ником из дискорда
https://retroachievements.org/createmessage.php?t=RAdmin
```

**Comment by luchaos** [comment]
Will be resolved with the move to `utf8mb4` later this week.

**Comment by luchaos** [comment]
`utf8mb4` is in place and should not be an issue anymore
