### ISSUE TITLE
[Bug] [UI] [Tooltips] User Card image loses its quality when compared to original one shown on User Profile page

### ISSUE THREAD

**Issue by Alexdatadestroyer** [RetroAchievements/RAWeb#1691]
Another problem was noticed recently regarding User Card since V3.1.0 was released days ago...

The image loses its quality when compared to original image exhibited on User Profile page. No matter if the image was uploaded by user or the default is being used. Looking closely to both images involved, it seems that the one used to be shown on User Card was converted to a lossy quality format (like PNG to JPG, for example) or it suffered the Aliasing Effect since some "Jaggies" (distortions) can be seem on the image.

**Yes, you can reproduce it:**

1. Upload any image or reset to default one;
2. Visit your User Profile page;
3. Place a comment on your User Wall;
4. Look to your avatar shown on User Card and compare to it exhibited on your UP: if you look closely, you will notice the quality loss between images.

Strangely enough, the Tooltip Card Effect - which is also used for showing achievement, set and profile badges informations - doesn't affect other website elements. So, pointing to any achievement, set page or a badge will return the image quality being displayed normally when compared to their original ones.

The image shown on top right corner area (next to your account name, points and retro points) isn't affected by this issue either.

**Screenshots taken from some users:**

- White Backgrounded avatar: [Alexdatadestroyer](https://retroachievements.org/user/Alexdatadestroyer) -- Green (original) | Red (downgraded)

![](https://i.imgur.com/Ailz5Ld.png)
![](https://i.imgur.com/Val1vTa.png)

- Any Backgrounded avatar: [danilofent97](https://retroachievements.org/user/danilofent97) -- Green (original) | Red (downgraded)

![](https://i.imgur.com/fpgD1pq.png)
![](https://i.imgur.com/O6O6Pfy.png)

- A user with Default avatar: [mmalzone](https://retroachievements.org/user/mmalzone) -- Green (original) | Red (downgraded)

![](https://i.imgur.com/2EenC7g.png)
![](https://i.imgur.com/lASdDRk.png)

- Black Backgrounded (or Transparent?) avatar: [MauricioReis](https://retroachievements.org/user/MauricioReis) -- Green (original) | Red (downgraded)

![](https://i.imgur.com/HxKXOAM.png)
![](https://i.imgur.com/lmfAAv5.png)

**Additional Information:**

Taking a better look on images posted above, the quality loss issue can also be noticed on UC characters when compared to others placed on User Wall. This indicates that the problem might affect the UC component altogether instead of just avatar area!

All uploaded images on Imgur are on PNG format. No zoom was used either.

**Exception Level: Medium** -- The quality loss issue can be missed easily and the problem seems to affect the entire UC component when compared to characters on a UW. However, the situation could be worse than actually is if this had affected another website element though.

**Comment by wescopeland** [comment]
This is being caused by a CSS filter that should probably only be conditionally applied.
