### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by Gorilli09** [RetroAchievements/RAWeb#1718]
Every time I go onto the RA website, it says it's temporarily unavailable.

**Comment by wescopeland** [comment]
The RetroAchievements website is currently offline, we apologize for any inconvenience caused.

You can still earn achievements in any supported emulator.

Make sure that the emulator has informed you that you have successfully logged in before you begin playing to avoid missing unlocks.

For more information and updates, please join our [Discord](https://discord.gg/retroachievements).
