### ISSUE TITLE
The results field doesn't follow the navbar / search input

### ISSUE THREAD

**Issue by w400pedro** [RetroAchievements/RAWeb#1723]
#### Search for something in the input, then the results will be shown, and after that, scroll up or down to see the issue.

I will attach this video recorded on Google Chrome to provide a better description:

https://www.youtube.com/watch?v=niMlP61HnCY

**Comment by wescopeland** [comment]
I believe this has to do with the search box's current implementation using jQuery UI Autocomplete, which is not very flexible and difficult to extend.

It would probably be ideal to consider migrating this away from the jQuery UI component to something like Floating UI. The tricky part is getting accessibility right, as this would all need to be reimplemented from scratch.

WAI-ARIA compliance guidelines on such a component can be found here: https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-list/
