### ISSUE TITLE
General discussion about PHP/Laravel/SQL/etc

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAWeb#173]
**This is not an issue nor a feature request!**

Just a thread where we can share some tips and tricks about PHP and thoughts about some parts of RAWeb's code.

**Comment by meleu** [comment]
@luchaos I was taking a look at the [new features of PHP 7](http://php.net/manual/en/migration70.new-features.php) and noticed an interesting operator: [Null coalescing operator](http://php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op).

Am I wrong or we could make `seekGET()`, `seekPOST()` and `seekPOSTorGET()` like this:

```php
function seekGET( $key, $default = NULL )
{
    return $_GET[ $key ] ?? $default;
}

function seekPOST( $key, $default = NULL )
{
    return $_POST[ $key ] ?? $default;
}

function seekPOSTorGET( $key, $default = NULL, $type = NULL )
{
    $retval = $_POST[ $key ] ?? $_GET[ $key ] ?? $default;
    if( isset( $type ) )
        settype( $retval, $type );
    return $retval;
}
```

**Comment by luchaos** [comment]
that does indeed work, very useful as it omits errors as well (like when the check in question is an undefined index of an array)
and makes it shorter than to write multipe ternary operations ($a = $b ? $c : $d)
(seekGET and seekPOST will be removed at some point though)

**Comment by meleu** [comment]
@luchaos this part of my code:
```php
    if( isset( $type ) )
        settype( $retval, $type );
```
brought me a question: is there a builtin way to check if an input is a valid type? Or would I need to hardcode the comparison with the known valid types?

**Comment by luchaos** [comment]
@meleu with Laravel we will have an Validator at hand with extensive options (see https://laravel.com/docs/5.6/validation)
There will be plenty of such validation rules prepared in the framework branch as a reference.

**Comment by luchaos** [comment]
We definitely will have an API documentation, but not like Laravel's internal API as that's for the framework, library API docs. The API we're exposing is not for a library but for a web API. 
For web APIs like RA's Web API and App (client) API there are more suitable ways to generate docs, Laravel can do that based on routes. We will have those linked on that page for both v1 legacy and the new v2 api, as well as oauth related endpoints: https://stage.retroachievements.org/api
