### ISSUE TITLE
Notifications for authored content

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RAWeb#175]
As a developer, I'd like to be notified when someone posts a comment to an achievement I made or a game for which I have made achievements.

Currently, only those users who have previously commented on the achievement or game page are notified. This issue requests expanding the notification list to include the achievement author for achievement comments, or anyone attributed as an achievement author for the game for game comments.

This could also be addressed by having the ability to subscribe/unsubscribe to any game/achievement as described in #5, but an achievement author should automatically be subscribed to the game/achievement when the achievement is uploaded.

**Comment by meleu** [comment]
Duplicated. See #3.
