### ISSUE TITLE
[Bug] [UI] [Forum] Text Handling Exceptions #4-2: Posts that have hypertext message might not get displayed correctly on Forum Posts

### ISSUE THREAD

**Issue by Alexdatadestroyer** [RetroAchievements/RAWeb#1755]
This issue is similar to #1677 which also affects the Forum Area: This time, hypertexted messages seems to give problems since only a small portion of the message is shown. The expected behavior was to show the entire message or a major portion of them if they are too long.

1. Original commentary from [pinguupinguu](https://retroachievements.org/user/pinguupinguu) on a [Forum Topic](https://retroachievements.org/viewtopic.php?t=5910&c=178824#178824):

![](https://i.imgur.com/TGxoXrm.png)

2. The message gets partially cut on Forum Recent Posts page:

![](https://i.imgur.com/V66dBez.png)

3. Then, the same behavior is noted on [pinguupinguu's Forum Post History](https://retroachievements.org/forumposthistory.php?u=pinguupinguu) page:

![](https://i.imgur.com/uj3a8D9.png)

As it was mentioned here https://github.com/RetroAchievements/RAWeb/issues/1677#issuecomment-1643932420 when foreign alphabet issue was reported and since this issue is similar to that, I took a look on `stripAndClamp` function to find the culprit, but couldn't.

https://github.com/RetroAchievements/RAWeb/blob/6f0c8b05cf9da150ac7ece99ee8184f8323e12ea/app/Support/Shortcode/Shortcode.php#L43-L126

I tried to count characters from majority of forum posts and they match 90 to 100 characters. `$previewLength` has a limit of 100 characters, but I don't think that those 90-chars cases are a problem since they may match any of those restrictions pointed there on function. In any case, it worths to be mentioned.

**Character Count Experiment:**

![](https://i.imgur.com/ZphLMKD.png)

However, there was a case that called my attention - which it might be something obvious, but a bit hard to notice: The URL tag. I have done a test based on original Pinguu's message and Reverse Engineering with help of "Preview" feature already available on Forum Area as shown above and got some results:

a) Message correctly exhibited: 13 characters (Shown on Items 2 and 3)

`Guess who's b`

b) Full message exhibited on forum post (hypertexted): 29 characters (Shown on Item 1)

`Guess who's back, back again?`

c) Full message when done Reverse Engineering: 112 characters

`[url=https://www.youtube.com/watch?v=-8xhmV3JoG4&pp=ygUKd2l0aG91dCBtZQ%3D%3D]Guess who's back, back again?[/url]`

d) Exhibited message after done Reverse Engineering: 90 characters (The message body matches with one presented on Item A above)

`[url=https://www.youtube.com/watch?v=-8xhmV3JoG4&pp=ygUKd2l0aG91dCBtZQ%3D%3D]Guess who's b`

e) Exhibited message after Reverse Engineering forcing 100 characters to be shown as per rule of `$previewLength`:

`[url=https://www.youtube.com/watch?v=-8xhmV3JoG4&pp=ygUKd2l0aG91dCBtZQ%3D%3D]Guess who's back, back `

With this experiment, it's proven that the text of link given to URL tag is causing interference on character count variable (`$previewLength`) overall - which is fusing the text of it + the text put to be shown hyperlinked on a post. Perhaps, a solution might be **to ignore the text of link inside URL tag and only consider the exhibited text?** Since Pinguu's message has only 29 characters (Item B), this would solve the issue.

However, I noticed something important which needs to mention: Showing a hypertexted message on a forum post through Forum Recent Posts is a bad idea since it might "encourage" spam messages. For cases like this, I think **we should display the message, but with hypertext effect removed.** Display like a normal message. That might mean another rule to be assigned on Shortcode.php file if this wasn't already assigned.

**Additional Information:**

The site used to count characters was [this one](https://contadorcaracteres.com.br/). I considered characters with blank spaces as factor for evaluation.

**Exception Level: High** -- Easy to reproduce if you give a wider link to URL tag. Even if this affects hypertexted messages, the function might need a special treatment for cases like this if not done already. Also, in future, if more forum tags are vulnerable to user given texts, this issue might happen on those too. (Example: Spoiler tag with subtitles)

**Comment by luchaos** [comment]
> Showing a hypertexted message on a forum post through Forum Recent Posts is a bad idea since it might "encourage" spam messages. For cases like this, I think we should display the message, but with hypertext effect removed. Display like a normal message.

Fully agreed - this is the case if I'm not mistaken?.

**Comment by Alexdatadestroyer** [comment]
> > Showing a hypertexted message on a forum post through Forum Recent Posts is a bad idea since it might "encourage" spam messages. For cases like this, I think we should display the message, but with hypertext effect removed. Display like a normal message.
> > **-- Alexdatadestroyer**
> 
> Fully agreed - this is the case if I'm not mistaken?.
> **-- luchaos**

In summary, yes. For the example above, the expected behavior was to show the entire message hypertexted (since it had a Youtube video linked). However, hypertexts might encourage spam. So, that's why I said that removing it would be something to add while fixing this issue

**Comment by Alexdatadestroyer** [comment]
This issue seems to be already been fixed at this point of RAWeb v6.7.1 version. Links arent valid anymore when a user post a hypertexted message as expected 👍
