### ISSUE TITLE
Cannot test anything

### ISSUE THREAD

**Issue by SyrianBallaS** [RetroAchievements/RAWeb#18]
So I loaded up the repo in NetBeans using IIS (Internet Information Services) as the web server for local testing (that's all I have). I'm assuming index.php is the entry point.

No matter what I do it says "Error: Could not connect to database. Please try again later." Is there a connection string or something missing? The live application/website still works though. Would appreciate knowing what tools are necessary to test and develop.

**Comment by luchaos** [comment]
i'll write up concise setup guides later today for both windows and macos.
the site itself runs on an apache server so you might want to switch to that from iis.
a mysql database is needed, you can enter your local database credentials to https://github.com/RetroAchievements/RAWeb/blob/master/_db_secrets.php

on a general note: the setup of the site might change a bit to follow common php project best practices.

**Comment by SyrianBallaS** [comment]
Thank a lot! I'm mostly a ASP.NET(Core) guy, I figured this would be a good opportunity to brush up on PHP.

**Comment by luchaos** [comment]
Very nice! :)
Here's the issue specifically for this task (to not forget): https://github.com/RetroAchievements/RAWeb/issues/22

**Comment by meleu** [comment]
Can we close this issue here?

**Comment by SyrianBallaS** [comment]
I think it's fine, close it.
