### ISSUE TITLE
Comments can alert self

### ISSUE THREAD

**Issue by ScottFromDerby** [RetroAchievements/RAWeb#187]
When adding a comment to achievement, game or user pages, if a user comments twice they will receive an email to tell them that someone has commented on their comment. Self should be excluded from the users to notify when commenting on a (a/g/u) comment chain.

**Comment by meleu** [comment]
I've just tested on [my user page wall](http://retroachievements.org/user/meleu) and on [this achievement's page](http://retroachievements.org/Achievement/55580). Unable to reproduce.

Looks like it's being checked [in this part of the code](https://github.com/RetroAchievements/RAWeb/blob/6f38ca262fbb5e05ffeb961deaa3560f0c004d90/lib/database/activity.php#L406).

**Comment by ScottFromDerby** [comment]
Ah OK, maybe it's just me?

I was getting *tons* of "Hey Server" emails for every achievement thread update. You're right it looks like it shouldn't do this... not sure why it was duplicating that email then, maybe some discrepancy when posting on behalf via Server? Either way I've removed my email address from "Server"'s account, fixes the problem but maybe not if there's still an issue :P

Thanks so much for doing the recon work!

**Comment by meleu** [comment]
Oh, then there's a person who receives notifications for the Server user? Whoops! :sweat_smile: 

Pretty sure it's related to my recent change to create a (pseudo) audit log. I'm using the Server to post messages like the ones you can see here: http://retroachievements.org/Achievement/61678

I've tweaked the `addArticleComment()` function to [avoid spam cheevos Author's mail box](https://github.com/RetroAchievements/RAWeb/blob/6f38ca262fbb5e05ffeb961deaa3560f0c004d90/lib/database/activity.php#L504). My reasoning is: they don't need to receive a notification when they are making the changes.

Well, I confess it's an ugly workaround. But it's temporary, we'll have an actual audit log on V2.
