### ISSUE TITLE
Sort games by category: Publishers, developers, etc.

### ISSUE THREAD

**Issue by rabbids4eva** [RetroAchievements/RAWeb#189]
There should be a sorting feature for a list of available achievement lists for games. If so, I'd love to see them have the following categories:

By Publisher (THQ, SEGA, Nintendo, LJN, CAPCOM, Namco, SNK, Taito, Square Enix, EA, Activision etc.)
By Developer (Rare, Vicarious Visions, Game Freak, HAL Laboratories, Nintendo R&D1, Codemasters etc.)
By Year (1983, 2001, 2006, 1998 etc.)
By Popularity
New Additions First
Old Additions First

**Comment by meleu** [comment]
Duplicated. See #68. Also related to #69.

Closing this issue here.
