### ISSUE TITLE
Feature: Top New Sets

### ISSUE THREAD

**Issue by rabbids4eva** [RetroAchievements/RAWeb#195]
When there are at least six new sets, users would have voted which new achievement sets are the best from the six. The one with most votes get featured on the featured list of the top six. The order would be like this:

1 - Gold
2 - Silver
3 - Bronze
4 - Plastic
5 - Wood
6 - Rubber Duck

**Comment by meleu** [comment]
We plan to add other ways to "upvote" a set. But not related with the 6 newest ones.

Closing this issue here.
