### ISSUE TITLE
Over-aggressive sanitization (character stripping) in site comments

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAWeb#200]
Most site pages use a comment system that strips non-ASCII characters, as well as `<`  and `>`, in contexts where it should not be necessary. Accented characters and other non-English characters, use of the `<` and `>` symbols to compare numerical values, etc. are erased from comments with no feedback. In contrast, forum messages and other text forms accept non-ASCII input without a problem.

**Comment by luchaos** [comment]
Reference: https://github.com/RetroAchievements/RAWeb/blob/master/public/request/comment/create.php#L23

**Comment by luchaos** [comment]
Guess we fixed that at some point. Closing.
