### ISSUE TITLE
Invalid game IDs sent by RAIntegration should be ignored

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAWeb#202]
Possibly due to an issue in `RAIntegration`, a game ID of 0 can be sent when no link is found for a given file. Despite not being a valid entry, it is shown on user pages as a blank entry (see the screenshot below), and possibly in other areas.

![image](https://user-images.githubusercontent.com/7488362/43601399-0d7714c2-965b-11e8-8063-c3f4a7ce8b0e.png)

The issue could be similar as the one resolved in #201.

**Comment by luchaos** [comment]
Closing, assuming that this is issue has been resolved by now. Please open a new issue if this issue still persists.
