### ISSUE TITLE
Compare with user doesn't show hardcore indicators for second user

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RAWeb#204]
When using the "compare with user" feature, the user's achievements don't have gold borders, the "-= HARDCORE =-" header, and the summary doesn't indicate bonus completion.

![image](https://user-images.githubusercontent.com/32680403/43680032-69bde1f4-97ee-11e8-87e0-a605dce9d5e8.png)

The user has earned the achievements in hardcore mode:

![image](https://user-images.githubusercontent.com/32680403/43680037-8c166faa-97ee-11e8-83fb-bd3ff98eefda.png)

Also note that _my_ completion on the "compare with user" page shows as 118/59 and 800/400, but the other user's profile completion shows 59/59 and 400/400. These should both display the same value. My suggestion is to modify the "compare with user" to also show 59/59 and 400/400, or possibly modify both to show 59/59 and 800/400.

**Comment by Jamiras** [comment]
Looks like a key mismatch between `getGameMetadataByFlags` and `gamecompare.php`.

* `DateEarnedFriendHardcore`: https://github.com/RetroAchievements/RAWeb/blob/22cadeac97e90f45e50fd94f19b4618f4420c73d/lib/database/game.php#L266
* `DateEarnedHardcoreFriend`: https://github.com/RetroAchievements/RAWeb/blob/74a5f83048ef3578261458d22a3dae44a9e0b3a5/public/gamecompare.php#L151

**Comment by televandalist** [comment]
Same thing happens with the game page, too. 

![654987](https://user-images.githubusercontent.com/45054151/104103334-23c2a500-5267-11eb-9efc-7ce1f9222310.PNG)
