### ISSUE TITLE
"Usable for a human" links

### ISSUE THREAD

**Issue by gogtytsufvhgekwzyuow** [RetroAchievements/RAWeb#205]
Links now: http(s)://retroachievements.org/game/[ID]

"Usable for a human": http(s)://retroachievements.org/[Platform]/[GameTitle]

Examples: 
http(s)://retroachievements.org/NES/Super_Mario_Bros.
http(s)://retroachievements.org/Mega_Drive/Sonic_the_Hedgehog

And if "404" then instead show search page with request.

**Comment by luchaos** [comment]
tanks for the suggestion - this is planned for v2 and partially implemented already.

**Comment by luchaos** [comment]
See https://dev.retroachievements.org/game/228-super-mario-world
