### ISSUE TITLE
Expiring claim notification does not disappear after extending claim

### ISSUE THREAD

**Issue by suspect15** [RetroAchievements/RAWeb#2076]
**Describe the bug**
The "Claim Expiring Soon" notification appeared at the correct time, however it remains present after I renewed the claim that was within a week of expiring.  Clicking through to the Expiring Claims page now shows nothing populated and I have no claims within a week of expiring any longer.

**To Reproduce**
1. Have claim within a week of expiring
2. Get "Claim Expiring Soon" notification
3. Extend claim
4. Observe notification persisting

**Expected behavior**
I expected the notification to disappear when I no longer had any claims within 1 week of expiration.

**Screenshots**
![image](https://github.com/RetroAchievements/RAWeb/assets/106546659/6b2fdda6-b3cb-4727-8d9b-21c06c9d200d)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 120.0.1

**Comment by suspect15** [comment]
The notification disappeared after about 30 minutes, so this may not be an issue after all.

**Comment by redwizard42** [comment]
Happens to all of us. Sticks around for 30min-an hour.

**Comment by Jamiras** [comment]
Related: #1928 
> Claim information is cached for one hour at a time. 

I'll see if I can forcefully expire it on renewal.
