### ISSUE TITLE
Mega Games heading on All Games List

### ISSUE THREAD

**Issue by CoolCanuck** [RetroAchievements/RAWeb#209]
On https://retroachievements.org/gameList.php, the heading is "Mega Drive games with achievements", but the page isn't for Mega Drive -- it's all available games for all systems (first option under "Support")

**Comment by Shikamaru-91** [comment]
The heading is "All Games" for Supported Games and "All Games >> Mega Drive Games" for Mega Drive

**Comment by meleu** [comment]
It lists all available games indeed, but as Mega Drive is the first supported console, it appears first.

If you scroll down you'll see the other games.

Closing this issue.
