### ISSUE TITLE
Follow basic PHP Project best practices

### ISSUE THREAD

**Issue by luchaos** [RetroAchievements/RAWeb#21]
Most of what currently resides in the document root of the project should be moved to a `public` folder.

This will allow us to be in control over what is exposed through the site and what is only meant to be consumed by the backend (e.g. composer dependencies that will live in `vendor`, chat service node application in its own space, etc.)

The directory layout would look something like that:

```
/chat/package.json <- chat service npm dependencies
/chat/... <- chat node application
/public/... <- here be majority of scripts that are currently in the root of the project
/storage/... <- here be logs, cronjob created files, etc
/vendor/... <- composer dependencies
/composer.json
/composer.phar
/package.json <- npm frontend dependencies
/... <- other private, project relevant files like configs may live here
```

this makes it much easier to reason about where the source is that one might be looking for - clustering together scripts by usage. comes with the benefit of appearing much nicer in the ide/code editor of choice as well.

Moving to the public folder also means that the web server has to be configured to point to that directory instead.

**Comment by GameDragon2k** [comment]
Wouldn't changing the directory of the scripts affect the emulators that use these scripts as well?

**Comment by luchaos** [comment]
i'm sorry, i forgot to explicitly state that as well: on the public side, none of the addresses would be affected - it would all look the same from the outside.
if i understood correctly that is - you mean emulators interfacing with scripts on the site, e.g. by calling http://retroachievements.org/script.php, right?

**Comment by luchaos** [comment]
what the directory change implies, apart from a cleaner look, is that it will not be possible to simply call any file outside the public directory.

as soon as we start using libraries pulled in by php's dependency manager, those would go into a `vendor` folder. we would not want to allow anyone to call e.g. `http://retroachievements.org/vendor/lib/src/script.php`

another advantage is that we can move filers to a private location without implementing extra security measures; like secrets in environment configurations, data storage etc - all things that are only meant to be consumed by php but should not be exposed publicly simply by calling the according address.

**Comment by SyrianBallaS** [comment]
I'm not sure if there is something similar in PHP but in .NET Core there's a concept of "user secrets". How it works is that on the command line, you specify a key/value pair and it stores the secret in a json file (secrets.json) deep in the user folder. It's cross-platform so I'm almost certain it works for Linux and Mac.

Secrets shouldn't really be in source control anyway. I could probably emulate it using PowerShell Core (cross-platform version of Windows PowerShell).

**Comment by luchaos** [comment]
that sounds very convenient! there is a comparable way to do this in php - there's a composer package for `.env` files that reside in the root of the project and are gitignored. there'd be another version controlled `.env.example` with sensible defaults that can be copied over and adjusted for different environments. i will add this in the upcoming days.

**Comment by luchaos** [comment]
All done - that's awesome @ScottFromDerby !
Closing.
