### ISSUE TITLE
User Score History Graph X-Axis Off by One Month

### ISSUE THREAD

**Issue by benjamincampbell** [RetroAchievements/RAWeb#2101]
**Describe the bug**
The History graph on a user's History page has the months labeled on the X-axis offset in the wrong direction by 1 month. It displays "January 2024" and then 4, 6, 8... etc. when in reality this is December 2023. Hovering over the data points in the graph itself confirm that these are for December, not January.

**To Reproduce**
1. Go to a user's profile
2. Click on "more..." under the Recent Progress section on the right sidebar
3.  See that the X-axis is labeled with the most current (right-most) month being January 2024, not December 2023

**Expected behavior**
The X-axis should (as of writing) have December 2023 as the most current labeled month.

**Screenshots**
![RA_axis_bug](https://github.com/RetroAchievements/RAWeb/assets/3676620/17f9a3a0-3dd3-436f-8fc9-b37ae2379e03)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 
 - Version 120.0.1, 64-bit

**Comment by wescopeland** [comment]
I've confirmed this issue is being caused because JavaScript zero-indexes months instead of beginning at 1 for January. In other words, JavaScript believes December is month 11.
