### ISSUE TITLE
Tabs in Game Info Messing Up Database Queries

### ISSUE THREAD

**Issue by televandalist** [RetroAchievements/RAWeb#2113]
**Describe the bug**
If someone puts a tab in an entry's Developer, Publisher, Genre, or Release Date fields, exporting queries to .csv will include the tabs. I went to those entries and removed the tabs, but it's something that happens pretty often. Maybe block tabs in those fields?

**To Reproduce**
1. Insert a tab in one of the above fields. I'm assuming it's from people copy/pasting info and not removing tabs.
2. Update the info.
3. Do a server query for game info and export to csv.
4. Import the csv into a spreadsheet.

**Expected behavior**
All info should be in a single column when importing the csv to a spreadsheet, at least until "Split text to columns" is selected (or whatever the Excel equivalent is). 

**Screenshots**
<img width="731" alt="zx" src="https://github.com/RetroAchievements/RAWeb/assets/45054151/6727b10a-b9e7-42c3-910f-7c898d19597b">
(Rows 2-17 had tabs in the game info)

**Comment by redwizard42** [comment]
I would personally have it trim leading and trails ng whitespace, and convert all other whitespace to a single space character.

**Comment by MSGoodman** [comment]
This seems like a pretty straightforward fix. I haven't looked at the codebase or run it locally yet, but this seems like a reasonable first ticket to onboard with, if y'all are accepting new contributors. If so, a couple of silly questions from a complete newbie:

> 1. Insert a tab in one of the above fields. I'm assuming it's from people copy/pasting info and not removing tabs.
> 2. Update the info.
Users can do this on the site? Where/how?

> 3. Do a server query for game info and export to csv.
What do you mean when you say this? Is this a feature built into the site? Or are you talking about just straight-up querying the database? If so, how can I get such (presumably/hopefully read-only) access?

**Comment by wescopeland** [comment]
Fixing this issue will likely require two key components:
* Added validation to prevent the problem from reoccurring. Back-end validation should be added to _update-meta.php_ and front-end validation should _possibly_ be added to _gameInfo.php_.
* A sync command should be written to update existing poisoned records in the `GameData` table.

@MSGoodman Per our conversation on Discord, I am happy to assist you with local setup. Please do not hesitate to reach out to me for support.
