### ISSUE TITLE
API_GetGameExtended returns undesirable fields

### ISSUE THREAD

**Issue by wescopeland** [RetroAchievements/RAWeb#2134]
**Describe the bug**
https://github.com/RetroAchievements/RAWeb/pull/2126#pullrequestreview-1801252883

This endpoint should not return `players_total`, `achievement_set_version_hash`, `achievements_published`, or `points_total`.

**Additional context**
This is likely occurring because the endpoint is using a helper function(s). We should detach it from that.

**Comment by jacobguinther** [comment]
Are you proposing a new helper function similar to `getGameMetadata` or to just replicate the useful logic from that helper into `API_GetGameExtended`?

These fields are introduced when `getGameMetadata` calls `getGameData`.

We could just unset them in `API_GetGameExtended`

Are there large portions of `getGameMetadata` that are unnecessary? The `$user` and `$user2` parameters are not used in `API_GetGameExtended` but that's the only logic I noticed that wouldn't need to be replicated.

**Comment by wescopeland** [comment]
> We could just unset them in API_GetGameExtended.

The web API should generally be detached from internal helper functions and rely more on Eloquent ORM for data retrieval. 

Calling `unset()` does indeed solve the issue, but not the root problem. Any time these internal helper functions change, the shape of data returned by the web API will also change.
