### ISSUE TITLE
Standalone platform producing null or "N/A" abbreviation on Last X Games Played widget

### ISSUE THREAD

**Issue by hb-robo** [RetroAchievements/RAWeb#2176]
**Describe the bug**
Looks like the Standalone platform isn't abbreviating correctly on these smaller platform indicators. That or it doesn't have one assigned, hence the "N/A" we're seeing. 

**To Reproduce**
1. Go to [user profile for horizonxi](https://retroachievements.org/user/horizonxi)
2. Scroll down to 'Last 3 games played'
3. See error for each of the three games listed

These are the only 3 games on the Standalone platform (officially anyway) and this is the only "user" that can currently "play" them.

**Expected behavior**
Instead of "N/A," the abbreviated text for the Standalone platform should read similarly to other consoles, e.g., GBA, N64, PS2, etc.

**Screenshots**
![image](https://github.com/RetroAchievements/RAWeb/assets/26484694/696224cb-8c60-4570-afa9-6080d0bb59bc)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge for Business
 - Version 120.0.2210.144 (Official build) (64-bit)

**Comment by luchaos** [comment]
Will be changed to `EXE` with the next release. See https://github.com/RetroAchievements/RAWeb/pull/2172
