### ISSUE TITLE
Unregistered Users

### ISSUE THREAD

**Issue by CoolCanuck** [RetroAchievements/RAWeb#220]
Unregistered users show very strangely on the site.  

* They are shown as site rank 1 on their profile page
* they are tracked and are in the site feed displaying what games they play
* links on their profile for ~~adding~~ following, blocking, and sending a private message (messages even get sent successfully) appear

![image](https://user-images.githubusercontent.com/15615155/45588708-e7751900-b8e6-11e8-97ba-21f2e14a90f3.png)

Unregistered users are currently messing up the display of the feed and the active players feed. 
![image](https://user-images.githubusercontent.com/15615155/45588727-65392480-b8e7-11e8-98f2-50de873192ed.png) 
![image](https://user-images.githubusercontent.com/15615155/45588731-75e99a80-b8e7-11e8-8224-7b6f0e2de333.png)

 (notice how the column width is now messed up).

Can we at least show the default profile picture (joystick) for now? This can be achieved by seting the 404 ErrorPage for /UserPic/* to return a php file with a png header and the default profile picture. You could also redirect to the default profile picture file.

**Comment by luchaos** [comment]
> Site Rank: Needs at least 500 points.

Site feed has been removed.

Add, block, send message actions are technically fine to be there for unregistered users.

Missing avatars have been fixed on the webserver level: https://retroachievements.org/UserPic/ThisIsNotTheAvatarYouAreLookingFor.png
