### ISSUE TITLE
Add leaderboads in the API

### ISSUE THREAD

**Issue by Nelfe80** [RetroAchievements/RAWeb#2246]
Hello,

I'm working on your API with Leaderboard support.
(just ideas with old codes, sorry)

Upgraded GetLeaderboardRankingJSON Function
with nifty pagination (thanks to $offset and $limit)

Endpoints:
API_GetGameInfoAndUserProgress.php extend with detailed leaderboard data.
API_GetLeaderboardCount.php
API_GetLeaderboardRanking.php: To know where you stand in the leaderboard
API_GetLeaderboards.php
API_GetTopLeaderboardScores.php: To get realtime rank
API_GetUserLeaderboardGameRankAndScore.php

(i'm developing a marquee system to display all these retro achievements and leaderboard stats)

Thanks

Best regards

(https://github.com/juherr/RAWeb/compare/develop...Nelfe80:RAWeb:LeaderboardsAPI?expand=1)
(https://github.com/Nelfe80/RAWeb/tree/LeaderboardsAPI/public/API)

**Comment by Nelfe80** [comment]
Sorry i'm tired

**Comment by wescopeland** [comment]
No worries, let's keep this in the discussion thread.
https://github.com/RetroAchievements/RAWeb/discussions/2081#discussioncomment-8436576
