### ISSUE TITLE
Recommendation

### ISSUE THREAD

**Issue by coolscribble** [RetroAchievements/RAWeb#227]
What about some button or anything which will recommend you something from similar games with cheevos you were playing?

**Comment by kdecks** [comment]
This exists in the sidebar of every gamepage.
![image](https://user-images.githubusercontent.com/32706333/46256099-629c0a80-c463-11e8-882a-26dcd5c9731c.png)
As a developer you can add to this list by going into the game page Dev tools and then adding the game id's here
![image](https://user-images.githubusercontent.com/32706333/46256112-9119e580-c463-11e8-8c81-3c584baa0375.png)
