### ISSUE TITLE
Add CORS headers to api responses to simplify Emuchievements code

### ISSUE THREAD

**Issue by Witherking25** [RetroAchievements/RAWeb#2275]
Steam runs in CEF, and technically the web stuff runs under the domain `steamloopback.host`, so whenever you try to `fetch()` stuff from websites it complains about the site not responding with CORS headers that include `steamloopback.host` and fails. Decky gets around this by doing a roundabout thing where you call a different function provided by decky that sends your request to the python backend and then uses aiohttp to actually do the request. It would be nice if y'all added `"Access-Control-Allow-Origin": "steamloopback.host"` to all the response headers because then I could just use the regular fetch and it would clean up the network tab in the debugger too.

**Comment by wescopeland** [comment]
Transferred from `api-js` to `RAWeb`. This sounds like more of an infra issue. I have no opinion on it; seems appropriate to assign to @luchaos who can give the final word.

**Comment by luchaos** [comment]
The Web API has the allow origin header set to `*`. The Connect API (dorequest) is not meant to be consumed like this. I think we discussed this before - it would be great if we can introduce the hash lookup features to the Web API so the Connect API can stay as-is.

There are other use-cases where we might have to revisit how the Connect API can be accessed in a similar fashion but that's still quite a long way to go.

**Comment by Witherking25** [comment]
I only do it once per session now, but yeah I guess I can just deal with that specific call
