### ISSUE TITLE
Feature Request: Rich Presence on User Pages

### ISSUE THREAD

**Issue by Keltron3030** [RetroAchievements/RAWeb#228]
It would be nice if we could go to a user's page and see their Rich Presence displayed above their "last 5 games played" section.

**Comment by luchaos** [comment]
added in https://github.com/RetroAchievements/RAWeb/commit/73fefab8bdbf64db424d6bb450499c26d91007fc

**Comment by Keltron3030** [comment]
Works great now, thanks
