### ISSUE TITLE
Change front page statistics to games with achievements, not just game entires

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAWeb#229]
On the front page Statistics (on the sidebar)

![image](https://user-images.githubusercontent.com/32706333/46263658-28685280-c4cf-11e8-8970-f8660c00580d.png)
 This link shows the number of game entries we have, not the number of actual games with achievements, which is misleading.

Changing it to only show entries with achievements in core, should fix this, and I believe it would be a very simple fix.

I believe the number should be around 2000. not 12000.

**Comment by luchaos** [comment]
None of those counters are accurate ;)
Registered users includes duplicates, unlocked achievements counts hardcore twice, achievements includes inofficial and games includes non-achievement games.
Theoretically, as the counters are only incremented, never decremented.
We'll have accurate counters there.

**Comment by ScottFromDerby** [comment]
Hey, anyone who says those numbers are inflated are just being mean :P
Can you blame me though? RA had just started, I wasn't going to put extra work into making it seem like there were fewer games/achievements :P

**Comment by luchaos** [comment]
no worries, there still is _plenty_ of data to be counted there

**Comment by meleu** [comment]
After looking at the SQL query that gets that data, I think the number of registered achievements is also counting the Unofficial ones.

Maybe adding a `WHERE ach.Flags=3` [in this SQL query](https://github.com/RetroAchievements/RAWeb/blob/db238c11d0d43c6f34101275be13615bebd5bba3/lib/database/utility.php#L565) can produce more accurate results.
