### ISSUE TITLE
Back button link leads to an invalid URL when editing a forum post

### ISSUE THREAD

**Issue by monkey-bug** [RetroAchievements/RAWeb#2291]
**Expected behavior**
For the link to go back to the post being edited.

**Screenshots**
![image](https://github.com/RetroAchievements/RAWeb/assets/136386334/2497dbb6-003f-4525-be67-f22ea532dd9d)

**Culprit**
https://github.com/RetroAchievements/RAWeb/blob/560f6136ed14f0d2451ff7cf0fe9cdcd60462cab/resources/views/pages-legacy/editpost.blade.php#L89

**Comment by wescopeland** [comment]
Thanks for reporting.

As of latest `master`, this button has been removed from the UI. For reference, the change occurred in https://github.com/RetroAchievements/RAWeb/pull/2247.
