### ISSUE TITLE
Facebook Integration broken

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAWeb#23]
I don't know the details but I know it's not working.

**Comment by luchaos** [comment]
for reference http://retroachievements.org/viewtopic.php?t=4249

**Comment by ViperZang** [comment]
Just noting that it gives an error now and should probably just be removed all together since it didn't even work when you were able to link Facebook
![image](https://user-images.githubusercontent.com/31069034/132927111-8c25b624-e499-4120-9018-af02639a2434.png)

**Comment by Sanaki** [comment]
Honestly, I'm not sure Facebook provides us any real benefit anyway.
