### ISSUE TITLE
Game Page Does Not Update text in progress widget

### ISSUE THREAD

**Issue by pinguupinguu** [RetroAchievements/RAWeb#2312]
**Describe the bug**
Game page doesn't update the "Mastered" widget if badge was previously earned, but you only have a fraction of the total amount of achievements. 

**To Reproduce**
1. Go to a game page that had a previous mastery
2. After revision, the bug *should* occur.

Game page used: https://retroachievements.org/game/6688 
**Expected behavior**
Text on sidebar:
"Mastered"
"X out of Y achievements earned", where x != y

**Screenshots**
![chrome_oYtnJDaEuk](https://github.com/RetroAchievements/RAWeb/assets/65916635/6374bcd2-97c6-4a81-a78d-0d893a26a207)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome 123.0.6312.59

**Comment by wescopeland** [comment]
Hi @pinguupinguu,

This is functioning as designed. After a revision, you haven't lost your mastery. We don't want to imply to users that masteries are taken away from them after revisions occur.
