### ISSUE TITLE
Switch to full content hashing for NES

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAWeb#234]
Background: `RANes` only sends part of the ROM, known as PRG ROM, to `RAIntegration`. This data excludes the header, and some trailing data (if it exists), known as CHR ROM (or VROM). This is inconsistent with other systems, making identifying titles based on their hash difficult when using third-party tools, as well as authentication without a header available to provide the number of PRG ROM blocks in a given file.
See: https://github.com/RetroAchievements/RAIntegration/issues/77

Requirements/issues to consider:

- Tooling for: 
  - [ ] Automatically adding full content hashes to the database for all titles
  - [ ] Automatically deprecating/removing legacy hashes
- Client updates:
  - [ ] RANes
  - [ ] RALibretro
- Communicating changes to:
  - [ ] Users
  - [ ] Third-party clients
- [ ] Timeline and process for deprecating legacy hashes

For the record, not deprecating legacy hashes makes the following processes more difficult (off the top of my head):
- Identifying versions and regions in bug reports
- Identifying incorrectly linked files
- Testing different versions and regions

The database needs some clean-up anyway, so it is an opportunity to kill two birds with one stone.

**Comment by meleu** [comment]
looks like it was solved in https://github.com/RetroAchievements/RAEmus/pull/14
feel free to reopen if I'm wrong.
