### ISSUE TITLE
When editing forum posts, screws up apostrophes and ampersands

### ISSUE THREAD

**Issue by PopovMark** [RetroAchievements/RAWeb#2343]
![изображение](https://github.com/RetroAchievements/RAWeb/assets/36122849/cd3e2fd6-e1e0-4fcb-96a2-992a9e75c420)

Apostrophes get changed to "&#039;", that one ampersand got changed to "&amp;amp;". They will appear exactly like that if I save them, then trying to edit them again will change the existing apostrophes into that sequence again. Please fix.

Firefox, Windows 10

**Comment by wescopeland** [comment]
Resolved by https://github.com/RetroAchievements/RAWeb/pull/2317.
