### ISSUE TITLE
"Create Forum Topic" is missing.

### ISSUE THREAD

**Issue by redwizard42** [RetroAchievements/RAWeb#2349]
Go to a game page without a forum topic.
"Create New Forum Topic" is missing.

There is a "Make Primary Claim and new Forum Topic" in the dev panel.

CRs need to be able to just make a forum topic for Jrs to be able to claim.

Current Workaround: Make the claim+topic, then drop claim.

**Comment by wescopeland** [comment]
Thanks for reporting. This is a side effect of some user roles/perms changes that went out with 6.3. I'll investigate.
