### ISSUE TITLE
Inconsistent license

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAWeb#235]
The website displays a Creative Commons logo linking to [this page](https://creativecommons.org/licenses/by-nc-sa/2.0/uk/), while the repository is licensed as GPL version 3.

Related commit: https://github.com/RetroAchievements/RAWeb/commit/5faf5fcef9d9d5320f32b9a09a83191632690bee

If this is an intended relicense by @ScottFromDerby, the graphics and text on the website need to be updated. As it stands, I'm not sure that the GPL terms can be legally enforced.

**Comment by meleu** [comment]
@Formedras vulnerable to what?

**Comment by Formedras** [comment]
It should be obvious from rzumer's description of the issue.
But since you don't get it: it's vulnerable to being used by bad actors, in closed-source projects or clones, with RA having no legal recourse.

**Comment by ScottFromDerby** [comment]
What legal recourse would we have available? RA is a zero profit. I don't have time/money to pursue legal action in any capacity. I completely agree with ensuring the site and contents are properly licensed, GPL sounds fine to me. Must the site display a GPL license, or is it ok to just *not* have the cc license displayed? The cc license I added in 2012 I think, it doesn't need to remain there.

**Comment by luchaos** [comment]
> The cc license I added in 2012 I think, it doesn't need to remain there.

That would fall in line with v2 - let's remove it? GPL for v1 sounds good to me.

**Comment by meleu** [comment]
since it will not be an issue in v2, I'm going to close this here.

**Comment by rzumer** [comment]
Please don't close issues until they are actually fixed.
