### ISSUE TITLE
No unlock rate shown in Pokémon Blue 

### ISSUE THREAD

**Issue by gboquizosanchez** [RetroAchievements/RAWeb#2362]
In https://retroachievements.org/game/22854 I don't know why, unlock rate in game main page is not shown. If you enter in a certain achievement, you can see the rate of it.

![image](https://github.com/RetroAchievements/RAWeb/assets/20032391/d5900bc5-b66d-49ae-891e-097c38c7fefe)

![image](https://github.com/RetroAchievements/RAWeb/assets/20032391/fa6f261c-e73f-48af-ab30-145f3874a881)

**Comment by wescopeland** [comment]
I suspect this may have been caused by the recent regression in `getParentGameFromGameTitle()` introduced in V6.3. That function is called by an async job which runs in a background queue. I am going to investigate further to confirm this is the root cause, though.

**Comment by wescopeland** [comment]
This line of code is the root cause:
```php
$numDistinctPlayersSelector = $parentGame?->players_total ?? getGameData($gameID)['players_total'];
```

`$parentGame` exists, but its player count is 0 because it doesn't have any published achievements.
