### ISSUE TITLE
Access denied for user 'retroachievements'

### ISSUE THREAD

**Issue by WedgeSparda** [RetroAchievements/RAWeb#2368]
**Describe the bug**
When following the steps described on the documentation in order to set the local dev environment. When running command `sail artisan migrate` I get the error

```
  SQLSTATE[HY000] [1045] Access denied for user 'retroachievements'@'172.18.0.7' (using password: YES) (Connection: mysql, SQL: select table_name as `name`, (data_length + index_length) as `size`, table_comment as `comment`, engine as `engine`, table_collation as `collation` from information_schema.tables where table_schema = 'retroachievements' and table_type in ('BASE TABLE', 'SYSTEM VERSIONED') order by table_name)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:829
    825▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    826▕                 );
    827▕             }
    828▕ 
  ➜ 829▕             throw new QueryException(
    830▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    831▕             );
    832▕         }
    833▕     }

      +36 vendor frames 
```
The same connection error happens whrn entering the local PHPMyAdmin service at `http://localhost:64080`

**Expected behavior**
No connection error should occur since I'm using the default user

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**

**Comment by wescopeland** [comment]
@WedgeSparda Can you confirm this is still happening with the latest code?

**Comment by WedgeSparda** [comment]
@wescopeland Same error :(

**Comment by Jamiras** [comment]
How are you setting up your development environment? Are you using docker containers or xampp?

If you run `SHOW GRANTS` in your database, you should have a line like this:
```
| GRANT ALL PRIVILEGES ON `retroachievements-web`.* TO `retroachievements`@`%`  |
```

It sounds like you don't, or it's too restrictive. I'm a bit suspicious that your error isn't reporting localhost/127.0.0.1 for the address.

**Comment by WedgeSparda** [comment]
I'm using Docker containers on macOS 

I just deleted the previous images and pulled the latest ones again and is working. 

Could it be the cause an error on the image update?

**Comment by WedgeSparda** [comment]
I'm going to close this since deleting and pulling the docker images again fixed the issue
