### ISSUE TITLE
Add ability to change username?

### ISSUE THREAD

**Issue by WoodenKnees** [RetroAchievements/RAWeb#2371]
It's now 2024 and no way to change our Username. However, it is a feature that should be basic.

### Discussed in https://github.com/RetroAchievements/RAWeb/discussions/792

<div type='discussions-op-text'>

<sup>Originally posted by **ahstro** March 14, 2020</sup>
Would be a nice feature to have 😊</div>

**Comment by wescopeland** [comment]
There is a Github Discussion for this where it's clearly stated work is underway to develop this feature.

It is not necessary to open a duplicate issue.
