### ISSUE TITLE
Screwed up ">" signs when editing forum posts

### ISSUE THREAD

**Issue by PopovMark** [RetroAchievements/RAWeb#2378]
Same thing as #2343.
Changes this symbol to 

&
g
t
; 

when you hit Edit. Spaced it with line breaks because it's shown as the "greater than" symbol otherwise.

**Comment by wescopeland** [comment]
Rather than continuing to band-aid this, I'm going to migrate the page out of _pages-legacy_.

**Comment by Alfex3** [comment]
Now, when writing a comment, it makes the text after the < symbol disappear. I found out when I looked at tickets for which I provided a fix and comments were cut where that simbol was. I think it's treated like an HTML tag.

**Comment by wescopeland** [comment]
https://github.com/RetroAchievements/RAWeb/pull/2421
