### ISSUE TITLE
0 games shown under consoles

### ISSUE THREAD

**Issue by echofoxmetal** [RetroAchievements/RAWeb#2379]
0 games shown under consoles when there are definitely games with achievements

I’m not sure what the problem could be (data array)
What could be the potential problem?

**Comment by wescopeland** [comment]
We have an issue template which asks to provide a way for us to reproduce the issue.

In the interest of time, please provide a URL for us to reproduce this. Otherwise, we are unable to help and I will be forced to close this issue.
