### ISSUE TITLE
Additional column in Achievement Distribution graph for small sets

### ISSUE THREAD

**Issue by Mindhral** [RetroAchievements/RAWeb#2396]
**Describe the bug**
For any set with less than 44 achievements, the column which should be the last is empty, and an additional one is added with its data.

**To Reproduce**
1. Go to [Slender: The 8 Pages ~ Homebrew ](https://retroachievements.org/game/24124) for example, which has 9 achievements
2. Look at the distribution graph: it has 10 columns instead of 9. The 9th is empty and the 10th has the data for 9.
3. The hidden table below with textual data (which I assume is for accessibility purpose) has the same problem.

**Expected behavior**
In the case of the example, 9 columns, by removing the current number 9.

**Screenshots**
![image](https://github.com/RetroAchievements/RAWeb/assets/148589639/9765a756-437b-490a-adba-406cbf7640f6)

**Additional context**
The cause seems to be in https://github.com/RetroAchievements/RAWeb/blob/b0ce38383b62ad04c629654958b9a1e0fb13a163/app/Helpers/render/game.php#L296
If the achievements count is above `DYNAMIC_BUCKETING_THRESHOLD` (44), it creates one less bucket than wanted, as `handleAllAchievementsCase()` is expected to create and fill the last one. But when it is bellow that threshold, is already creates as many buckets as there as achievements. The last one is never filled, and a new one is added with its data.

Replacing `$numAchievements` by `$numAchievements - 1` in the following line should be one way to fix the issue:
https://github.com/RetroAchievements/RAWeb/blob/b0ce38383b62ad04c629654958b9a1e0fb13a163/app/Helpers/render/game.php#L308

**Comment by wescopeland** [comment]
Thanks, you're correct about the root cause. I've tested the solution and opened a PR to remediate the issue.
