### ISSUE TITLE
RA cheevo Hint/Tip

### ISSUE THREAD

**Issue by coolscribble** [RetroAchievements/RAWeb#241]
I was thinking when I couldn't sleep, that would be good to make something like faq/wiki/on page hints
not exactly how to win the game, but something to help you
there could be 2 types:

1. game hint which will tell you how to get more lives etc

2. cheevo hints which will be like:
                                 To defeat Bebop in TMNT without getting hit **EXACTLY** when he shows, jump over him and beat him with Donattelo

It can be button "spoiler" like when you click him, it will show you the hint but not every time

Or NES Orchestra hint could be:
start with '->'

I hope you know what I mean, I'll make a picture if I didn't forget how I see it

**Comment by coolscribble** [comment]
![screenshot_2018-10-27 slaughtered boar in teenage mutant ninja turtles nes](https://user-images.githubusercontent.com/43485409/47603537-646ad680-d9ed-11e8-83b3-ac2f7764d149.png)

**Comment by meleu** [comment]
It would be a neat cosmetic, but IMO the "Embedded video URL" and the comments are enough for devs/users to share such hints. And that's what they usually do. If images are needed, users can post imgur links or something.

**Comment by coolscribble** [comment]
Personally, I would love more this written hints without video walkthrough
I would even make many of those hints myself :D it could be even on the earlier mentioned wiki

I really like FAQs but they are too long and it's kind of hard to find exactly what you want because cheevos are different
Maybe it'll even fix some of the cheaters IMO 
if it could be in wiki, I'll highly appreciate it tho

I would make it like: everyone could add the hint and if 3 people give it thumb up, it will be official
(or if dev will agree with it/make the hint)

But it's up to you, it was just an idea

**Comment by kdecks** [comment]
You can already do this effectively through the game comments, and I've seen it done many times.
