### ISSUE TITLE
Site Feed: Multiple Completed Messages

### ISSUE THREAD

**Issue by CoolCanuck** [RetroAchievements/RAWeb#243]
![image](https://user-images.githubusercontent.com/15615155/47829324-425eb480-dd5d-11e8-954b-7ea141ea2bfe.png)

In rare and seemingly unknown cases, multiple "completed" entries may appear in the site feed. 

In the above example, they are all the same game ID.

**Comment by Jamiras** [comment]
It looks like he had three achievements trigger at the same time, completing the set. There's probably a timing issue where they all think they're the one that completed the set.

**Comment by kdecks** [comment]
With the site feed disabled this is irrelevant.
