### ISSUE TITLE
Enhancement for Dev Stats page: Sort by Ticket Ratio %

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAWeb#244]
As suggested by @Keltron3030 in #88 for the [developer stats](http://retroachievements.org/developerstats.php) page:

As a developer and admin, I aim to easily see which developers are having the most issues (tickets), per achievement made. Adding a _sortable_ metric on the [developer stats page](http://retroachievements.org/developerstats.php) that shows **ticket ratio %**. This would accomplish that aim and make it readily apparent.

This would be done by: (Number of tickets) / (Achievements), rounded up to the nearest 0.1%.

Ex: 
Pereira006 would have ticket ratio of a 8.4%.
dude1286: 11.3%
Altomar: 0.4%

Here's how I imagine it would look: 
![image](https://user-images.githubusercontent.com/32706333/48095026-e66ab480-e1d0-11e8-9183-ba5c2e085dcc.png)

It's assumed that this should be a rather easy change to make.

((Also.. I'm not sure which is more correct "ticket ratio percent" or "ticket percent ratio" or neither.. something like this anyway.😅))

**Comment by Keltron3030** [comment]
Thanks, if the "%" is shown next to each value you can just display "ticket ratio" as the column header.

**Comment by ScottFromDerby** [comment]
Love this - would like to prioritise it

**Comment by Keltron3030** [comment]
@meleu the boss has spoken. :)  Difficult to also add an active flag column.  Would be good to see this stat paired with active in the last 6 months.  this way we can light a fire under those devs that are still active and able to fix their own sets.  Does the table support filtering by two columns, for example sort by activity flag then sort by ticket percent?

**Comment by meleu** [comment]
!meme
**"Keltron is the new rabbid :sweatsonic:"** - *unknown*

**Comment by Keltron3030** [comment]
Well done.... Bring out the lunch mob
http://retroachievements.org/developerstats.php?t=4
