### ISSUE TITLE
New Feature: Ticket Inbox for login box (div.login)

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAWeb#246]
As an admin I hope that developers will resolve all their tickets quickly. Adding more a visible, even slightly annoying, notice to developer could serve as a constant reminder and incentivize developers to resolve them.

Here's a concept mock-up:
![image](https://user-images.githubusercontent.com/32706333/48170927-ecd35c00-e2b6-11e8-9b3c-b6255dbd0d1c.png)

The **Open Tickets (X)** would only appear if the user or developer has more than 0 tickets. The value X would be the same value already calculated on user pages.
![image](https://user-images.githubusercontent.com/32706333/48171626-104bd600-e2ba-11e8-865d-b0fd9f12dc04.png)

Just like on the User Page, clicking on this link would link to 

> `https://retroachievements.org/ticketmanager.php?u=[user.self]`

It's important for this to only show up if the user/dev has >= 1 ticket, as there are users that have tickets, but we don't want every non-dev user with tickets to see "Open Tickets: 0"

------------------
Here's 2 more mockups
![image](https://user-images.githubusercontent.com/32706333/48171294-90713c00-e2b8-11e8-8c9f-43969b25733d.png)
![image](https://user-images.githubusercontent.com/32706333/48171365-da5a2200-e2b8-11e8-941c-1eecd3d03c5b.png)
using ticket emoji: 🎫.

**Comment by meleu** [comment]
Oh, yeah! I had this idea before and completely forgot.
Looks easy to implement. I'm going to take a look at it tomorrow.

**Comment by meleu** [comment]
solved in 593afc161e39284f494ce76f741d535a126ee1ee

**Comment by kdecks** [comment]
I"m getting a display bug: 
![image](https://user-images.githubusercontent.com/32706333/48224930-9b7ba900-e358-11e8-859d-064fcaf257e5.png)
zoom is 100%

**Comment by meleu** [comment]
I'll change it to just `Tickets`, it's enough to mean "Open Tickets" and will solve that.

Only tomorrow though.

**Comment by meleu** [comment]
solved in e2064a1e29b9998ebf0a714c981d3295c4a9ecf8
