### ISSUE TITLE
User Recent Posts Isn't redirecting to the next 25 oldest posts

### ISSUE THREAD

**Issue by Soulsderfuchs** [RetroAchievements/RAWeb#2491]
**Describe the bug**
When you go into any user page and want to look at their forum post history ex: https://retroachievements.org/user/Soulsderfuchs/posts 
The first 25 results show as expected but when you click next 25 expecting the next page of said users messages it goes to a general forum post list unrelated to the user. 
https://retroachievements.org/forums/recent-posts?offset=25

**To Reproduce**
1. Go to any profile page and click their forum post history page
2. Scroll down and click on next 25
3. See error

**Expected behavior**
See the next 25 oldest post list of the users forum posts.

**Screenshots**
![chrome_qaQ69keUgp](https://github.com/RetroAchievements/RAWeb/assets/59575350/f19f7caa-a4e3-46cb-8956-8f32736a03a2)
![chrome_9V5GRwZftE](https://github.com/RetroAchievements/RAWeb/assets/59575350/35f75ba4-2cf8-461e-9351-4af828d9f191)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser: Chrome
 - Version: 125.0.6422.142 (Official Build) (64-bit)

**Comment by wescopeland** [comment]
Resolved by https://github.com/RetroAchievements/RAWeb/pull/2479.

**Comment by wescopeland** [comment]
Thanks for reporting! This one was easy to miss.
