### ISSUE TITLE
Ticket Resolution Credit

### ISSUE THREAD

**Issue by Keltron3030** [RetroAchievements/RAWeb#250]
As a developer with an interest in site quality and those who contribute to that goal; I would like to see a developer stat for tickets resolved.  

The formula would exclude those tickets in which the developer is the resolver.  This way resolution credit is only given to those who help to improve the site by resolving tickets which are not their own.

I think this stat should be listed as an additional column on the developer stats table and on the developer's user page as a motivator to resolve tickets and improve overall site quality.

Current:
![Screenshot_20191103-004757](https://user-images.githubusercontent.com/42773860/68080526-bbab4000-fdd3-11e9-9cd0-c5928938a003.png)

**Comment by kdecks** [comment]
hear, hear

**Comment by Keltron3030** [comment]
If this feature ever becomes a reality there will probably need to be some follow up considerations.  Tickets opened and closed by the same user will need to be monitored for abuse. Tickets closed and reopened, should give credit to the last resolver.  The assumption being if you want  to resolve a ticket you must not only address the achievement ticket at hand but also ensure future tickets will not be needed.  For example, a does not trigger "fix" resulting in a "triggers" at the wrong time ticket is not a good thing.

**Comment by meleu** [comment]
> Tickets opened and closed by the same user will need to be monitored for abuse.

abuse what? monitored by whom? is this supposed to be some kind of competition? do we need to keep an eye if people are cheating here too?

I initially thought in such feature as a mere cosmetic to do some kind of "ego massage" to those who help to increase the project's quality, but if it brings more workload for admins/mods/staff... I'm not that eager to implement such feature.

**Comment by Keltron3030** [comment]
Oh, no not really.  I was only thinking that someone could open and close their own tickets which in most cases would be totally acceptable as a dev may find an error in another's achievement and want to do a ticket and then resolve later. 

I think this point is really a non issue and should be disregarded.

**Comment by kdecks** [comment]
I share that sentiment about wanting to avoid creating oversight workload.

Now I'll soapbox about chasing stats:
>Any attempt for a developer to try to game any developer stat for their ego or reputation is a fool. Numbers often lie, and such behavior is looked down upon. If someone is trying to gain **points** or **reputation** at the expense of quality or brevity, well the rest of us are not idiots. We can see through it.
>
>Many are motivated to compete, especially in a gaming site, but numbers are only an indirect indication of success and contribution. The most successful developers are those who make achievements of quality, and that are most enjoyed by the community for their various challenge, creativity, and aesthetic designs. That's not something you can easily quantify.

**Comment by Keltron3030** [comment]
Totally agree with everything said my both of you.

**Comment by Keltron3030** [comment]
This was more or less addressed by #436 Thanks again @MrOwnership
