### ISSUE TITLE
Automatic email for new tickets 

### ISSUE THREAD

**Issue by Keltron3030** [RetroAchievements/RAWeb#251]
As a developer who may have worked on achievements I haven't created; I would like to receive an email if a ticket was submitted for an achievement where I was the last user to edit said achievement.  Perhaps the easiest way to implement this would just be for the server to send an email when a ticket is opened for an achievement which you've ever commented on.

**Comment by meleu** [comment]
It seems solved once #349 was merged.
Feel free to reopen if I'm wrong.
