### ISSUE TITLE
prevent "1 day" accounts from submit tickets

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAWeb#258]
Add a logic in [SubmitNewTickets()](https://github.com/RetroAchievements/RAWeb/blob/8b606b0d55237cf3d365bafe568e062f2f419ee5/lib/database/tickets.php#L88) preventing recently created accounts from submitting tickets.

The `MemberSince` info can be obtained via [getUserActivityRange()](https://github.com/RetroAchievements/RAWeb/blob/66eec6171a9d982cb61b5053ecd8b7dc54e2873b/lib/database/user.php#L1166).

[update based on Jamiras suggestion below]
Check also if the account played something. The `LastGameID` can be obtained via [getAccountDetails()](https://github.com/RetroAchievements/RAWeb/blob/e4b59ca20877a64af9c226fd95bbd698bc508212/lib/database/user.php#L687).

**Comment by Jamiras** [comment]
Should probably also have a clause that they have logged into at least one game. I believe RetroArch still submits the "Started Playing" notification, even if it doesn't do Rich Presence yet.
