### ISSUE TITLE
Bitwise XOR doesn't appear in achievement logic on website

### ISSUE THREAD

**Issue by tomojira** [RetroAchievements/RAWeb#2584]
**Describe the bug**
When bitwise XOR is used in achievement logic, the ^ operator and its comparison don't seem to appear on achievement pages on the website.

**To Reproduce**
1. Open a set with XOR logic in RALibretro, such as [After Burner (Master System)](https://retroachievements.org/game/10051)
2. Check a relevant achievement in the Achievement Editor, such as [Stage 1 Clear](https://retroachievements.org/achievement/420017)
3. Check the achievement's page on the website
4. Compare the logic

**Expected behavior**
The logic on the achievement page should appear to be identical to what is seen in the emulator, including XOR.

**Screenshots**
![RALibretro 2024 07 31 00 06 55](https://github.com/user-attachments/assets/75b795e1-20a4-43d6-96ff-5043d2f9ef3b)
![firefox 2024 07 31 00 07 15](https://github.com/user-attachments/assets/44d7e263-a23a-4fc5-884c-1d14d3ec8a6f)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 128.0.3

**Comment by Jamiras** [comment]
This was included in #2567: https://github.com/RetroAchievements/RAWeb/pull/2567/files#diff-86af13e178e26184ad49c70e9eac99162754ac242a6aa370bda64f7b8d9adcbcR189
![image](https://github.com/user-attachments/assets/6146205b-35d8-4bbf-853c-1961b0cfe2b8)
