### ISSUE TITLE
Dropdown for performing an action on a ticket no longer appearing

### ISSUE THREAD

**Issue by cIymax** [RetroAchievements/RAWeb#2585]
**Describe the bug**
The dropdown for performing an action on a ticket just recently stopped appearing for me.  Roughly a week or two ago things were still working fine.

**To Reproduce**
After getting a ticket, the dropdown won't appear, even after you comment on the ticket.

**Expected behavior**
See #2542, although it may not be the same issue.

**Screenshots**
![ticket_reassign](https://github.com/user-attachments/assets/35eb9ff7-f93c-4bc4-90f7-c2cc401d7ab6)

**Desktop**
 - Win10
 - Chrome

**Comment by Jamiras** [comment]
That's a restriction of being a Junior Developer. Junior Developers are expected to have their tickets reviewed just like their sets. It ensures they're not just closing stuff without due diligence, and provides the same sort of oversight to any fixes as would be applied to newly created achievements.
