### ISSUE TITLE
Site Menu typo?

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAWeb#26]
![image](https://user-images.githubusercontent.com/32706333/36223456-af700270-1181-11e8-9243-6bf76e63d4a5.png)

**Comment by GameDragon2k** [comment]
This is actually intentional.

Competitions is a subforum of the Community forum.
You can think of it like this:
```
Community
⤷ Competitions
```

**Comment by kdecks** [comment]
Makes sense. 

Closing.
