### ISSUE TITLE
Add a small message informing users to refresh their cache after uploading a user pic

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAWeb#262]
This is one of the most common problems users have, as needing to reset the cache is unusual. 

![image](https://user-images.githubusercontent.com/32706333/51086623-e2de3700-1705-11e9-9269-b4ab1a694676.png)

> After uploading, press Ctrl + F5. This refreshes your browser cache making the image visible.

Adding this message or something similar should help reduce the confusion significantly.

**Comment by televandalist** [comment]
Beat me to it.
