### ISSUE TITLE
Followed User Rankings says 1 points instead of 1 point

### ISSUE THREAD

**Issue by GenericMadScientist** [RetroAchievements/RAWeb#2625]
**Describe the bug**
Anyone in Followed Users Rankings who got exactly 1 point in the selected span of time has '1 points' instead of '1 point'.

**To Reproduce**
1. Follow someone who got exactly 1 point today or this week (can be yourself).
2. Go to your profile page.
3. Go to the Followed Users Rankings table and select the appropriate time span.

**Expected behavior**
It should say 1 point, no plural.

**Screenshots**
![1-points](https://github.com/user-attachments/assets/83f01476-98da-4f57-931f-cf7a1ffc7040)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 129.0.1

**Comment by wescopeland** [comment]
Thanks for reporting, will be resolved by https://github.com/RetroAchievements/RAWeb/pull/2626.
