### ISSUE TITLE
Mastered set with demoted achievement updated Mastery Date

### ISSUE THREAD

**Issue by PJM-dev** [RetroAchievements/RAWeb#2628]
**Describe the bug**
A set I mastered in April now says I mastered in July (around the time of achievement demotion)

**To Reproduce**
1. Go to PaddyShade's N64 mastery list (https://retroachievements.org/user/PaddyShade/progress?filter%5Bsystem%5D=2)
2. See Ocarina of Time at the top (mastered July 30 2024)
3. The final achievements earned for this mastery was on April 5 2024, 5:17pm (Dark Lord /Blind Explorer)
4. This achievement was demoted July 27 2024 - https://retroachievements.org/achievement/48256

**Expected behavior**
Mastery date should not be updated because of a demotion

**Screenshots**
![image](https://github.com/user-attachments/assets/22974e72-bc97-464f-bbeb-fbeaf061418a)
![image](https://github.com/user-attachments/assets/b44196f2-d5ac-4915-9a33-a05d70d0baf6)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version 127.0.6533.120 (Official Build) (64-bit)

**Additional context**

**Comment by wescopeland** [comment]
To the best of my knowledge, the Completion Progress page itself doesn't show a mastery date.

When I hover over the game while viewing your profile, I see the correct mastery date which occurred in April.

![Screenshot 2024-08-21 at 3 02 08 PM](https://github.com/user-attachments/assets/ad201373-c18f-4334-aaf5-6e5a429a05a3)

**Comment by PJM-dev** [comment]
Ah gotcha, I thought the date on that page was mastered, but it looks like it's the date of the last achievement earned, which was this one which was re-promoted on July 30th:
![image](https://github.com/user-attachments/assets/f48825aa-5954-4396-bd63-9ac1f12edc0f)

I guess that would be expected if this one got re-promoted, but it does seem a bit unintuitive.

**Comment by wescopeland** [comment]
Hi @PJM-dev!

For the time being I'm thinking it may be best to close this issue, as it appears there isn't an active data issue or back-end logic error. However, please feel free to open something in our discussions section in this GitHub if you have ideas for how we can improve this UX to make it less ambiguous 🙂
