### ISSUE TITLE
Issue: Forum URL doesn't show link text

### ISSUE THREAD

**Issue by SporyTike** [RetroAchievements/RAWeb#264]
While editing a forum post and added some links with custom url links using the 'url' feature I noticed that it seems to have an issue. If you create two links in the same textparagraph (so don't you Return) both urls have issues. 

**Example code:**
`[url=https://retroachievements.org]test[/url] [url=https://retroachievements.org]test[/url]`

**Example shown in the forum after saving:**
`https://retroachievements.org ]test[/url] test [url=https://retroachievements.org'>test`

**Example should shown in the forum after saving:**
`test test`

Both links aren't shown like they should. The first link is _https://retroachievements.org_ but it doesn't lead somewhere and the second link is the _test_ between [/url] and [url=... and works fine.

I read kdecks already submitted this issue and meleu closed it because it was fixed but it seems the issue is still there.

**Comment by meleu** [comment]
Note to self:
Improve the regex in [this line of code](https://github.com/RetroAchievements/RAWeb/blob/66eec6171a9d982cb61b5053ecd8b7dc54e2873b/lib/dynrender.php#L2810) making it handle multiple `[url]` tags in the same line.

**Comment by meleu** [comment]
fixed in #266
