### ISSUE TITLE
Issue: Add Game IDs on game pages doesn't work

### ISSUE THREAD

**Issue by SporyTike** [RetroAchievements/RAWeb#265]
While making a set for `LEGO Star Wars II - The Original Trilogy` I tried to add the games `LEGO Star Wars` and `LEGO Island 2 - The Bricksters Revenge` to the similar games section. I noticed that for some unknown reason I can't add this three titles to each other. I can press the Add button and the url changes to `?e=ok` but the games aren't shown. So for testing I tried to add Super Mario World and it worked fine but still not the LEGO games.

- [LEGO Star Wars](https://retroachievements.org/game/5719)
- [LEGO Star Wars II - The Original Trilogy](https://retroachievements.org/game/5720)
- [LEGO Island 2 - The Bricksters Revenge](https://retroachievements.org/game/6393)

**Comment by rzumer** [comment]
Same issue with linking 13682 to 13855's page but not vice versa.

**Comment by televandalist** [comment]
I've noticed with the hubs, sometimes a game won't show up on the hub page's similar games, but the hub will show up on the game's page. It's really odd. An example would be this: https://retroachievements.org/game/245 - It shows the Cyberpunk and Cinematic Platformer hubs in similar games, but the game does not show up on those pages.

**Comment by kdecks** [comment]
I think I remember someone saying the issue might have to do with entries that were merged. Not sure.

**Comment by luchaos** [comment]
Fixed in https://github.com/RetroAchievements/RAWeb/commit/cf7658331e307e88155668adb5d7057638926c0d
The query was optionally contraining results based on games' individual achievements status.
Rewriting it from a left join to a subselect to calculate the total points sum resolved it.
