### ISSUE TITLE
`guideURL` is always `null`

### ISSUE THREAD

**Issue by TapiocaFox** [RetroAchievements/RAWeb#2655]
**Describe the bug**
`guideURL` field is always `null` when we try to fetch game record information.

**To Reproduce**
Take a look at [getGameInfoAndUserProgress](https://api-docs.retroachievements.org/v1/get-game-info-and-user-progress.html) API.

**Expected behavior**
`GuideURL` field has some value led to game's guide.

**Access by (please complete the following information):**
 - Using `api-kotlin`

**Comment by wescopeland** [comment]
I am seeing this value populate when calling the endpoint directly:
```
GET .../API/API_GetGameInfoAndUserProgress.php?y=...&g=15020&u=WCopeland
```

![Screenshot 2024-08-31 at 3 33 58 PM](https://github.com/user-attachments/assets/0fb830bb-12b1-4996-b917-f8b0dd397ca6)

What happens if you try to query game 15020 with api-kotlin?

**Comment by TapiocaFox** [comment]
Yes. It is still `null`:

I used Daijishou Console `\ra show game 15020`. Got `guideUrl: null`. Maybe @official-wizard know what is going on?

```
[RetroAchievementsManager] refreshMyRetroAchievementsGameRecordByGameId
2024-08-31 17:27:44.404 12984-13036 daijishou_...ng_service com.magneticchen.daijishou           D  [RetroAchievementsManager] guideUrl: null
2024-08-31 17:27:44.425 12984-13036 daijishou_...ng_service com.magneticchen.daijishou           I  [💻 Daijishou Console] \ra show game 15020
                                                                                                    > RetroAchievementsGameRecordEntity(id=94, userId=magneticchen, gameId=15020, name=Defender, url=https://retroachievements.org/game/15020, imageUrl=https://retroachievements.org/Images/070479.png, consoleImageUrl=https://static.retroachievements.org/assets/images/system/arc.png, consoleName=Arcade, rating=null, ratingVotesCount=0, achievementsCount=38, unlockedAchievementsCount=0, lastUpdatedTimestamp=Sat Aug 31 17:27:44 EDT 2024)
```

**Comment by TapiocaFox** [comment]
Seems to be an API Kotlin Specific issue. Thanks for the help!
