### ISSUE TITLE
"Set Motto" cut off on controlpanel.php on mobile

### ISSUE THREAD

**Issue by clanofartisans** [RetroAchievements/RAWeb#2657]
**Describe the bug**
When the browser window is resized to about 600 pixels wide or smaller, the "Set Motto" button on a user's settings page gets cut off, making it a bit unintuitive to save your motto. This is especially problematic on portrait mode on mobile devices.

**To Reproduce**
1. Log in.
2. Resize window to 600px wide or smaller.
3. Fail to find the Set Motto button.

**Expected behavior**
The Set Motto button should be visible.

**Screenshots**
![image](https://github.com/user-attachments/assets/25d1c8c3-a018-4978-83f5-3457d103bbdb)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Only tested in Chrome
 - Version: n/a

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: n/a
 - Browser: Only tested in Chrome
 - Version: n/a

**Additional context**
A very quick fix would be to add `flex-wrap` to the div that contains the button, and `block` to the button itself, although there may be a better way to do it with the page layout RA uses.

**Comment by wescopeland** [comment]
Will be resolved by https://github.com/RetroAchievements/RAWeb/pull/2624.

**Comment by clanofartisans** [comment]
> Will be resolved by #2624.

Beautiful, thank you!
