### ISSUE TITLE
make removing leaderboard submissions an admin only role (v1)

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAWeb#267]
This is a security concern (as suggested by some recently); as in it may be possible that some devs abuse their authority here with no oversight. Admin will continue to log when they remove leaderboard entries and keep track of suspicious behavior.

**Comment by Tsearo** [comment]
This should be taken care of with an alternative approach in #557

**Comment by meleu** [comment]
indeed, closing this as something ~~solved~~ dealt with.
