### ISSUE TITLE
Rename SG-1000 to include Othello Multivision

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAWeb#272]
The Othello Multivision platform is supported and linked with SG-1000. It is a clone platform which is hardware compatible, so it should be fine to use the same entry for both, but for clarity I recommend renaming "SG-1000" to "SG-1000/Othello Multivision" in the database.

**Comment by meleu** [comment]
According to the https://segaretro.org/Othello_Multivision:

> The Othello Multivision (オセロマルチビジョン) is a licensed SG-1000 clone manufactured by Tsukuda Original.

Being it just a clone (TBF: I'm not sure if it's "just" a clone), do you think it needs to be publicized like that?

My reasoning is that we also don't publicize names like Genesis or Famicom...

I'm not very aware of the "sega retro" scene, but at a quick glance it seems that SG-1000 is clear enough.

**Comment by rzumer** [comment]
As far as I know the Multivision has "exclusive" titles that do not work on an SG-1000 while SG-1000 titles remain compatible on it, so it is not the same as a simple name change. I don't know much about it either though.

"Genesis" is included in the title in the Site Pages dropdown, but not in the database title, FYI.
