### ISSUE TITLE
userList is slow

### ISSUE THREAD

**Issue by ahstro** [RetroAchievements/RAWeb#274]
It currently takes a really long time (sometimes 10 seconds, sometimes 40) for me to load a `http://retroachievements.org/userList.php`-url. I'm not proficient in PHP, so I can't quite figure out why, but I'm assuming it has something to do with how the database is [used to populate `$userListData`](https://github.com/RetroAchievements/RAWeb/blob/develop/public/userList.php#L22). The relevant database lib function is [`getUserListByPerms`](https://github.com/RetroAchievements/RAWeb/blob/develop/lib/database/user.php#L1540). Wish there was more I could do to help :)

**Comment by meleu** [comment]
I have a strong feeling that it started when the Untracked feature was implemented and also that the my PR #126 contributed to it. Hopefully it will be better handled in v2 (with some help from the laravel framework).

**Comment by luchaos** [comment]
the queries for user listings are fairly performant - i don't see any slowdowns happening on the user listings at the moment. there might've been something else going on in the database/on the server at that time.

**Comment by ScottFromDerby** [comment]
I think it might be specifically a sort query:
http://retroachievements.org/userList.php?s=3&p=1
this particular URL takes a good 10 seconds

Might just be a case of a missing LIMIT() subclause? will check asap
