### ISSUE TITLE
Recent Progress chart shows days incorrectly

### ISSUE THREAD

**Issue by ahstro** [RetroAchievements/RAWeb#276]
So, this is happening. The point farthest to the right is `31/1` and the consecutive ones going up is `1/2`, `2/2`, and `02/02`.
![retroachievementswat](https://user-images.githubusercontent.com/3090888/52170062-60b0c380-2743-11e9-8fd4-4a1e98a760b8.png)

**Comment by Prism7** [comment]
This glitch is affecting me and a number of other users on Discord as well.

**Comment by luchaos** [comment]
Not sure how to reproduce this. Is this still an issue?

**Comment by ahstro** [comment]
Not seeing it myself anymore, but also don't have any recent progress. Can't speak for anyone else.

**Comment by wescopeland** [comment]
It appears no one is able to reproduce this anymore. I think it is fairly safe to conclude this is no longer an issue. In the event this is seen again, please feel free to reopen.
