### ISSUE TITLE
In `GetUserSummary`, `UserPic` returns the username without it's capital letters when the endpoint on the site is case sensitive.

### ISSUE THREAD

**Issue by NicoPlaysThings** [RetroAchievements/RAWeb#2769]
For example, lets take my username, NicoPlaysThings:

If the API call is made with u=nicoplaysthings, it looks like this:
![image](https://github.com/user-attachments/assets/fef5ce14-c547-4922-88ed-ef090d4e8d29)

If the API call is made with u=NicoPlaysThings, it looks like this:
![image](https://github.com/user-attachments/assets/0811b556-abe9-42f5-9fe4-bf33e26ada74)

**Comment by wescopeland** [comment]
Transferred to RAWeb

**Comment by G3mha** [comment]
I would like to start working on this one, sounds good @wescopeland ?

**Comment by wescopeland** [comment]
👍
