### ISSUE TITLE
Extend forum History

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAWeb#28]
Right now http://retroachievements.org/forumposthistory.php show 50 most recently changes in groups of 25.

Extend the history to 250 or infinite if possible.

**Comment by meleu** [comment]
Looking at the code it seems that Scott made it to be "infinite", but for some reason it doesn't work like that. Will try take a look at it today.

**Note to self:** check why [the condition in this line of code](https://github.com/RetroAchievements/RAWeb/blob/057cf6347fd50d3c629b5b8f92e4d9ef71de24e4/public/forumposthistory.php#L91) is preventing the `Next 25 >` link to be added. See also: [`lib/database/forum.php`](https://github.com/RetroAchievements/RAWeb/blob/71594911f967321eeb35ab43e4572f25f8450183/lib/database/forum.php#L505)
