### ISSUE TITLE
Creating "official forum topics" - Developer-only permission?

### ISSUE THREAD

**Issue by Flara-StarLite** [RetroAchievements/RAWeb#283]
I feel that creating “official forum topics” for game entries should be a Developer-only permission.

The first post of an official game topic is usually reserved for important information about that game (such as what versions of the rom are compatible, where to find a guide for missable achievements, etc.) As such, it’s helpful to the developer of a set if they are able to create the topic themselves, and are able to edit it anytime without the need to contact an admin.

By having this permission open to the general public, many "official game topics" are being created daily, often by non-developers who have no plans to work on the games.

**Comment by meleu** [comment]
agreed!

> By having this permission open to the general public, many "official game topics" are being created daily, often by non-developers who have no plans to work on the games.

or even worst: creating official topics for garbage entries.

**Comment by kdecks** [comment]
Stretch goal. Allowing devs to reassign owners of a forum topic.
