### ISSUE TITLE
Broken README link in `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by G3mha** [RetroAchievements/RAWeb#2855]
**Describe the bug**
In the `CONTRIBUTING.md` file, there is a broken link to the README. Specifically, in the "Testing, Code Style, and Static Analysis" section, there is a reference to "See the [README](https://github.com/RetroAchievements/RAWeb/issues/README.md)" which does not properly link to the README file since it's in a different directory.

**To Reproduce**
1. Go to 'CONTRIBUTING.md'
2. Scroll to the "Testing, Code Style, and Static Analysis" section
3. Click on the README link
4. See that the link is broken since it points to README.md in the current directory rather than the root directory

**Expected behavior**
The README link should point to the correct path, likely `../README.md` instead of `docs/README.md`, so that clicking it successfully navigates to the repository's README file.

**Screenshots**
N/A - Issue is visible in markdown source

**Desktop/Smartphone**
N/A - This is a documentation issue that affects all platforms equally

**Additional context**
This appears to be a simple path issue - the link needs to be updated to use the correct relative path from the docs directory to the root README.md file.
Suggested fix: Update the link from [README](README.md) to [README](../README.md)

**Comment by wescopeland** [comment]
https://github.com/RetroAchievements/RAWeb/commit/74cfe9182c774f298690ee1cd1ce431f98d3a8ca
