### ISSUE TITLE
leaderboard doesn't show up on game page if there aren't any winners

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RAWeb#294]
This game has four leaderboards: https://retroachievements.org/leaderboardList.php?g=9491
But none of them show on the game page: https://retroachievements.org/game/9491
![image](https://user-images.githubusercontent.com/32680403/56085022-e747e800-5df9-11e9-82fe-e2b1ac66a24a.png)

Leaderboards do show up on other game pages, along with the player in the top slot:
![image](https://user-images.githubusercontent.com/32680403/56085033-05154d00-5dfa-11e9-99d5-e08fad5a6109.png)

So, it's my guess that whatever is building the list requires a winner before the leaderboard will appear.

**Comment by Keltron3030** [comment]
Is this really a problem?
