### ISSUE TITLE
Hide earnings on Game Page

### ISSUE THREAD

**Issue by magusLOGS** [RetroAchievements/RAWeb#297]
A option to hide earnings on the Game Page via checkbox (temporary applies to current Game Page) and by default via Settings Menu (applies to all Game Pages) which can be turned on/off temporary for current Game Page.

- [x] Hide Hardcore earnings
- [x] Hide Softcore earnings

**Comment by SyrianBallaS** [comment]
If this is a per user setting, I think it's a good idea. I don't think it would be if it affected everyone at once.

**Comment by magusLOGS** [comment]
@SyrianBallaS only for current logged-in users (based on their earnings). It makes going for completions easier as the earned aren't displayed anymore, XboxAchievements and PSNTropies has something similar last time i've checked those Sites.
