### ISSUE TITLE
Notify the dev when there's a new comment on the page of an achievement they created

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAWeb#3]

**Comment by GameDragon2k** [comment]
Doesn't this happen already?

**Comment by meleu** [comment]
"A game wall discussion **YOU'VE COMMENTED IN** on RetroAchievements..."

It doesn't happen when someone add a comment on a page of an achievement that you created.

Example: I wasn't notified when the user ZBR added a comment on [this page](http://retroachievements.org/Achievement/55778) (an achievement I created).

**Comment by Jamiras** [comment]
I'd like to expand this to also include automatically notifying when a comment is added to the game wall associated any achievements you've created.

This could also be addressed by having the ability to subscribe/unsubscribe to any game/achievement as described in #5, but an achievement author should automatically be subscribed to the game/achievement when the achievement is uploaded.

**Comment by meleu** [comment]
I've noticed that what is being requested in the title is what Scott originally wanted to do, but due to [a wrong function call](https://github.com/RetroAchievements/RAWeb/pull/182/files#diff-295c69655390b9ab4408ceea39d90e70L502) it wasn't working.

This was implemented/fixed on PR #182. Closing this issue.
