### ISSUE TITLE
Site Search is (mostly) broken

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAWeb#304]
After the site crash on 31 March, site search has only partially worked.

You can still see suggested results, based on what you are typing, and selecting these goes where it should, but if you enter your search, no results are found.

What is missing is an extended list with multiple pages which showed forum threads, games, achievements and users.

**Comment by Krylan** [comment]
I wanted to take care of this issue, but after I checked the search on my localhost... it's fully working. The only thing I can think of is that there is a missmatch in databases. Function's query probably can't work with some change in the DB structure.

**Comment by luchaos** [comment]
it's been due to the move from mysql 5.7 to mysql 8.0
even though i tuned down the "strictness" by changing quite a few engine flags, it's still pickier than it used to be.
should be fixed now.
