### ISSUE TITLE
Game Topic Longplay URL Invalid

### ISSUE THREAD

**Issue by MrOwnership** [RetroAchievements/RAWeb#307]
The auto-generated URL for Longplay in each game topic forum post is invalid. It currently searches for www.longplays.org which no longer exists. I think it should be updated to search www.youtube.com with "longplay" appended to the generated URL.

Also the console is not being appended to the URL at all for either of the three generated URLs because
`$consoleName = $gameData['ConsoleName'];`
is missing in the file.

For example, this is generated URL for the current implementation:
https://www.google.com/search?q=site:www.longplays.org+Chuck+Rock+

I'd recommend we update it to:
https://www.google.com/search?q=site:www.youtube.com+Chuck+Rock+(Master+System)+longplay

I have completed the necessary update to implement this, I wanted to get some feedback before committing the change.

**Comment by meleu** [comment]
submit a PR so we can give you the feedback

**Comment by meleu** [comment]
solved in #312
