### ISSUE TITLE
Some users are unable to submit tickets through the web interface

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RAWeb#323]
There have been two users so far that have posted in #help-me that they get a "Sorry. There was an issue submitting your ticket" message when trying to create a ticket through the web interface. 

I suspect this was caused by the changes made for #258. The logic for determining if a player has played a game may be incorrect. Neither user shows any "Last seen in" message, indicating they play exclusively on RetroArch. Both are also relatively new players (accounts created within the last three months), so are likely on a recent version of RetroArch. It's possible that my assertion that

> I believe RetroArch still submits the "Started Playing" notification, even if it doesn't do Rich Presence yet.

may be wrong, or at least may no longer be true.

**Comment by meleu** [comment]
could you name the users having this issue so I can debug it more effectively?

**Comment by Jamiras** [comment]
I didn't know if it was appropriate to name them, but since they posted in #help-me, I guess its probably okay.

[Rata](http://retroachievements.org/user/Rata) 
![image](https://user-images.githubusercontent.com/32680403/60467428-dc8c3a80-9c13-11e9-9764-ec89ea66538a.png)

and [GrandMasterLynx](http://retroachievements.org/user/GrandMasterLynx)
![image](https://user-images.githubusercontent.com/32680403/60467461-f0d03780-9c13-11e9-910b-72acbad88194.png)
![image](https://user-images.githubusercontent.com/32680403/60467485-fcbbf980-9c13-11e9-92a1-80fa3fcc342e.png)

**Comment by Thoooreau** [comment]
Same to AngeloLeonhart yesterday when trying to do a ticket to this cheevo through the site: https://retroachievements.org/achievement/72196
