### ISSUE TITLE
Players are no long able to add game ratings

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAWeb#324]
![image](https://user-images.githubusercontent.com/32706333/60462861-ae086280-9c07-11e9-995a-99cbea48cf45.png)

The interface is frozen and does not accept new scores.

**Comment by meleu** [comment]
Probably related with my PR #302. :sweat: 

I'm gonna solve it soon.

Note to self: do not refactor code when several languages are used in the same file.

Also: script code should be on its own file.
