### ISSUE TITLE
Include user account type on user card (v1)

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAWeb#326]
When a user profile is hovered in the forum or in other parts of the site, the profile pic is enlarged, the amount of points are shown and in some parts of the site (not the forum) the user's motto is displayed.

![image](https://user-images.githubusercontent.com/32706333/61063019-801bde80-a3bc-11e9-9c74-b3cf15e13b7b.png)

I'm am referring to this as the "user card".

![image](https://user-images.githubusercontent.com/32706333/61062707-ed7b3f80-a3bb-11e9-8fb4-c92ea65c2adf.png)

The concept is to display the users account type, as in admin, developer, registered, etc, especially for the forum so that it will be more obvious to users who are moderators and developers.

This concept could be scrapped entirely unless someone likes the idea and wants to build it into v1.

**Comment by MrOwnership** [comment]
I started looking into this a little bit. I think it would be cool to expand on this and add a little more user details into the user card. I updated the code to display the following when you hover over a user icon. The information is all hard coded just to show the concept.

![](https://i.imgur.com/Jry8WEB.png)

Any thoughts on how much information we would want to be included in the user card?

**Comment by Blazekickn** [comment]
Last recorded rich presence would be nice. Its already displayed on your profile.

**Comment by Blazekickn** [comment]
Looks great by the way

**Comment by kdecks** [comment]
Very cool mock-up; all of it!

I think it might be good to instead of showing the last 5 sets mastered/completed to show the last 5 achievements earned. (I do not hold this strongly) Or possibly last 5 achievements earned AND last 5 awards. Would that be too much?

**Comment by meleu** [comment]
IMO the last awards and games mastered are unnecessary (last Login would be more useful, for example).

**Comment by meleu** [comment]
What this feature is trying to answer is "who's this guy?". If he's an old user, a mod, an admin, is active, maybe the points, etc.

In order to know "what has this guy been up to?" (last played games, last awards, rich presence) people need to visit the profile page.

**Comment by televandalist** [comment]
![Screenshot_20190727-144243](https://user-images.githubusercontent.com/45054151/61998967-72817c80-b07d-11e9-88e8-57ddd41676c5.png)

In any case, having some sort of "card" is a fun.

**Comment by MrOwnership** [comment]
This one is pretty basic but it shows what I think the be the most important user stats/information.
![](https://i.imgur.com/L9eblS6.png)

I envisioned it as showing brief information about the user/user activity without having to actually go to the user page, RA's version of the 'gamercard' that PSN and MS have. I'm not sure how much time and effort is worth putting into creating a full fledged 'gamercard' for v1.

**Comment by meleu** [comment]
@MrOwnership a PR with this would be nice! :ok_hand:

**Comment by kdecks** [comment]
Maybe account creation date too

**Comment by luchaos** [comment]
> Maybe account creation date too

This is very problematic unfortunately. The account creation date is not stored on the user entry in the database and is derived from the (crazily huge) activity table. 

I tested this with production-like data locally and the result is very slow loading times.

Removing the account creation date and pushing it to production without it. We can easily have those added in v2 as the v1-to-v2 migration will try recreating singup dates and store them properly on the user entries.

**Comment by luchaos** [comment]
Deployed to production.
