### ISSUE TITLE
Unused usernames display an unregistered account page

### ISSUE THREAD

**Issue by ViperZang** [RetroAchievements/RAWeb#327]
If you type in a URL with a username that doesn't exist, it will display a page with that username as an unregistered account with blank data (avatar, points, etc.).
I think it should either display an error page (like invalid game IDs) or redirect to the homepage (like invalid achievement IDs)

Example:
![NotAUsername](https://user-images.githubusercontent.com/31069034/61089776-378b1200-a40a-11e9-9f2f-fdb766c782cc.png)
https://retroachievements.org/user/NotAUsername

**Comment by televandalist** [comment]
You can also modify the Unix time in the history URL and see how your cheevo progress was in 1970 :deng:

https://retroachievements.org/historyexamine.php?d=1&u=televandalist

**Comment by luchaos** [comment]
This will result in a 404 Not Found response in v2.

**Comment by luchaos** [comment]
> This will result in a 404 Not Found response in v2.

Added in https://github.com/RetroAchievements/RAWeb/commit/356b4919dc79a7020819b13536974f06bcd13d68
