### ISSUE TITLE
Deleted official game forum threads still linked after deletion

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAWeb#33]
When official forum threads for a game are deleted they are still linked from the game page. The title is lost and no one can contribute to the thread.

**Comment by meleu** [comment]
note to self:
File `lib/database/forum.php`, function `requestModifyTopic()`, [logic starting here](https://github.com/RetroAchievements/RAWeb/blob/8ce6d8f07b10507f4e2785a75b50ba064968171f/lib/database/forum.php#L587) should check if the topic that is about to be deleted is linked to a game (`GameData.ForumTopicID`).

**Comment by meleu** [comment]
I fixed it in commit https://github.com/RetroAchievements/RAWeb/commit/534c1edc05c931f11ad4f63750988681d60dabfd
