### ISSUE TITLE
Transparent Image Support

### ISSUE THREAD

**Issue by ViperZang** [RetroAchievements/RAWeb#330]
Currently, images with transparent backgrounds have the transparency turned to black.

The only other work-around is to match the background colors, but that only works on even-numbered rows. Other places usually have gradients, which doesn't work at all.

This feature would be useful for some game badges that use the RAGray background color, as well as profile pics that just contain a logo, such as mine.

![Screen Shot 2019-07-26 at 5 30 00 PM](https://user-images.githubusercontent.com/31069034/61982972-828d5380-afcc-11e9-8aa4-9312b32aa9b1.png)

**Comment by luchaos** [comment]
Deployed to production.
