### ISSUE TITLE
Streamer support

### ISSUE THREAD

**Issue by SporyTike** [RetroAchievements/RAWeb#332]
A while ago I thought about a support for RA streamers and the last few weeks I also heard it from streamers itself.
Currently there are a few RA users who stream their achievement earnings and development and as a result they do advertising for the site because some viewers see it and join RA. In my opinion it would be fair to support those streamers.
In the past there was a stream section for the RA Twitch channel on the mainpage so I thought about bring something like this back. A small section where people can see which users stream RA at the moment (maybe with game).

**Comment by Thoooreau** [comment]
Maybe a page like http://www.speedrunslive.com/, right? Would be cool, indeed.

**Comment by televandalist** [comment]
I brought up having featured streamers at a staff meeting a while back and everyone was on board. It's just a matter of someone volunteering to take charge of it and keep it organized. 

FYI: I'm pretty ignorant about streaming culture, but know many people at RA enjoy it.
