### ISSUE TITLE
Create option for devs to "follow" sets

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAWeb#345]
Follow/watch/adopt/star⭐️, basically a simple means for developers to get notification when a set has new tickets or when achievements have changed. This will allow devs to take responsibility for sets that don't have an active developer and provide a way for them to track issues for achievements they have worked on where they are not the author.

Ideally it's a one button step. It would also be nice to be able to see a list of all sets that are followed on a generated page.

**Related**
#185 Add the ability for users to star games
#251 Automatic email for new tickets
#247 Receive an inbox message when a ticket I created has been updated
 #102 Developer Set Sign-in and Jr-Developers

**Comment by meleu** [comment]
It seems solved once #349 was merged.
Feel free to reopen if I'm wrong.
