### ISSUE TITLE
Unlink Game Entry Changes

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAWeb#35]
1 Add a field where developers can label each MD5.
2 Add a CRC32 field. Hopefully this is generated automatically.
3. Change the name of **Unlink Game Entry** to Linked Version Manager.

See: #1 Show Linked hashes on game page

**Comment by Jamiras** [comment]
Love the idea of labelling MD5s. I think #47 should have superceded this instead of the other way around. Maybe update the title to be similar to #47.

**Comment by meleu** [comment]
Related: #133
