### ISSUE TITLE
Sort Authors by Core Achievement Count

### ISSUE THREAD

**Issue by televandalist** [RetroAchievements/RAWeb#353]
If a game has an achievement set, the authors are currently sorted alphabetically. 
Example: http://retroachievements.org/game/2022
Authors: CeruleanKnight, JAM, Nomstuff, pgj1997, tuteur51

Sorting authors by core achievement count would make it appear as so: 
tuteur51 (21), JAM (5), Nomstuff (5), pgj1997 (4), CeruleanKnight (2)

Sure, it's a minor tweak that won't mean much for most people, but I think sorting this way makes more sense. Also, in some cases, it would give a better idea of who to contact regarding a set.

**Comment by MrOwnership** [comment]
Done, I'll create a PR for this sometime tomorrow.

![image](https://user-images.githubusercontent.com/16140035/67069014-b8645300-f149-11e9-963a-2570f4178ee7.png)

**Comment by luchaos** [comment]
Thanks for taking care of it @MrOwnership .
This addition makes sense for the site's current state. And while I'll review and merge the pr i'd still like to mention that this will be gone in v2 - as the way that contributions to sets or individual achievements will not be based on mere achievement creation.
That said - that's my main concern with almost all changes that are currently going into v1...

**Comment by luchaos** [comment]
Added in https://github.com/RetroAchievements/RAWeb/pull/354
