### ISSUE TITLE
Remove "Show Complete|Incomplete Only" from gameList.php

### ISSUE THREAD

**Issue by televandalist** [RetroAchievements/RAWeb#379]
https://retroachievements.org/gameList.php

This filter went by whether a game had 400 points or not, which is no longer necessary.

I also suggest removing the right container and adding some more filtering options, much like https://retroachievements.org/achievementList.php

**Comment by luchaos** [comment]
You are referring to the `complete`/`incomplete` filters https://retroachievements.org/gameList.php?d=&c=0&f=1&s=0 ?
I agree - those should be removed.
