### ISSUE TITLE
Option to Hide Mastery Badges

### ISSUE THREAD

**Issue by eldexterr** [RetroAchievements/RAWeb#380]
Been requested multiple times before :+1: 
I don't want to have :freepoints: Rayman prototype in my profile

**Comment by televandalist** [comment]
Thought about this last night actually. Maybe in the award sorting pages, assigning an X or something would hide the award.

**Comment by meleu** [comment]
You guys shouldn't be ashamed of that "Bubble Bath Babes" badge you have. It's just an innocent puzzle game. :innocent:

**Comment by eldexterr** [comment]
Ashamed of Bubble Bath? I'm proud of that one lol :deng:

**Comment by kdecks** [comment]
I would love this

**Comment by Blazekickn** [comment]
I mostly just want it to hide sets that got revisions or :freepoints: sets that are getting revisions
