### ISSUE TITLE
Duplicate Leaderboard Option

### ISSUE THREAD

**Issue by Tsearo** [RetroAchievements/RAWeb#386]
I would like to see a feature on the on the leaderboard page for duplicating leaderboards.

Many times leaderboards are exactly the same except for one value changing and it would save a lot of time to use one completed leaderboard as a template and then only have to modify a single value in the rest.

Something simple like this to select a specific leaderboard to copy and how many times you would like it copied. <br/>
![image](https://user-images.githubusercontent.com/4047771/71628931-a6cb0d00-2bc8-11ea-9c73-296cf2c29da7.png)

Possibly also setting a starting Display Order to increment from as well.

**Comment by luchaos** [comment]
Added in https://github.com/RetroAchievements/RAWeb/pull/397
