### ISSUE TITLE
Most Requested Sets - Next 50 Error

### ISSUE THREAD

**Issue by Pearate** [RetroAchievements/RAWeb#412]
On the site, when you click on the Next 50 link, it brings you on an empty list...  
[Most Requested Sets](https://retroachievements.org/setRequestList.php)

**Comment by MrOwnership** [comment]
The issue has been address and fixed with PR #402. It has been merged into the develop branch but not yet deployed to the site.

The current way around the issue would be to manually remove the `&s=` from the url.

**Comment by meleu** [comment]
deployed and fixed! :+1:
