### ISSUE TITLE
Faster way to see own sets and tickets

### ISSUE THREAD

**Issue by SporyTike** [RetroAchievements/RAWeb#415]
Would it be possible to add two new links to the dropdown "My Pages" in the site menu? I would like to have a direct link to my achievement sets I created and to all my tickets. At the moment to view them I need to load my profile page first and then click on the links to go there. It would be much faster to just click the dropdown and then select the site the developer wants to see and wouldn't need to load two (or even three) pages.

**Comment by televandalist** [comment]
Been meaning to add those + the site award management to the navigation bar.
