### ISSUE TITLE
Get_UserSummary Endpoint always return empty data set

### ISSUE THREAD

**Issue by CBeatt13** [RetroAchievements/RAWeb#434]
Current the Get_UserSummary end point always returns an empty data set. Appears to have broken at the end of January with the middleware push.

**Comment by CBeatt13** [comment]
This may be related to ticket #421

**Comment by luchaos** [comment]
Thank you for narrowing down to that specific commit. 
A very sloppy oversight, my bad (we need tests) - it's fixed now.
