### ISSUE TITLE
Provide a Docker file

### ISSUE THREAD

**Issue by luchaos** [RetroAchievements/RAWeb#44]
... and add a note to documentation section.

**Comment by ahstro** [comment]
Any progress on this? I'd love to play around with the code, but I don't feel like doing a bunch of setup on my own box. (I tried playing around with this a bit, but I'm a complete novice when it comes to Docker)

**Comment by luchaos** [comment]
i'll add the required docker files as soon as i'm done with refactoring, i actually need that myself to verify the apache setup (currently running on nginx)
the docker setup will be as close to the prod setup as possible.
