### ISSUE TITLE
Get link of specific post in the forum

### ISSUE THREAD

**Issue by SporyTike** [RetroAchievements/RAWeb#442]
There is no way to link to a specific post in the forum yet. If person A wants to show person B a specific post of a forum, they need to post the whole link of the page or add e.g. `&o=3` to the link to show the one as first on the page.
Would be nice if there is an easy way to get the link by pressing something like a "copy link to post" button on the post which could look like on the picture. 

![Unbenannt](https://user-images.githubusercontent.com/45672834/78055184-6fb0f700-7383-11ea-9a8d-adb8c8ce21f4.png)

**Comment by luchaos** [comment]
Resolved in https://github.com/RetroAchievements/RAWeb/pull/456/commits/32282cebbf1b2aefb5a72b5ab960ae244dc4c2de
