### ISSUE TITLE
READ ME section for all game entries

### ISSUE THREAD

**Issue by JuliaWolska** [RetroAchievements/RAWeb#45]
In this section every developer could add notes, especially about things the player should know about the set. It would be for the best to have this section visible in the emulator asap, to bring access to all necessary information about the set, with no need to access the site.

**Comment by kdecks** [comment]
#36

**Comment by kdecks** [comment]
I've removed this same concept from #36 So they can be two separate issues.

What I wrote there: 
>Perhaps there can be a completely different solution to this problem like adding a **Resource and Information** or **Read-me** page on the game page. Somewhere for each game where devs can post and edit important information about the set.

**Comment by meleu** [comment]
Closing this issue here. Another one was opened by Scott and it is using the "GitHub projects" feature.

See #106
