### ISSUE TITLE
Cache images to improve repeat visits

### ISSUE THREAD

**Issue by Haggus** [RetroAchievements/RAWeb#452]
When I'm looking at my profile page, it takes a while to load all achievement images. This could be improved by setting a cache control header:

 `Cache-Control: max-age=31536000`

That way, on consecutive page loads, the images could be cached and wouldn't have to be downloaded on each refresh. Since most of them are not going to change anytime soon, that cache timeout could be set higher (like 30 days or even a year).

I noticed they are all served from S3, which supports setting cache control. If you need help with configuration, feel free to reach out :)

**Comment by luchaos** [comment]
Thanks for the heads up! That's an oversight on our end. 
As it happens i'm currently reconfiguring some of the cache control headers for other assets on the host - i'll take care of that while at it.

**Comment by Haggus** [comment]
Awesome, in that case I'm closing the issue!
