### ISSUE TITLE
Easy way to reset progress for most recently played game

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RAWeb#453]
Most often when I want to reset game progress it's for the game I've most recently played. In all of these scenarios, it would be beneficial to have the most recently played game selected in the Reset Game Progress combobox:
* Reset entire game
  * don't want the low completion percentage to lower my overall completion percentage
    * didn't like the game
    * game was too hard
  * was only playing the game to fix tickets
  * a bunch of achievements unlocked as soon as I opened the game
* Reset individual achievement
  * want to re-earn the achievement (for AotW or similar event)
  * achievement triggered incorrectly
  * want to force a mastery by resetting and re-earning a simple achievement in the set

As a side note, the list is currently sorted by console ID, then game name. If the list were sorted by game name first it would be easier to find things.

**Comment by meleu** [comment]
I think every game page could have a link where the player could reset the progress for that game (if at least one of them is awarded), and every achievement page could have a link to reset that individual achievement (if awarded).

It seems to be easy to implement using [resetAchievements()](https://github.com/RetroAchievements/RAWeb/blob/74654482880e00d86da0efe5c02b222b9768a0eb/lib/database/achievement.php#L819) (for resetting all achievements from a game) and [resetSingleAchievement()](https://github.com/RetroAchievements/RAWeb/blob/74654482880e00d86da0efe5c02b222b9768a0eb/lib/database/achievement.php#L870) (for resetting individual achievements).

**Important**: in the frontend it's important to ask for a confirmation and highlight that such action is not reversible.
