### ISSUE TITLE
Horizontally flip the default game badge

### ISSUE THREAD

**Issue by ViperZang** [RetroAchievements/RAWeb#454]
Minor cosmetic change.
Currently, the default game badge, [located here](http://retroachievements.org/Images/000001.png), is a stock controller image with the dpad on the right. Most controller have the dpad on the left, so the icon looks weird.

Current
![000001](https://user-images.githubusercontent.com/31069034/79642826-bd907200-816d-11ea-9598-869e84bcfdcb.png)

Proposed (jpg because I'm on mobile and that's how the app saved it)
![1587225972362](https://user-images.githubusercontent.com/31069034/79642848-d4cf5f80-816d-11ea-9bd7-3dd563915b16.jpg)

**Comment by luchaos** [comment]
Updated on [server](http://retroachievements.org/Images/000001.png) and [S3](https://s3-eu-west-1.amazonaws.com/i.retroachievements.org/Images/000001.png)
