### ISSUE TITLE
Checksum section for all game entries

### ISSUE THREAD

**Issue by JuliaWolska** [RetroAchievements/RAWeb#46]
This would bring information about the CRC32 checksums of all linked ROMs - information for all players to be able to identify correct version of the game. MD5 values, which are used by the system (and by developers to identify linked ROMs), could be maintained through improved Unliking page, which should be renamed to "Linked Version Manager" or something similiar. It would be the best if this section were updated authomatically, when the ROM is linked.

**Comment by kdecks** [comment]
#1 
#35

**Comment by kdecks** [comment]
It would be better to post any additions on these concepts in issues 1 and 35.
