### ISSUE TITLE
Assign Console IDs to several missing consoles

### ISSUE THREAD

**Issue by televandalist** [RetroAchievements/RAWeb#496]
Magnavox Odyssey and Neo Geo CD appear to be fully functional in RALib, but currently lack console IDs. Could use the opportunity to assign console IDs to several other missing consoles. 

Suggestions since the actual order doesn't matter: 
23 - Magnavox Odyssey
56 - Neo Geo CD
57 - Fairchild Channel-F
58 - FM Towns
59 - ZX Spectrum
60 - Game & Watch
61 - Nokia N-Gage
62 - Nintendo 3DS

**Comment by meleu** [comment]
Solved in #497
