### ISSUE TITLE
add an option to "unsubscribe" a forum thread

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAWeb#5]

**Comment by kdecks** [comment]
And a way to choose to subscribe, not to just be subscribed by default.

**Comment by RetroAchievements** [comment]
Yes please, I want this

**Comment by ScottFromDerby** [comment]
Merging my own feature requests
Unsubscribe from RA forum posts/emails functionality (Ticket Comment, Forum Post, Game Post, Achievement Post)

**Comment by luchaos** [comment]
Resolved in https://github.com/RetroAchievements/RAWeb/pull/349 thanks to @gdeOo .
Great job.
