### ISSUE TITLE
A way to make the "value" field in leaderboards read a different value depending on certain conditions.

### ISSUE THREAD

**Issue by Alfex3** [RetroAchievements/RAWeb#513]
When several versions of the game have been made compatible, either by the original dev or by someone else, there still can be only 1 value for each leaderboard. My suggestion is something like this: "if these conditions are true, the value to submit is this one, otherwise it's this other one". It might be possible to do with "?", like in rich presence.

**Comment by Jamiras** [comment]
This is more of an issue for the runtime (rcheevos) than the website (RAWeb).

You could try to use the MAXOF operator (http://docs.retroachievements.org/Leaderboards/#value-interpreter)

> Connecting two value conditions with $ will cause only the one with the highest value to be used.

But that would only work if you can guarantee the value for the alternate versions was always lower than the value for the current version.

A better approach would be to leverage Measured/MeasuredIf using alt groups, but the leaderboard value parser currently doesn't support alt groups. Each alt group would represent a single supported version, with a MeasuredIf limiting each alt group to a specific version.

A final alternative, which would impact RAWeb (as well as rcheevos and RAIntegration), would be to have different definitions per hash. The server would only send the client the value definition appropriate for the hash being used, but the editor would have to somehow support defining values for all hashes.

**Comment by Keltron3030** [comment]
I think the measured/measuredif alt groups would be the best option as there are times when a developer may require alternate values other than just for alternate hashes as proposed.  I have an example right now where I want to submit a value from an array slot dependant on which one is active.  Technically in this case it would also be beneficial to be able to tie alternate submits to their corresponding value.

**Comment by Alfex3** [comment]
Similar to how Measured is used for hit counts, Measured if could be used as a boolean. Example: Q:ROM=US*USvalue_Q:ROM=EU*EU value. #582 would make it even easier.

**Comment by Jamiras** [comment]
The linked rcheevos ticket has been released in RAIntegration 0.79 and RetroArch 1.9.4. You can now use `MeasuredIf` and `$` to get different values for different conditions. See the ticket for an example.
