### ISSUE TITLE
dorequest.php?r=login Doesn't work if password contains certain characters

### ISSUE THREAD

**Issue by snewell** [RetroAchievements/RAWeb#514]
Started getting login issues last night and I *think* it's related to this commit: https://github.com/RetroAchievements/RAWeb/commit/33aa7008d213b3ef8e2cb02b030780581e29782e (the timing matches up, but I haven't bisected the commits yet to be 100% sure).  I installed RAWeb locally and can reproduce if I set my password to "!Password" or "_Password".  "Password" and "password" both work fine, so I'm guessing it's something related to the character encoding.  Logging in via the regular website works fine.

Let me know if you need any more information.  I'll see if I can triage further when I have some bandwidth and update this issue.

**Comment by snewell** [comment]
Sorry, realized some specific error messages would be useful:
Failure:
```
$ curl 'https://retroachievements.org/dorequest.php?r=login&u=<login>&p=<password>'
{"Success":false,"Error":"Error with login! Please try again."}
```

Success:
```
curl 'http://192.168.1.114:64100/dorequest.php?r=login&u=<login>&p=Password'
{"Success":true,"User":"partnerslayer","Token":"FnxWpVRmcht6jiMT","Score":0,"Messages":0}
```

**Comment by luchaos** [comment]
Thank you for reporting this issue @snewell ! It's indeed related to said commit - i reverted the code in question. 
Should work as intended again?

**Comment by snewell** [comment]
Seems fine now.  I already changed my password on the main site (retroarch sends passwords in the clear, which something I should probably write a pull request for...), but it works on the local version of RAWeb that I'm running.

Thanks!
