### ISSUE TITLE
Page is down

### ISSUE THREAD

**Issue by Danyelalejandro** [RetroAchievements/RAWeb#515]
Webpage is down
http://www.websitedown.info/retroachievements.org
Thank you guys

**Comment by televandalist** [comment]
Why yes, yes it is.

**Comment by Danyelalejandro** [comment]
Thank you @televandalist Love your sets and support to the community. Will wait then

**Comment by televandalist** [comment]
It's only gone down a couple times in the past two years or so. Each time it wasn't down long. 

Also, 👋 #github-log

**Comment by Danyelalejandro** [comment]
Solved! Will close issue. Thanks everyone
