### ISSUE TITLE
Tell in "Report an issue with this achievement" how to see the checksum in RetroArch

### ISSUE THREAD

**Issue by Alfex3** [RetroAchievements/RAWeb#517]
When there's only one hash linked, this isn't a problem, but if there are more, when a ticket says "MD5: Unknown", you have to either check all the ROMs, or contact the reporter and wait for an answer.

**Comment by HolyShinx** [comment]
updated the wiki to say how to check the MD5 hash, maybe linking it on the report page would be a good 
https://github.com/RetroAchievements/docs/wiki/FAQ#how-do-i-check-the-md5-hash-of-the-game-im-playing

Hope meleu approves it :smiley:

**Comment by Jamiras** [comment]
When an achievement is unlocked, the hash is passed to the server along with the other parameters required to do the unlocking. This was added to allow automatically tracking compatibility in v2 (see #96 and #284). Depending on whether or not the captured data is aggregated, it may be possible to see exactly which hash the user was using for the unlocks they did get.

**Comment by luchaos** [comment]
Can we derive a concrete action from this for V1? V2 will handle things differently - anything to do in v1 here? Otherwise i'd rather close this issue.

**Comment by Jamiras** [comment]
You can probably close this as solved by #674.

![image](https://user-images.githubusercontent.com/32680403/171964730-19434e83-c744-4917-917b-b41e13ba647c.png)

I'd still like the ability to see which hashes the user has actually used, but I'm not sure that's a V1 thing.

**Comment by luchaos** [comment]
We _could_ implement all of the player session logic in v1 if we wanted to but that's a whole different issue - a ready made PR rather. Closing 👍
