### ISSUE TITLE
[Suggestion] Allow devs to self-award site awards for their sets.

### ISSUE THREAD

**Issue by ViperZang** [RetroAchievements/RAWeb#518]
My idea is to allow developers with achievements in a core set to be able to give themselves site awards for the sets they have made.

As a dev, I proud of my sets, and like the games, but sometimes I get tired of the games for a while, and don't really replay it. I believe there are others like that too. Some I don't even have the skill to master myself, but I'm proud of my work.

I feel there should more dev recognition than 6,000 earns, and 70,000 points. A site award for the set's you've made would be a nice addition.

Side note: Borders are nice, like the gold hardcore border, and maybe the dev awards could be purple since it's already associated with devs because of the discord role

**Comment by HolyShinx** [comment]
I mean automatic softcore badge doesn't seem like a bad idea (softcore makes everything free anyway)

**Comment by meleu** [comment]
Advertising their creation is cool, indeed. But using the site-awards for it would be an ugly workaround.

A better solution would be a separated section on the side bar of the user's page, identical to the site awards but with the badges of the games they worked on.

I'm putting this in my TODO list.

**Comment by ViperZang** [comment]
Seperate section does sound better. 
Maybe putting the existing dev awards there would be cool too.

**Comment by Blazekickn** [comment]
theres already a section on users profiles dedicated to sets they have made achievements for. GIving people a badge for making the set does little but remove the incentive that's already there to go back and play the set.

**Comment by Blazekickn** [comment]
*besides the points obviously

**Comment by televandalist** [comment]
Should separate event badges from game badges, too. Can't imagine it being too difficult considering events have their own console ID. Might affect how the page for sorting badges works, though...

**Comment by meleu** [comment]
The request being made in the title of this issue is not going to be implemented.
I'm closing this issue.
