### ISSUE TITLE
Require users to select Hardcore or Softcore when submitting tickets. 

### ISSUE THREAD

**Issue by televandalist** [RetroAchievements/RAWeb#521]
There are few things more irritating than spending time troubleshooting a ticket only to find out that the user was playing on softcore and hits weren't saving/loading for them. 

This would also help on the manual unlock end.

**Comment by luchaos** [comment]
> Softcore not storing hits hasn't been relevant for some time on anything other than Duckstation standalone.

Still relevant?

**Comment by luchaos** [comment]
nevermind. added in https://github.com/RetroAchievements/RAWeb/pull/673
