### ISSUE TITLE
Can't reset progress from game page if the only achievement obtained is worth 0 points.

### ISSUE THREAD

**Issue by televandalist** [RetroAchievements/RAWeb#525]
For example, the only achievement I have in [Space Harrier II](https://retroachievements.org/game/81) is the AAAARRGHH achievement, which is worth nothing. The option to reset progress is missing from the game page. It still appears on the achievement page, though.

**Comment by meleu** [comment]
Indeed, the verification to show that option to reset the progress is checking if the amount of points earned is greater than zero:

https://github.com/RetroAchievements/RAWeb/blob/21fa0793c3cd95cc9b539c5979df2d4ed23186ed/public/gameInfo.php#L747

I'll try to find another way to check it later.
