### ISSUE TITLE
Extended developer section in user profile

### ISSUE THREAD

**Issue by JuliaWolska** [RetroAchievements/RAWeb#55]
For starters it should list all games the developer contributed in, and allow the developer to make notes under any of them. This could replace developer stats.

**Comment by kdecks** [comment]
It could be expandable/collapsible as well or got to a subpage. Some devs ``*ahem*`` lists would be quite long.

**Comment by meleu** [comment]
@JuliaWolska could we close this request once the gameList by dev already exists?

I know it's not exactly the same thing you're asking (`and allow the developer to make notes under any of them`), I just wanna know if that could be considered "good enough" to close this issue...

**Comment by meleu** [comment]
on discord Salsa said that this issue here can be closed. Implementing what is being suggested in #106/#45 and #164 should be enough.
