### ISSUE TITLE
Untracked users show Site Rank in tooltip

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RAWeb#555]
An untracked user's Site Rank is listed as "Untracked" on their profile page:
![image](https://user-images.githubusercontent.com/32680403/115117544-54983180-9f5c-11eb-96e2-6a8bfa2ababc.png)

But an actual value appears when viewing their tooltip:
![image](https://user-images.githubusercontent.com/32680403/115117535-4cd88d00-9f5c-11eb-82f0-ad96311cceab.png)

**Comment by meleu** [comment]
Fixed in #559
