### ISSUE TITLE
Game Page Flags

### ISSUE THREAD

**Issue by JuliaSalsa** [RetroAchievements/RAWeb#57]
Every fresh set should be marked with Public Beta flag until it's somewhat verified as stable (could be simply marked/unmarked by developer). WIP flag could be used to mark/unmark sets that are currently under construction (mostly usable to indicate the set is currently revised for all  who are interested in playing this game at the time).

**Comment by kdecks** [comment]
I'd like to expand on this idea and I'd suggested renaming this issue **Game Page Set Status**

### Other Set Statuses:
- Sets would default to ``Empty``
- ``Public Beta``
- ``🔨 Work in progress`` with a developer or developers signed into the game, this would be logged (#11) 
- ``❗️ Unstable``
- ``🌟 Stable``
- ``Incomplete``

One other thing, the latest status change would be shown.

**Comment by kdecks** [comment]
I've updated this concept to go in tandem with #102.

**Comment by SyrianBallaS** [comment]
I think this a good idea, this might prevent invalid tickets

**Comment by kdecks** [comment]
An addition: A message that only is show to developers by an `unstable` flag.
```This set has x open ticket you can enhance the community by repairing them.`` 
(or something to this affect.) And link to the open tickets from here.

**Comment by Jamiras** [comment]
Suggest also adding quick reference pages so players can find "public beta" and "new" sets, as well as provide a master list of "in development" games.
