### ISSUE TITLE
A [ticket=#####] tag on site

### ISSUE THREAD

**Issue by televandalist** [RetroAchievements/RAWeb#575]
Mostly self-explanatory. Output could be something as simple as "🎟️ - 38800" - Would obviously need to be a link to the ticket, but having a tooltip with ticket info would be great. 

I don't see it being used in the forum much outside of stuff like The Unwanted and DevQuest, but QA would get a lot of use out of it for site messages.

**Comment by luchaos** [comment]
Merged. Will be included in next release.
