### ISSUE TITLE
add more info about the forum post on the email notification

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAWeb#6]
Once I commented on that "What games you want achievements?" topic I feel like cursed. I'm not interested in following that thread. And, as there's no option to unsubscribe it, I would like to, at least, see the topic's title in the notification message. And then I could delete the message without having to click on the link and being frustrated...

IMO it would save some bandwidth too.

**Comment by Jamiras** [comment]
Would also be nice if the link went straight to the new post instead of having to scroll down through the previous posts that have already been read.
