### ISSUE TITLE
BW site award for the set which was revised

### ISSUE THREAD

**Issue by JuliaSalsa** [RetroAchievements/RAWeb#62]
The site award could turn black and white if the game recieved revision. I think it's better solution instead of just make them vanish. Still it could be set in the profile, if somebody wouldn't like it.

**Comment by kdecks** [comment]
I don't think either should happen. As a player I like that when I've finished a set that I keep the trophy regardless off revision. Players would not like these changes.

**Comment by JuliaWolska** [comment]
It might be optional. Some players would like to know if a set they completed got new achievements.

**Comment by Jamiras** [comment]
I'm not sure anyone would want their trophy to be demoted or disappear, but I could see wanting to revisit a modified set.

It would be better to address this with some sort of notification process. The simplest implementation would be to send a notification message to every user who has mastered the set. It would appear in their inbox and not affect their user page at all.

An alternate implementation would be to put a notification marker (!) over the icon to draw the user's attention. Upon hovering over it, they could see a message indicating that the set has been revised, and can dismiss the notification to make the marker disappear.
