### ISSUE TITLE
lbinfo API changes for returning data near a specified user

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RAWeb#625]
DuckStation is trying to show leaderboard rankings in their emulator using the `lbinfo` API, which is not currently exposed through rcheevos. Before I add it to rcheevos, I'd like to request a couple changes to make it easier to use.

-----

The first change has to do with the shared ranking system (#576). The `lbinfo` API currently appends the user's entry to the end of the response if it's not already in the list. It does this with whatever the "tied" rank is, so it's impossible to know what offset to use to get the neighboring entries. 

For example, here's a partial response for a `lbinfo` call:
```
{"User":"Azgorath","Score":323,"DateSubmitted":1615654895,"UserRank":"1","Rank":1},
{"User":"MizuchiOrochi","Score":489,"DateSubmitted":1600604303,"UserRank":"2","Rank":2},
{"User":"zuschzero","Score":647,"DateSubmitted":1456596394,"UserRank":"3","Rank":3},
{"User":"Riger","Score":705,"DateSubmitted":1464191350,"UserRank":"4","Rank":4},
{"User":"Fluttershy","Score":714,"DateSubmitted":1398132702,"UserRank":"5","Rank":5},
{"User":"nolen3110215","Score":714,"DateSubmitted":1436761683,"UserRank":"5","Rank":5},
{"User":"Casseadaim","Score":714,"DateSubmitted":1465404441,"UserRank":"5","Rank":5},
{"User":"Subzhero777","Score":714,"DateSubmitted":1468784685,"UserRank":"5","Rank":5},
{"User":"PMniac","Score":714,"DateSubmitted":1474985563,"UserRank":"5","Rank":5},
{"User":"BigFish","Score":714,"DateSubmitted":1475002686,"UserRank":"5","Rank":5},
{"User":"Jamiras","Score":743,"DateSubmitted":1556809936,"UserRank":"72","Rank":72}
```
My rank is returned as 72, but there's so many people tied for rank 72 that my offset is actually 199. The next non-tied rank is 275!
![image](https://user-images.githubusercontent.com/32680403/123127556-9f747080-d407-11eb-8ec3-fa327c1079eb.png)

If I asked for the five people on either side of rank 72, my record wouldn't be returned. Magicken is actually offset 72, and here's the five people on either side of him:
![image](https://user-images.githubusercontent.com/32680403/123127750-cd59b500-d407-11eb-8e3a-13b0ccd8fc06.png)

`UserRank` is currently not used, and as far as I can tell, always matches `Rank`. I propose eliminating it and adding an `Index` or `Offset` field indicating the value that would need to be passed to get the records around the user.

-----

The second issue is directly related to the first. There's no way currently to request the entries around a user without first determining where the user is by issuing a dummy request, extracting the user Index, and then issuing a second request with the appropriate offset.

As the `lbinfo` API does not currently require authentication, I propose leveraging the `u` parameter to query around the user. Using the leaderboard above, I could query `u=Jamiras&c=11` to get the five entries on either side of me (`o` would be derived as `indexof(Jamiras) - c/2`). `o` could still be used directly to query specific ranges when not interested in a specific user.

This would indirectly change the DLL to show the neighboring leaderboard entries (instead of the top 10) when viewing the leaderboard details in the overlay (which is probably a good thing). A similar change was requested in #281 for the scoreboard displayed after submitting a new entry via the `submitlbentry` API.

-----

The third issue is that there's no way to know how many entries are in the leaderboard without making multiple requests until no more data is returned. This data could be used to tell the user that they're in the top 20%, or to create a scrollbar in the UI.

I propose adding a `NumEntries` or `TotalEntries` field to the response (similar to the `NumEarned` or `TotalPlayers` provided by the `achievementwondata` API).

**Comment by Tsearo** [comment]
Alright so I think I understood what you wanted and have it working but want to double check before creating the PR in case there were any misunderstandings or any other improvements you'd like.

I've repurposed UserRank to UserPosition for tracking their placement, seems simple enough as it wasn't used for anything. 

Added TotalEntries to the results of the lbinfo call, another simple one. Ex. `"TotalEntries":164` added before the Entries

For the `u` parameter part I believe that `u` is already used to check for the user and append them to the end if they aren't in the returned results. When doing calls to lbinfo I have to input `r=lbinfo&u=Searo&i=4359` to get myself appended to the list if I'm not already in the results. So I instead added a new optional parameter to pass in `n` for nearby which is a boolean. `false` (default) will give normal existing behavior but `true` will return `c` results near the player based on changing the offset `o` to `$offset = $userPosition - intdiv($numToFetch,2) -1`. This will default to showing the extra user ahead of the specified user when the count is even (and there are users ahead of the specified user). 

One area of concern I do have is if the user is not found when the `n` nearby flag is used it will return an empty array of Entries, I can easily instead make it just return the top `c` entries if that is the preferred behavior though which is what the normal call to lbinfo does if the user is specified but doesn't exist.


Using old data for leaderboard ID 4361 as an example
`u=FlavourSavior` Results

```
,"TotalEntries":164,"Entries":[
{"User":"ManyHours","Score":4870,"DateSubmitted":1585514608,"Rank":1,"UserIndex":1},
{"User":"RideTheSkies","Score":4770,"DateSubmitted":1551978923,"Rank":2,"UserIndex":2},
{"User":"fyrenthenimar","Score":4760,"DateSubmitted":1552221123,"Rank":3,"UserIndex":3},
{"User":"DaniloZlatan","Score":4760,"DateSubmitted":1569272309,"Rank":3,"UserIndex":4},
{"User":"Hitzugy","Score":4760,"DateSubmitted":1584774556,"Rank":3,"UserIndex":5},
{"User":"zephyr97","Score":4550,"DateSubmitted":1549738720,"Rank":6,"UserIndex":6},
{"User":"oxitran","Score":4550,"DateSubmitted":1585834692,"Rank":6,"UserIndex":7},
{"User":"cochese788","Score":4520,"DateSubmitted":1549511790,"Rank":8,"UserIndex":8},
{"User":"DrDro","Score":4470,"DateSubmitted":1551751372,"Rank":9,"UserIndex":9},
{"User":"yendihunt","Score":4460,"DateSubmitted":1548950609,"Rank":10,"UserIndex":10},
{"User":"FlavourSavior","Score":4000,"DateSubmitted":1588896880,"Rank":51,"UserIndex":61}
```


`u=FlavourSavior&c=11&n=true` Results

```
,"TotalEntries":164,"Entries":[
{"User":"Phipe93Arancibia","Score":4000,"DateSubmitted":1557372515,"Rank":51,"UserIndex":56},
{"User":"TheBigChiklis","Score":4000,"DateSubmitted":1570856431,"Rank":51,"UserIndex":57},
{"User":"DanRenegados","Score":4000,"DateSubmitted":1575934769,"Rank":51,"UserIndex":58},
{"User":"MenaceInc","Score":4000,"DateSubmitted":1582838864,"Rank":51,"UserIndex":59},
{"User":"64","Score":4000,"DateSubmitted":1583158425,"Rank":51,"UserIndex":60},
{"User":"FlavourSavior","Score":4000,"DateSubmitted":1588896880,"Rank":51,"UserIndex":61},
{"User":"Gex100","Score":4000,"DateSubmitted":1588934273,"Rank":51,"UserIndex":62},
{"User":"somakarma","Score":3980,"DateSubmitted":1551829826,"Rank":63,"UserIndex":63},
{"User":"suki","Score":3940,"DateSubmitted":1550430805,"Rank":64,"UserIndex":64},
{"User":"Hotscrock","Score":3920,"DateSubmitted":1551644257,"Rank":65,"UserIndex":65},
{"User":"Rantsi","Score":3880,"DateSubmitted":1571160315,"Rank":66,"UserIndex":66}

```

As a bonus side effect I guess you can also pull just the entry for the user now as well if that helps with anything by calling nearby with a count of 1.
`u=FlavourSavior&i=4361&c=1&n=true`
```
"TotalEntries":164,"Entries":[
{"User":"FlavourSavior","Score":4000,"DateSubmitted":1588896880,"Rank":51,"UserIndex":61}]
```


If I didn't misinterpret anything and this all looks good to you let me know and I'll go ahead with getting it cleaned up and ready for a PR.

**Comment by Jamiras** [comment]
> I've repurposed UserRank to UserPosition for tracking their placement, seems simple enough as it wasn't used for anything.

Your examples show `UserIndex` which seems more appropriate than `UserPosition`, though I think `Index` would be sufficient.

> For the u parameter part I believe that u is already used to check for the user and append them to the end if they aren't in the returned results. When doing calls to lbinfo I have to input r=lbinfo&u=Searo&i=4359 to get myself appended to the list if I'm not already in the results. So I instead added a new optional parameter to pass in n for nearby which is a boolean. false (default) will give normal existing behavior but true will return c results near the player based on changing the offset o to $offset = $userPosition - intdiv($numToFetch,2) -1. This will default to showing the extra user ahead of the specified user when the count is even (and there are users ahead of the specified user).

You might need @luchaos 's input here. I believe the DLL is the only thing calling `lbinfo` currently (besides the recent attempts from Duckstation), so changing the behavior of the `u` parameter is probably acceptable. The DLL should show nearby entries, and changing the API would do so without needing a new DLL.

I don't see any reason to ask for the top N users _and_ the user's current position (current behavior). You either want the top N users or the entries near the user (usually the latter).

If `n` is still preferable, I would recommend using `1`/`0` instead of `true`/`false` to be consistent with the other APIs (i.e. `h=1` for hardcore)

> One area of concern I do have is if the user is not found when the n nearby flag is used it will return an empty array of Entries, I can easily instead make it just return the top c entries if that is the preferred behavior though which is what the normal call to lbinfo does if the user is specified but doesn't exist.

I think returning the top N entries would make more sense. Another thing to consider would be if the user is near the top or bottom of the list. If there's 20 entries and the player is entry 18 and I ask for the 11 nearest, should I just get 13-20 (8 entries) or 10-20 (11 entries)? Since I asked for 11 entries, the second seems better.

**Comment by CookiePLMonster** [comment]
> I think returning the top N entries would make more sense.

I agree, this is the only way not to have "User" leaderboards empty without the need to issue duplicate API requests.

> Another thing to consider would be if the user is near the top or bottom of the list. If there's 20 entries and the player is entry 18 and I ask for the 11 nearest, should I just get 13-20 (8 entries) or 10-20 (11 entries)? Since I asked for 11 entries, the second seems better.

The latter does seem better, as that will allow the emulator to always show full pages. Otherwise, in the worst case if the user was the last on the list, only 5 or 6 entries would be displayed, leaving a good part of the page empty!

**Comment by Tsearo** [comment]
Thanks for the feedback I think I have it more aligned with what you had wanted now that I understand it a bit more after testing it in RALibretro locally.

Here is what I currently have working so far, all examples using whatever the current dll's behavior is (defaults to `c` = 10 I believe) . It will default to getting nearby players (`n` = 1) to a user if they have an entry
![image](https://user-images.githubusercontent.com/4047771/124199704-86bc2880-daa1-11eb-916a-f972edd54bf5.png)

If there are no or less than `c`/2 entries before you then it will still grab a total of `c` entries
![image](https://user-images.githubusercontent.com/4047771/124200351-1f06dd00-daa3-11eb-9c1a-f6fcc121fe96.png)

If there are no or less than `c`/2 entries after you then it will still grab a total of `c` entries
![image](https://user-images.githubusercontent.com/4047771/124204198-89704b00-daac-11eb-87fd-49d3c78ab326.png)

otherwise it will return the top `c` entries
![image](https://user-images.githubusercontent.com/4047771/124200118-8a03e400-daa2-11eb-8a3c-f03edb0af639.png)

I believe the dll will still need to be updated to default to `c` of 11 if you want to have an even number of entries before and after a user right? 

This should be more of what you were wanting hopefully.

**Comment by Jamiras** [comment]
> It will default to getting nearby players (n = 1) to a user if they have an entry

Is the `n` parameter even still needed?

Otherwise, it seems to be what I was asking for.

**Comment by CookiePLMonster** [comment]
I agree about the above - `n` and specifying the user name are redundant, IMO queries without the user name specified should return top entries and queries with the user name should return nearby entries.

This will require allowing `lbinfo` to run without the user name specified.

**Comment by luchaos** [comment]
Implemented, merged & deployed. See #627
