### ISSUE TITLE
[QoL] Client timezone

### ISSUE THREAD

**Issue by srensamblador** [RetroAchievements/RAWeb#629]
As it stands, most dates are shown in UTC time (the active players widget in the homepage displays it in the client's, however).
If it were possible, it would be more user-friendly if the dates were converted to the client's timezone or at least, if users could choose their timezone in the settings.

**Comment by luchaos** [comment]
Thanks for the suggestion! 
Seems to be a duplicate of https://github.com/RetroAchievements/RAWeb/issues/85 / https://github.com/RetroAchievements/RAWeb/issues/94
Implemented in v2/dev: https://dev.retroachievements.org/settings/site
<img width="1528" alt="Screenshot 2021-07-04 at 22 27 05" src="https://user-images.githubusercontent.com/1280590/124398626-fe46bd80-dd16-11eb-95ff-29290eb3e140.png">
