### ISSUE TITLE
Admin permission to change avatars

### ISSUE THREAD

**Issue by JuliaSalsa** [RetroAchievements/RAWeb#63]
It could be allowed to admins to change avatars if they are broken or mark them as NSFW.

**Comment by kdecks** [comment]
Agreed. The should be able to be reset to default.

This would be logged (#11)

**Comment by televandalist** [comment]
Been able to set it to default for a while.

![re](https://user-images.githubusercontent.com/45054151/128511080-d0b7cf62-1e00-4b4f-a132-3a4ec0d049da.png)
