### ISSUE TITLE
Most Wanted Sets

### ISSUE THREAD

**Issue by JuliaSalsa** [RetroAchievements/RAWeb#64]
Registered users would have possibility to request a set for any game which doesn't have achievements. All votes could be listed in seperate section called "Most Wanted Sets"

**Comment by kdecks** [comment]
This issue has a topic (#36) You should post your thoughts there.

**Comment by kdecks** [comment]
We were discussing this in chat...

Having a button ``I want achievements for this game`` (Or something like it) on game pages that goes to a master list showing all the set requests.

These could disappear automatically based on set status (#57) when a set is no longer ``empty``.

It could show on the game page how many users clicked it, a list of their names, and a link to the master list too.

**Comment by meleu** [comment]
Implemented in #378 
closing
