### ISSUE TITLE
[Request] Retroarch integration / Provide better feedback to application when login token has expired

### ISSUE THREAD

**Issue by Nargash** [RetroAchievements/RAWeb#678]
When logging in to Retroachievements, Retroach initially uses your username/password, but then saves a token to its configuration file for future logins. What I have noticed, is if you do not log in for some time (turns out to be two weeks), the token expires. At that point, the user would need to log in with their password once again, which in terms of Retroach workflows means they need to delete the data from cheevos_token and re-add their password to cheevos_password in their retroarch.cfg file. From my testing, it looks like Retroarch will actually remove the token from its coniguration file when this occurs.

So the problem is it is not clear to the user that the expired token is the problem, and that the next step would be to confirm their token is cleared from retroarch.cfg and that they now need to re-enter their password.

I would propose that when the token is expired, a better message back is provided (I think it is coming [from here](https://github.com/RetroAchievements/RAWeb/blob/51d72fffe421e65b94616858ce0b10459e6cdee0/public/dorequest.php#L114)) and the message is currently: "Error with login! Please try again."

Thanks! Let me know if you need any more information or testing on my part.

**Comment by meleu** [comment]
Maybe `Error with login! Check your credentials and try again.`

What do you think? Do you want to suggest something?

btw: the logic you described (password removed from `retroarch.cfg` after successful login) was implemented in https://github.com/libretro/RetroArch/pull/6618 to avoid storing passwords as plain text.

**Comment by Nargash** [comment]
Hi meleu, yes I think something like that could be a good improvement! Since then a user would have an indication they should go and re-enter their password before trying to login again. Thanks for responding!

**Comment by chrcoluk** [comment]
Is there a reason the token needs to expire?  If I understand this issue correctly, if I dont login for two weeks, I have to manually enter the username and password again, this seems very odd behaviour and causes large inconvenience.

I think either making the token perpetual or remove the token with perpetual storage of credentials is the better way to go.

**Comment by Nargash** [comment]
> Is there a reason the token needs to expire? If I understand this issue correctly, if I dont login for two weeks, I have to manually enter the username and password again, this seems very odd behaviour and causes large inconvenience. (bear in mind copy and paste is blocked so have to manually type in these credentials also)
> 
> I think either making the token perpetual or remove the token with perpetual storage of credentials is the better way to go.

I believe it is for security (if your access token gets leaked, it can't be used indefinitely to log into your RA account). In regards to the inability to copy and paste (see issue #15824), I'd recommend pasting your password right into the retroarch.cfg file. It goes into 
`cheevos_password="<MYPASSWORD>"`

You also would need to remove your token from the same file, by setting this variable:`
cheevos_token = ""`
