### ISSUE TITLE
Provide to regular users (not only devs) the link to opened tickets for a game

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAWeb#7]
Maybe it can avoid duplications.

**Comment by SyrianBallaS** [comment]
Not sure how it works on the site but game tickets you've sent get sent through email if a change was made. Saying that since I'm not a "Dev" on RA, achievement-wise at least.

**Comment by grenade44** [comment]
Also maybe adding he ability to submit multiply achievements under 1 ticket, which all have the same issue. 

Like finishing a level doesn’t trigger the unlock on every level of a game and having a ticket opened up for every achievement.

**Comment by meleu** [comment]
implemented in #147
