### ISSUE TITLE
New RA github organization's avatar

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAWeb#73]
@ScottFromDerby you are very handsome and charming on that avatar picture, but maybe using another avatar for the @RetroAchievements organization would work better. :sweat_smile: 

My suggestions:

- This one made by @luchaos:
![ravatar](https://raw.githubusercontent.com/retroachievements/retroachievements.github.io/master/assets/images/retroachievements-logo-color-transparent-square.png)

- Or this one made by @JuliaWolska (aka Salsa):
![ravatar-joy](https://raw.githubusercontent.com/RetroAchievements/docs/master/img/icon.png)

**Comment by ScottFromDerby** [comment]
Agreed on both counts. (That I'm handsome, and that it should be a site logo). Love both logos though...

**Comment by ScottFromDerby** [comment]
Ok I think I've done it, have picked the first one despite loving the second one

**Comment by meleu** [comment]
Then, let's close this issue. ;)
