### ISSUE TITLE
Currently download links are broken

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAWeb#75]
Known issue, the download links are not working. We have a work-around to Salsa's dropbox, but the links need repair (and possibly an update to the new dll's and exe's soon?

Anyway, that's a separate issue. If the links are fixed this can be closed.

http://retroachievements.org/download.php

**Comment by meleu** [comment]
@JuliaWolska in the meantime could you update the files on your dropbox?

**Comment by JuliaWolska** [comment]
Update done.

**Comment by ScottFromDerby** [comment]
/bin/ needs reconstructing entirely :(

**Comment by ScottFromDerby** [comment]
Done! Scripts all updated. Also pushed out gd's latest changes. Cheers all
