### ISSUE TITLE
add links for the new supported systems

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAWeb#76]
@luchaos @ScottFromDerby would it be to much work to add links to the new systems in this list?:

![new-systems](https://user-images.githubusercontent.com/8508804/36673959-555762c2-1ae3-11e8-84a4-99cc7c8377fd.png)

I'm specifically talking about adding a link for [Atari Lynx](http://retroachievements.org/gameList.php?c=13) and [Neo Geo Pocket](http://retroachievements.org/gameList.php?c=14).

**Comment by meleu** [comment]
OK, @ScottFromDerby added the links, but looks like Virtual Boy is duplicated.

**Comment by ScottFromDerby** [comment]
lol woops
