### ISSUE TITLE
Unable to upload achievement badges

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RAWeb#79]
Attempting to upload a badge image through the achievement editor results in a "Error in upload! Try another image format, or maybe smaller image?" error dialog.

Response from server:
```
{"Success":true,"Response":{"Filename":"uploadbadgeimage.png","Size":1955,"Error":"Issues encountered - these have been reported and will be fixed - sorry for the inconvenience... please try another file!","Success":false}}
```

Related code: https://github.com/RetroAchievements/RAWeb/blob/71594911f967321eeb35ab43e4572f25f8450183/public/doupload.php#L240

Note: error_log call indicates wrong function: "UploadUserPic.php" instead of "UploadBadgeImage".

**Comment by Jamiras** [comment]
This appears to be working again. @ScottFromDerby - if you're done, please resolve this issue.

**Comment by meleu** [comment]
closing this issue.
Please reopen if the issue happens again.

**Comment by meleu** [comment]
@Jamiras you can also tag @RetroAchievements/raweb for RAWeb stuff :wink:
