### ISSUE TITLE
add forum sections for other consoles

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAWeb#8]
currently we need sections for
- Master System
- Nintendo 64
- Atari Lynx
- Neo Geo Pocket
- Atari 2600
- Arcade

In the future we'll need a section for:
- PlayStation

And maybe there are more to come!

**Comment by kdecks** [comment]
Could this be considered a bug? It's more than just an enhancement

**Comment by luchaos** [comment]
This could be done on a console's settings page.
Consoles will receive a reference to a forum topic in the database.
