### ISSUE TITLE
Forum Issue: YouTube videos break BBCode URL tag

### ISSUE THREAD

**Issue by ViperZang** [RetroAchievements/RAWeb#818]
currently, I you put a youtube link with no BBCode in the forums, it automatically turns the video into an embed.
However, using the BBCode tag for URL links causes the video to try to use YouTube embed features, which breaks the BBCode. I don't know what the backend stuff looks like, but from a user POV, it seems to be trying to convert the url into YouTube's iframe embed code. 

**Supplemantary information**
---

`[url=https://youtu.be/dMH0bHeiRNg]v2 wen[/url]` (as well as the long `https://www.youtube.com/watch?v=dMH0bHeiRNg` links)
will display as
![image](https://user-images.githubusercontent.com/31069034/132022501-2d49b84b-45be-4fd4-b0d2-41182849f4b7.png)

---

YouTube's sharing  feature gives this as embed code:
```
<iframe width="560" height="315" src="https://www.youtube.com/embed/dMH0bHeiRNg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

---

Not sure if it help, but here's the YouTube iframe API stuff
https://developers.google.com/youtube/iframe_api_reference

**Comment by MagmarFire** [comment]
This is almost certainly simply due to a bug with how the code is parsed. Should be simple enough to fix.

**Comment by luchaos** [comment]
> This is almost certainly simply due to a bug with how the code is parsed. Should be simple enough to fix.

The order in which the content body is parsed in particular. 

I made a test page for that a while ago: https://retroachievements.org/test/bbcode.php

Adding the problematic line there as a "test" case confirms the issue.

**Comment by luchaos** [comment]
"Linkifying" URLs to embeds is the first thing that is happening in the bbcode/shortcode parser: https://github.com/RetroAchievements/RAWeb/blob/master/lib/util/bbcode.php#L36

A suggested fix would be to not linkify URLs that are within a shortcode's attribute. The regex required for that is not hard to write but has to be implemented carefully to not break the other parsing step. That happened a few times in the past.

**Comment by ViperZang** [comment]
:zheart:
