### ISSUE TITLE
Add configuration to use bcrypt as the default password hashing algorithm

### ISSUE THREAD

**Issue by MagmarFire** [RetroAchievements/RAWeb#826]
Argon2id support isn't universal among all PHP installations. brypt, another hashing algorithm suitable for passwords, is generally much more readily supported. It would be useful to have a configurable value to have bcrypt be the default algorithm by default, at least for local development.

**Comment by luchaos** [comment]
This is a v1 issue. In v2 it's a mere Laravel default configuration.

**Comment by luchaos** [comment]
See [.env.example](https://github.com/RetroAchievements/RAWeb/blob/master/.env.example#L60). Closing
