### ISSUE TITLE
Achievement definition explanation is incomplete

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RAWeb#83]
The dev tools for an achievement attempts to dissect the achievement definition with the associated code notes. However, it doesn't support Alt Groups, or PauseIf conditions. I suspect it also doesn't support AddSource/SubSource/AddHits.

![image](https://user-images.githubusercontent.com/32706333/36343597-5c5f4b8a-13cb-11e8-80a2-7b80bb5a578c.png)

**Comment by meleu** [comment]
Solved in #219
