### ISSUE TITLE
Graphical error with old stock trophy badges and new trophy badge designs.

### ISSUE THREAD

**Issue by blendedsea** [RetroAchievements/RAWeb#832]
Error with some of the old stock trophy badges displaying the new trophy designs that were added recently.

As this image shows, I'm highlighting "Bump me up" which is displaying one of the new Trophy badge designs. Among this is two others; one the same the other new but different.
![graphic1](https://user-images.githubusercontent.com/91394986/134787394-4d246e62-e0d6-4653-b7eb-a42adfebb5fa.png)

Shown here is the achievement page of the mentioned achievement above. The greyscale badge is now displaying the old Trophy badge, and there hasn't been an edit since 2020.
![graphic2](https://user-images.githubusercontent.com/91394986/134787398-c7a2a26a-1ea2-4143-b0a3-51182ab03de9.png)

Thoughts are that the new badges may only display when they have been unlocked. And it's impossible to say which achievements will display what until unlocked, it seems.

**Comment by televandalist** [comment]
I notified the web team about this a couple days ago, but good to have an issue open.
