### ISSUE TITLE
Database Seeding/Population

### ISSUE THREAD

**Issue by SyrianBallaS** [RetroAchievements/RAWeb#84]
OK so I finally figured out how to get this thing to run on apache and mysql using XAMPP.
I also noticed a schema script for the DB and got that in as well.

The problem I'm facing is this:
`Notice: Undefined offset: 3 in %USERPROFILE%\source\RAWeb\public\gameList.php on line 18`

Then I figured it's because the DB is basically just a bunch of tables with no records.
I'm not 100% certain, but in MySQL Workbench (Windows Version), you can just click on the "Data Export" link under the "Management" Section and select the proper DB.

## Edit
I originally had this for just game page but it affects everything, forums, achievement pages, developer stats, global feed, etc. All those pages are basically empty. The home page is pretty much empty.

Some pages still look how they should like FAQ and Search the Site. The "Web API" page has some problems but I think it's because of my firewall. That might give a clue.

## Edit2
Usually I get this message if I didn't allow an outbound connection but it doesn't seem to be the case since I allowed it.

This is the message 

`Warning: file_get_contents(http://retroachievements.org/API/API_GetTopTenUsers.php?z=TestUser&y=&): failed to open stream: An attempt was made to access a socket in a way forbidden by its access permissions. in C:\Users\Samer\source\RAWeb\public\RA_API.php on line 23
`

This is the code:
`<?php RenderToolbar( $user, $permissions ); ?>`

So is it necessary to put a dummy account in the DB or something?

**Comment by SyrianBallaS** [comment]
Wasn't too sure if I should've opened a new issue because this seems related. I can't debug now.

Throws an exception.
**File**: /public/rcarousel/widget/lib/jquery.ui.rcarousel.js
**Function**: : function _islastPage( page )
**Line**: 283


This is what the Console says:



`SyntaxError: expected expression, got '<'
index.php:25
TypeError: data.lastPage[i] is undefined
jquery.ui.rcarousel.js:283
TypeError: e is null
player.c658e6f2a334a6a4e3f0.js:28
setStatsEnabled has been deprecated.
player.c658e6f2a334a6a4e3f0.js:28
"failed to resolve properties promise"
player.c658e6f2a334a6a4e3f0.js:28
Response {}
player.c658e6f2a334a6a4e3f0.js:28
bodyUsed:false
headers:Headers {}
ok:false
redirected:false
status:401
statusText:"Unauthorized"
type:"cors"
url:"https://api.twitch.tv/kraken/user"
__proto__:ResponsePrototype {clone: clone() {…}, arrayBuffer: arrayBuffer() {…}, blob: blob() {…}, formData: formData() {…}, json: json() {…}, …}
Error: e is null
player.c658e6f2a334a6a4e3f0.js:39
Offline Recommendations: No channel videos
player.c658e6f2a334a6a4e3f0.js:28
Offline Recommendations: No channel videos
player.c658e6f2a334a6a4e3f0.js:28
Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.
`

**Comment by luchaos** [comment]
@SyrianBallaS there will be an easy database migration/seeding tool in place as soon as i get around finishing the framework integration https://github.com/RetroAchievements/RAWeb/issues/42
I'll fix quite a few of the errors that are caused because of an empty database's state along the way
didn't have a look at all the javascript errors yet

**Comment by SyrianBallaS** [comment]
Sweet, I noticed your Lumen has an MVC architecture and that's what I'm used to. Since we're using MySQL it can't be helped but SQL Server already has a migration tool called "Data Migration Assistant". I think that only works for SQL Server and Azure though.

Is your CLI for migrations going to be similar to the .NET Core Entity Framework Core CLI?
It basically does Code-First migrations so to speak.

**Comment by SyrianBallaS** [comment]
Awesome, I can (possibly) actually view results from my changes.
