### ISSUE TITLE
Issue with "Last Updated" sorting

### ISSUE THREAD

**Issue by ViperZang** [RetroAchievements/RAWeb#841]
Sorting Game List by Last Updated (IDs `6` and `16`) don't seem to follow an order.

Game Boy Color for example:
![image](https://user-images.githubusercontent.com/31069034/137034639-f64f26ab-9472-4803-9557-d4a6132a012d.png)

**Comment by anegoda1995** [comment]
You right. Order by last updated field looks broken.
Code for sorting is here:
```
       case 6:
            $query .= "ORDER BY gd.ConsoleID, ach.DateModified DESC, Title ";
            break;
        case 16:
            $query .= "ORDER BY gd.ConsoleID, ach.DateModified ASC, Title DESC ";
            break;
```

Who know, why here is not only ordering by **DateModified**?

**Comment by anegoda1995** [comment]
I fixed the issue, but anyway I don't understand why we need to sorting more than by one column. It will be good to get more information about code from previous commentary.

**Comment by luchaos** [comment]
> Who know, why here is not only ordering by DateModified?

Ordering by `ConsoleID` first makes the grouping of games work on the "All Games" page (`gameList.php` without the `c` query parameter - "All games of all systems").

Additionally sorting by title makes sure that games within the same system and with a potentially identical "Last Update" value are at least ordered alphabetically. Probably not necessary but doesn't seem to hurt performance that much either.

**Comment by luchaos** [comment]
> I fixed the issue, but anyway I don't understand why we need to sorting more than by one column. It will be good to get more information about code from previous commentary.

Looking at it, it really isn't consistent with the ordering by ConsoleID 🤔 . I was about to suggest that we move that `ORDER BY gd.ConsoleID` above the switch to make sure it's consistent but it seems for some sorting purposes the column that's actually sorted by was more important - in particualr for `NumLBs` and `OpenTickets`. I can understand the latter somehow - to make it easier for QA, but the NumLBs preference makes no sense imo.
