### ISSUE TITLE
Bug: Bad new password message not showed

### ISSUE THREAD

**Issue by nickmafra** [RetroAchievements/RAWeb#845]
### Steps to reproduce:
 - Click on "Forgot password?"
 - Click on the link received in your email inbox
 - Type a bad pass: "a" for example
 - Click on "Change Password"

### Expected behaviour:
Show a popup contaning instructions to type a valid password.

### Current behaviour:
Redirecting to "https://retroachievements.org/?e=notloggedin".

**Comment by Tsearo** [comment]
Might not hurt to also add a note that some special characters in the password can cause login issues with RetroArch

**Comment by Jamiras** [comment]
> Might not hurt to also add a note that some special characters in the password can cause login issues with RetroArch

This shouldn't be happening. If you know of a special character that causes problems, please verify it's still a problem on the latest version, then write it up so it can be fixed.

**Comment by anegoda1995** [comment]
Maybe better to redirect to _same_ url, not to _controlpanel.php_ with **e** parameter and show it at this page?
