### ISSUE TITLE
Site Rank link always goes to page 1

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RAWeb#86]
The Site Rank link on the user profile page always links to the first page of top users. It should link to the page containing the user.

Additionally, the rank reported on the user profile page does not match the rank in the user list. For example, I'm 163 on my profile, but 150 on the list.

**Comment by kdecks** [comment]
This is almost certainly related to untracked status.

**Comment by Jamiras** [comment]
May be invalidated if we move to an exp-based system (#50)

**Comment by Jamiras** [comment]
#446 fixes the second issue. the rank on the user page now matches the rank in the user list.

**Comment by Jamiras** [comment]
This appears to have been fixed.
