### ISSUE TITLE
Fix broken image avatar for players who have no avatar

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAWeb#89]
Due to a bug some players do not have an avatar, not even the default:
![image](https://user-images.githubusercontent.com/32706333/37230787-ebee5bda-23a5-11e8-992c-89d2a9acac73.png)

![image](https://user-images.githubusercontent.com/32706333/37230844-0b13243c-23a6-11e8-82a8-9c8c88a836d8.png)

This creates displays bugs on site. 

**Possible Solution**
Assign everyone without an avatar one, in a batch.
(Individual players can do this, but instead of playing whack-a-mole, asking individual players, which I've been doing, lets resolve the entire issue in one swoop.)

**Comment by luchaos** [comment]
image uploads should be fixed again. https://github.com/RetroAchievements/RAWeb/commit/c106752a95a7f57aa6671a2fbf0b4f9a5d26a3ed

**Comment by kdecks** [comment]
Good. What we now is to clean up all those accounts with broken images.

**Comment by luchaos** [comment]
i can write a console command for that - depending on when/if the laravel version goes online
another solution would be to have checks in place that displays the default image depending if the user's avatar image file does not exist.
in any case, rather easy to fix

**Comment by Jamiras** [comment]
Cross-referencing #79, hoping this will address both.

**Comment by meleu** [comment]
Looks like it was solved. Feel free to reopen the issue if it wasn't.
