### ISSUE TITLE
[Forums] Multiple URLs on the same line do not display correctly

### ISSUE THREAD

**Issue by BlacRyu** [RetroAchievements/RAWeb#898]
If multiple URLs are placed on a single line in a forum post, it ends up highlighting more text than it should, and displays some of the forum tags as text instead of consuming them. Here is an example:

> Source: 
> ```
> 2. [url=https://www.romhacking.net/hacks/3764/]Breath of Fire - Sound Restoration[/url] - Restores the music from the original SNES game. The music in the GBA game is pretty butchered, with lower quality instrumentation and certain sound channels just being removed without compensation. This leads to some of the melodies disappearing or being butchered. For example, [url=https://youtu.be/4PmXU1P50bQ?t=27]here is the original culvert track[/url], and [url=https://www.youtube.com/watch?v=5XE7ucjRTtQ&t=26s]here is the GBA version[/url].
>   ```
> As seen in the forum editor:
> ![RAWeb url bug - post source](https://user-images.githubusercontent.com/10762433/149608428-3ebf3e32-e219-4d2f-9df3-3031f5a21b2d.png)
>   
> Result: 
> ![RAWeb url bug - post result](https://user-images.githubusercontent.com/10762433/149608429-611fc29b-7ad6-45f2-a9cb-559f3f0c951c.png)
> 

All of the urls included in the post end up being clickable, but they are represented by the wrong text. 

If I separate the urls so that each one is on a separate line in the post's source, then it works properly, as seen here: 

> Source:  
> ```
> 2. [url=https://www.romhacking.net/hacks/3764/]Breath of Fire - Sound Restoration[/url] - Restores the music from the original SNES game. The music in the GBA game is pretty butchered, with lower quality instrumentation and certain sound channels just being removed without compensation. This leads to some of the melodies disappearing or being butchered. 
> For example, [url=https://youtu.be/4PmXU1P50bQ?t=27]here is the original culvert track[/url].
> And [url=https://www.youtube.com/watch?v=5XE7ucjRTtQ&t=26s]here is the GBA version[/url].
> ```
> Result: 
> ![image](https://user-images.githubusercontent.com/10762433/149609948-660f9e80-c76e-4c43-bedc-0dffd42ff389.png)

**Comment by BlacRyu** [comment]
I made a test post to see if this affects any other forum tags, but from what I can tell it seems to only be an issue with the [url] tag: https://retroachievements.org/viewtopic.php?t=14921&c=105498

**Comment by RALordAndrew** [comment]
It should be fixed once #896 goes live.

**Comment by luchaos** [comment]
Fixed by #896
