### ISSUE TITLE
Add timestamps to all resources

### ISSUE THREAD

**Issue by luchaos** [RetroAchievements/RAWeb#92]
All database tables should include a `CreatedAt` and `UpdatedAt` timestamp column (or similar).

- [x] Write migration
- [x] Prefill timestamps where applicable

**Comment by Jamiras** [comment]
#52 briefly discusses having four audit field (Created, CreatedBy, Updated, and UpdatedBy) specifically for achievements.

**Comment by luchaos** [comment]
implemented in v2
