### ISSUE TITLE
Ability to report broken achievements through the website

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RAWeb#95]
Several broken achievements are only noted by comments in the game page, official game forum, or even in the achievement page. There should be some way to report broken achievements from the website (probably from within the achievement page). 

This also addresses the lack of ability to report broken achievements from RetroArch. Unfortunately, we would lose the automatic submission of the MD5 the player was using, but it would be easy to include a field that could be filled in if the user was feeling helpful. I would also recommend having a selector for choosing which emulator was being used (RetroArch vs RAxxx).

**Comment by meleu** [comment]
I may be wrong, but IIRC @GameDragon2k said on discord that he's working on it...

**Comment by GameDragon2k** [comment]
Yep, I'll try to have it up soon

**Comment by meleu** [comment]
Closing this issue. It was solved on PR #97
